### ISSUE TITLE
Wild Pokemon Level Increase Only Works for Some Cases

### ISSUE THREAD

**Issue by DatXFire** [Ajarmar/universal-pokemon-randomizer-zx#1]
Version: 3.0.2
Game: HeartGold
Issue: Wild Pokemon level increase does not seem to affect wild Pokemon levels outside of specific cases like fishing and surfing. I've attached a log file with only wild Pokemon randomized and a 50% level boost. It is very clear to see when it applies to fishing/surfing (E.g. New Bark Town Old Rods are at Level 15, but Route 32 wilds are at 4-6 instead of 6-9). Not sure if it is only like this in HG, or if it applies to other games as well.
[wildboosttest.nds.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/4686887/wildboosttest.nds.log)

**Comment by tom-overton** [comment]
This doesn't seem to affect either Platinum or White 1, so I'm guessing this may be HGSS-only. I've uploaded two logs with the same settings as above:
[platinum.nds.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/4693121/platinum.nds.log)
[white.nds.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/4693122/white.nds.log)
