### ISSUE TITLE
[Feature Request] Disallow Battle-Only Forms with Randomized Alternate Forms

### ISSUE THREAD

**Issue by sora10pls** [Ajarmar/universal-pokemon-randomizer-zx#10]
There are various Alternate Forms that can only be obtained when in battle. When randomizing with Alternate Forms enabled, this can significantly break the Pokémon in question. A good example is Aegislash; if randomized to have Form 1 (Blade Form), its animations fail to load properly and will always be shown in Blade Form. Some others like Castform and Cherrim will immediately revert to their base Form when sent out into battle (assuming weather doesn't match Alt Form), which defeats the purpose of the feature.

In pkNX, we have [a list of Species with Battle-Only Forms](https://github.com/kwsch/pkNX/blob/caf9e635b42fc7ed95bba25bf7bee2eec9314dbb/pkNX.Structures/Legality/Legal.cs#L195-L210) that are set to never be given an Alternate Form when randomizing for this very purpose:
```csharp
        public static readonly HashSet<int> BattleForms = new HashSet<int>
        {
            (int)Species.Castform,
            (int)Species.Cherrim,
            (int)Species.Meloetta,
            (int)Species.Aegislash,
            (int)Species.Xerneas,
            (int)Species.Wishiwashi,
            (int)Species.Mimikyu,
            (int)Species.Cramorant,
            (int)Species.Eiscue,
            (int)Species.Morpeko,
            (int)Species.Zacian,
            (int)Species.Zamazenta,
            (int)Species.Eternatus,
        };
```
Note: Darmanitan also belongs in this list, though because pkNX handles Generation 8 and its Galarian Form/Galarian Zen Mode, it's handled elsewhere.

I think it would be best if Alternate Form randomization skipped these Species in particular. It could even be given its own checkbox if people wish to have these buggy forms... for whatever reason. Mega Evolutions and Primal Reversions could also be handled separately since they function normally enough when forced to be encountered that way, but I leave that up to your discretion.

**Comment by Ajarmar** [comment]
Some of these are already excluded from appearing (Xerneas, Mimikyu, and I think Cherrim as well). As for the others - I'm a bit curious about this (and I wouldn't be surprised if there were version differences between different generations/games), because I know that most of them _don't_ break if the opponent sends them out (I've seen it in practice with Castform, Meloetta and Aegislash). In that case this would be an issue exclusively with these Pokemon appearing in contexts where the player can get them; in which games have you seen these forms causing issues?

**Comment by sora10pls** [comment]
* Castform and Cherrim may not break, though if Abilities are kept vanilla, they immediately revert if weather doesn't line up
* Meloetta works fine, though may not revert from Pirouette => Aria after battle as intended (only changes when using Relic Song in battle)
* Aegislash was tested in XY (probably affects ORAS too, SM/USUM could be different); when using King's Shield, its Form swap animation would play, but it would break and show Blade Form the entire battle
* If Xerneas, Wishiwashi, and Mimikyu are handled, then those can be left as is

**Comment by Ajarmar** [comment]
The special case depending on whether or not abilities are vanilla is probably how I'd do it, yeah. Ultimately I think this is a pretty niche case, but I'll probably include it in some future update
