### ISSUE TITLE
Not really an issue, but can I edit the shiny chance for wild encounters?

### ISSUE THREAD

**Issue by brigglechungus** [Ajarmar/universal-pokemon-randomizer-zx#101]
figured it would be possible since you can change trainer's shiny chance

**Comment by tom-overton** [comment]
No, this isn't possible, nor will it likely be possible in the future. It is vastly different from editing whether a trainer Pokemon is shiny. In Gen 7 (the only game we support in which trainers can have shiny Pokemon), a trainer Pokemon being shiny or not is a single true/false flag; thus, we can randomly flip this flag on to create random shiny trainer Pokemon. For wild Pokemon, shiny odds are controlled by code, and we would have to go in and make code patches for *every* single game (except the Gen 1 games I suppose) to allow you to edit the odds.
