### ISSUE TITLE
request - Is it possible to have the game ID modified when randomizing to a .3ds file?

### ISSUE THREAD

**Issue by Hellfir** [Ajarmar/universal-pokemon-randomizer-zx#103]
Unsure due to my lack of knowledge on 3ds roms. Main reason for wanting this is so that Citra can have save files for each randomized rom, since it currently saves game data to a folder titled with the game id.

**Comment by tom-overton** [comment]
I don't think this functionality belongs in the randomizer. We also output layeredFS, where matching the original title ID is necessary to make it function, and we support game updates, where matching the original title ID is also important. However, this is a pretty easy thing to do, so I just built a little tool that does it:

Release: https://github.com/tom-overton/3ds-title-id-editor/releases
Source code: https://github.com/tom-overton/3ds-title-id-editor

We normally don't take feature requests, so as a result I am not offering any support for this tool outside of just providing it to you. If it doesn't work, you'll have to figure out why yourself.

**Comment by Hellfir** [comment]
Just wanted to let you know that it (probably) works perfectly! I ported it over to python though since that's easier for me to run from linux. Mostly finished.

**Comment by tom-overton** [comment]
Awesome! I checked your repo and and your code looks great. Nice work! I assumed you were on Windows (since most people are) so I cooked up a pretty crappy Windows Forms app, but you did a great job moving it to Python.

**Comment by Hellfir** [comment]
I actually just moved over to linux, hence the switch, but if I had asked for it a few weeks ago it would have done well!

At some point I'm tempted to attempt some sort of wrapper script for the rando that just takes a rom and a settings file and mashes them together on the command line and hopes for the best, but I'd have to study the rando for a while to make that happen I think.
