### ISSUE TITLE
"Unhandled exception when trying to load your rom"

### ISSUE THREAD

**Issue by samurottwho** [Ajarmar/universal-pokemon-randomizer-zx#104]
I'm trying to randomize my Ultra Sun copy and every time I try, I get the error message that there was an unhandled exception. I don't know enough to diagnose the issue by myself so any help would be extremely appreciated. Here's the error file:
[error_2021-01-24-21-44-28.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5864033/error_2021-01-24-21-44-28.txt)

**Comment by tom-overton** [comment]
The error looks pretty clear to me:
> com.dabomstew.pkrandom.exceptions.RandomizerIOException: java.io.IOException: No space left on device

Try freeing up space on whatever drive you have the randomizer on. If you're randomizing Ultra Sun you'll probably want at least 6 GB free, since it's a fairly large game.

**Comment by tom-overton** [comment]
Closing because this is a pretty obvious fix. Just make some space and try again.

**Comment by Rare7Rex** [comment]
nops doesn't work
