### ISSUE TITLE
I dont know what this means

### ISSUE THREAD

**Issue by Elc422** [Ajarmar/universal-pokemon-randomizer-zx#105]
[error_2021-02-02-18-37-33.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5915523/error_2021-02-02-18-37-33.txt)

**Comment by Ajarmar** [comment]
Haven't encountered this error before so I can't be sure about the exact reason, but this seems like it might be because of a corrupted ROM. You should try using a different ROM and see if it works.

**Comment by tom-overton** [comment]
@Elc422 Did you try a different ROM? If so, did it work?

**Comment by tom-overton** [comment]
Closing as the OP hasn't responded for a week. @Elc422 if you return, please try again with the newly-released v4.1.0
