### ISSUE TITLE
Can´t open Rom

### ISSUE THREAD

**Issue by IY0NAI** [Ajarmar/universal-pokemon-randomizer-zx#106]
As said in the title I can´t open the Rom. The game is pokemon X and i´ve attached the error txt.
[error_2021-02-03-14-03-12.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5918608/error_2021-02-03-14-03-12.txt)

**Comment by tom-overton** [comment]
This is a really old issue we fixed in 4.0.1. We're now on 4.0.2, so download that here: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases/tag/v4.0.2

**Comment by IY0NAI** [comment]
Thanks for the help! I must have accidently downloaded an old version of the randomizer..
