### ISSUE TITLE
Problems Launching it

### ISSUE THREAD

**Issue by Miguel5885** [Ajarmar/universal-pokemon-randomizer-zx#107]
When I try to open the launcher I get this error 
![image](https://user-images.githubusercontent.com/65354491/106822518-94e75380-667f-11eb-8269-c08af4f6f5a9.png)
And when I try to open PokeRanzoZX I get this error 
![image](https://user-images.githubusercontent.com/65354491/106822687-d677fe80-667f-11eb-9160-a26e8cdb22de.png)

I have all the files in a carpet
![image](https://user-images.githubusercontent.com/65354491/106822749-ee4f8280-667f-11eb-960b-dde518c5d6fb.png)

Please let me know how I can fix it

**Comment by tom-overton** [comment]
Huh, I haven't seen this since #30. If you open a command prompt and run `java -jar launcher.jar` does that work?

**Comment by Miguel5885** [comment]
It worked now, thanks
