### ISSUE TITLE
Metronome not working

### ISSUE THREAD

**Issue by Deadvid** [Ajarmar/universal-pokemon-randomizer-zx#108]
I was trying to randomize a copy of Pokémon White 2 but every time I selected 'Metronome Only Mode' and then randomized it, it would not work and instead gave me this every time.
[error_2021-02-07-19-28-04.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5938515/error_2021-02-07-19-28-04.txt)

**Comment by tom-overton** [comment]
Sorry about that, will be fixed in the upcoming release.
