### ISSUE TITLE
Rival Pokemon very high level

### ISSUE THREAD

**Issue by Duzzpartner** [Ajarmar/universal-pokemon-randomizer-zx#109]
I'm assuming the 'Percentage Level Modifier' is by percentage, so at 50, everything is multiplied by 1.5. However, my rival is starting with Pokemon between 27 - 32 and I'm unsure why.

**Comment by tom-overton** [comment]
Can you provide a log file demonstrating this? I don't even know what game you're talking about with the information you've currently provided.

**Comment by Duzzpartner** [comment]
Sorry! More information: Playing Fire Red. It seems to be that if I choose the same ROM file over and over, each time every Pokemon's levels continued to rise. Apparently this was just me being dumb and I need to randomize using a fresh ROM file everytime and not just overwriting it.

**Comment by tom-overton** [comment]
Ohhhhhh, yeah, that'll do it. Assuming the romcode didn't get changed, we don't detect a randomized ROM any differently from a non-randomized one, so it probably didn't look any different in the UI. You need to use a fresh file each time.
