### ISSUE TITLE
Log Missing From Mac

### ISSUE THREAD

**Issue by Scep-X** [Ajarmar/universal-pokemon-randomizer-zx#111]
Whenever I try to load the randomizer, it tells me to check the log file. Problem is, there is no log file, so I can't figure out how to open it. I have the latest version of Java.

**Comment by tom-overton** [comment]
I wonder if this is some sort of security/permissions thing. Can you try the following?
1. Move the randomizer to a different directory and try again
2. Run the randomizer via the Terminal using `java -jar launcher.jar`
3. Assuming neither of those work, run using `sudo java -jar launcher.jar`

**Comment by Scep-X** [comment]
How do I change the directory? I'm not too good with mac.

**Comment by tom-overton** [comment]
By "move the randomizer to a different directory," I mean simply pick up the folder containing the randomizer and move it somewhere else with Finder.

As for the Terminal thing, if you're not familiar with a Mac, it's a bit confusing. You need to make sure the Terminal is "looking at" the folder with the randomizer in it. To do this, type the letters "cd", then press Space, then drag the folder with the randomizer in it onto the Terminal. Now press Enter and run the commands again.

**Comment by Scep-X** [comment]
it worked. thank you!
