### ISSUE TITLE
java not compatable

### ISSUE THREAD

**Issue by VoidChaos232** [Ajarmar/universal-pokemon-randomizer-zx#113]
![image](https://user-images.githubusercontent.com/79814201/109437006-8e4bc200-7a1a-11eb-823b-a968f507d891.png)
this keeps popping up

**Comment by tom-overton** [comment]
Please attach the launcher-log.txt file in that same folder.

**Comment by VoidChaos232** [comment]
what folder

**Comment by VoidChaos232** [comment]
[launcher-log.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6062741/launcher-log.txt)

**Comment by VoidChaos232** [comment]
@tom-overton please help

**Comment by VoidChaos232** [comment]
my discord is VoidChaos#0659 if u need anything else but i need this fixed

**Comment by Ajarmar** [comment]
You have an incompatible version of Java. You need Java version 8 (or higher), 64-bit. For more information, read this page: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java

**Comment by VoidChaos232** [comment]
i have Java installed ur randomizer is broken

**Comment by VoidChaos232** [comment]
![image](https://user-images.githubusercontent.com/79814201/109527398-812ae380-7aab-11eb-8228-235064931e0f.png)
I HAVE JAVA INSTALLED

**Comment by VoidChaos232** [comment]
![image](https://user-images.githubusercontent.com/79814201/109527439-90119600-7aab-11eb-8c7a-b9acb96a59fd.png)

**Comment by Ajarmar** [comment]
I don't doubt that you have Java installed, but I'm pretty sure you have _the wrong version_ of Java installed. Did you read the page I linked? It explains how you can check your Java version and where to download a new version of Java if you need to.

**Comment by VoidChaos232** [comment]
I have the java 8

**Comment by VoidChaos232** [comment]
java 8 enverimental

**Comment by Ajarmar** [comment]
Can you give me a screenshot of what result you get when typing `java -version` in a terminal window?

**Comment by VoidChaos232** [comment]
may i talk 2 u to show u my screen

**Comment by VoidChaos232** [comment]
what do u mean by terminal window

**Comment by Ajarmar** [comment]
You can open a terminal window like this:

1. Press Windows Key + R to open the "Run" window.
2. Type "cmd" and then press OK.

This will open a terminal window. Type `java -version` in it and press enter, and then take a screenshot of the result you get.

**Comment by VoidChaos232** [comment]
![image](https://user-images.githubusercontent.com/79814201/109528382-83da0880-7aac-11eb-925a-f5db94141139.png)

**Comment by Ajarmar** [comment]
Thanks. You have the wrong version of Java (specifically, you have Java 8, 32-bit version). You need the 64-bit version. On this page you can find links to where you can download a 64-bit version of Java (under the "Java Downloads" section): https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java

**Comment by VoidChaos232** [comment]
![image](https://user-images.githubusercontent.com/79814201/109528932-17abd480-7aad-11eb-9acf-de2aaf4569e4.png)
what one should i do??
