### ISSUE TITLE
Shedinja's evolutionsTo list missing Nincada -> Shedinja evolution in 3DS games

### ISSUE THREAD

**Issue by AaronCFreytag** [Ajarmar/universal-pokemon-randomizer-zx#115]
It seems like the Shedinja evolution is missing on Shedinja's side in gen 6 and 7 games. I've checked in Y, Omega Ruby, Sun, and Ultra Sun. The evolution is still present in Nincada's evolutionsFrom list, so I'm guessing it probably just isn't also being copied over to Shedinja's list.

Omega Ruby:
![image](https://user-images.githubusercontent.com/15931642/109469602-1afa7e00-7a23-11eb-9bf6-cb1a0def61f6.png)

Expected (Black 2):
![image](https://user-images.githubusercontent.com/15931642/109469624-22218c00-7a23-11eb-9897-f396cc456347.png)

**Comment by tom-overton** [comment]
Nice catch, thanks! You were pretty much right about the cause of it. Internally, there *is* no evolution between Nincada and Shedinja in the 3DS games. How it actually works is that there's a hardcoded check after any evolution to see if something just evolved *into* Ninjask; if so, then all the checks run to see if Shedinja should be created, and if they all pass, the Shedinja is *also* created in a very hardcoded manner. The evolutionsFrom entry on Nincada is manually created so the randomizer can know that Nincada -> Shedinja is a thing that exists, and we use this to replace all the hardcoded species IDs with whatever the result of the randomization was. However, I missed updating Shedinja's evolutionsTo with this evolution as well; that's now fixed.
