### ISSUE TITLE
actuallyCosmetic Pokemon don't copy TM/Tutor compatibility from base formes

### ISSUE THREAD

**Issue by AaronCFreytag** [Ajarmar/universal-pokemon-randomizer-zx#117]
It seems like the cosmetic formes of pokemon have their own randomized sets of TM/Tutor compatibility. I'm assuming this is a bug since the level up movesets of cosmetic pokemon are copied from their base formes. I'm not really sure whether this has an impact in the actual game itself but I thought I would mention it regardless.

Entries in TM compatibility list:
![image](https://user-images.githubusercontent.com/15931642/109590913-9dd21600-7ac1-11eb-8586-041540d4db55.png)

Judging on how it's done for other values being copied over to cosmetic formes, the solution is probably as simple as iterating over the actuallyCosmetic formes after randomizing compatibility and copying the compatibility from the base forme. I'll handle it if no one else has a particular reason they would rather do it.

**Comment by tom-overton** [comment]
Great catch! I actually noticed this when reviewing your PR, but since it was similarly broken in master, I didn't say anything. I think the solution you proposed is exactly how I would handle it too. If you want to take care of fixing this, we would absolutely appreciate it!
