### ISSUE TITLE
Pokémon Y doesn't randomize wild Pokémon

### ISSUE THREAD

**Issue by Th3Haakon** [Ajarmar/universal-pokemon-randomizer-zx#121]
Hi, so I'm trying to randomize Pokémon Y and some of the options doesn't work. During the randomize everything works fine but once I open the game (in Citra) only a few things are randomized, for example the attacks, the items or even the rivals pokemon are full randomized but the starters or the wild pokemon no. I tried using the European Rom and the USA one too, also I tried using the last version of the PokeRando ZX(4.0.2) and also the previous version (4.0.1) in both ROMs. Can anyone help me?

Sorry for my english, im Spanish.

**Comment by tom-overton** [comment]
I'm fairly certain what's happening is that you have a game update installed in Citra or on your 3DS. See if you have something like "Ver 1.5" on the file select screen like this:

![image](https://user-images.githubusercontent.com/12245827/97775269-90f5e380-1b1c-11eb-98de-e482b1db036b.png)

If you have a game update installed in Citra or on your 3DS, you have two options:
1. Delete the game update. You can follow the instructions [here](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Randomizing-the-3DS-games#managing-game-updates-in-citra) to delete it
2. Load a CIA of the same game update inside the randomizer. You can follow the instructions [here](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Randomizing-the-3DS-games#3ds-game-updates) to load it

**Comment by Th3Haakon** [comment]
Thank you!

I just tried deleting the game update and everything works fine now. 
Thank you very much!

**Comment by tom-overton** [comment]
Glad it worked for you!
