### ISSUE TITLE
Making multiple seeds?

### ISSUE THREAD

**Issue by cookcatt** [Ajarmar/universal-pokemon-randomizer-zx#122]
I'm doing the pokemon firered ironmon challenge, so every time I lose I have to restart with a **new seed**

I've been making them in batches so I can just open the next seed, but it's a hassle. Is there an easier way of doing this that I'm not seeing? When I watch ppl like iateyourpie play they just jump to the next game, so I'm unsure if I'm over complicating things or something...

**Comment by tom-overton** [comment]
You're not missing anything; there is no easier way of doing this.
