### ISSUE TITLE
Capping at around 16,000 kbs

### ISSUE THREAD

**Issue by Ludwig314** [Ajarmar/universal-pokemon-randomizer-zx#126]
The whole process works perfectly up until the saving point. At which point, the saving icon remains forever and when i end the process using task manager, i get a cxi file in my folder of the randomized rom. However, it is only 16 mb which is far from the size of the actual rom. I don't know if you have encountered any problems like this before but any help would be appreciated.

**Comment by Ajarmar** [comment]
1. Are you using the latest version of the randomizer? (v4.0.2)
2. Are you running the randomizer via the launcher?

**Comment by Ludwig314** [comment]
I am doing both of those things and it still doesn't work.

**Comment by Ajarmar** [comment]
Okay, a few more questions then.

Which game are you trying to randomize?

If you open task manager while a randomization is ongoing, does it look like your total memory usage or CPU usage maxes out?

And if you look at the Java processes (there will probably be several), what's the highest that the memory usage goes for either of them?

**Comment by Ludwig314** [comment]
I am trying to randomize pokemon Y, both memory usage and CPU usage remians low. And the highest memory usage is 300 mb /16 GB available.

**Comment by Ajarmar** [comment]
Hmm, this is weird. Does it work if you choose to generate a LayeredFS instead of a CXI?

**Comment by Ludwig314** [comment]
But i don't if there is any way to get from that to a usable file type.

**Comment by Ajarmar** [comment]
The guide here explains how to use a LayeredFS to play your randomized game: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Randomizing-the-3DS-games#guide-for-playing-your-randomized-layeredfs-directory-on-the-citra-emulator

I'm not sure what could be causing your CXI problem though. How long have you tried to let it run for?

**Comment by Ludwig314** [comment]
I have let it run for a few hours at one point and it can't get past that 16 mb boundary.

**Comment by Ajarmar** [comment]
Okay, it definitely seems stuck then.

Can you do the following for me?
1. Download v4.1.0 of the randomizer (it was released last week, [download link here](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases/download/v4.1.0/PokeRandoZX-v4_1_0.zip)).
2. Randomize the game (any settings are fine), save as LayeredFS, and choose to generate a log file after the randomization finishes. 
3. Upload the log file here.

**Comment by denaggels** [comment]
I encountered the same issue with a german Platinum ROM. 
A german SoulSilver ROM went through without any hick ups.

Used v4.1.0. Java is up-to-date and used Launcher.jar
If I can contribute to solving this issue, please tell me how.
