### ISSUE TITLE
X, Y and Omega Ruby crash when opening

### ISSUE THREAD

**Issue by zeraaaaa** [Ajarmar/universal-pokemon-randomizer-zx#13]
Alpha Sapphire is perfectly fine, so I'm kinda confused. Here's an error log:
[error_2020-09-27-12-41-37.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5288222/error_2020-09-27-12-41-37.txt)

**Comment by zeraaaaa** [comment]
Just checked and my CIA files work fine. Maybe my rom, will check back

**Comment by Ajarmar** [comment]
Same issue as https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/11, check the answers there
