### ISSUE TITLE
my java is not reading the launcher and randomizer file, java is 64 bitz[Help] windows 10, Pokémon Randomizer ZX v4.1.0 universal, java 64 bits

### ISSUE THREAD

**Issue by nicolasfir86** [Ajarmar/universal-pokemon-randomizer-zx#131]
**Describe your problem clearly:** 

**System (please fill in the following information):**
 - Operating System: 
 - Randomizer Version: 

**If your problem is that you can't start the randomizer:**
- If there is a `launcher-log.txt` created when you try to start the launcher, please attach it to this issue as an attached file.
- Open a terminal window (if you're not sure how, google your operating system + "terminal window"). Type in `java -version` and press Enter. Please include a screenshot of what you get:

**If your problem is that you can't randomize a game:**
If you get a popup saying that there has been an "unhandled exception", please attach the error log as an attached file to this issue.

**Comment by tom-overton** [comment]
Can you please edit your post to fill in the fields that the template is asking you to fill in? (e.g., Operating System, Randomizer Version, etc)

**Comment by nicolasfir86** [comment]
windows 10
Pokémon Randomizer ZX v4.1.0 universal
java 64 bits

**Comment by Ajarmar** [comment]
We have switched to a new launcher in v4.2.0. Please try downloading [the latest randomizer version](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases) and see if it works for you. If you run into problems with the new launcher, go here: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/221
