### ISSUE TITLE
Where's the Launcher

### ISSUE THREAD

**Issue by FrostFalcon** [Ajarmar/universal-pokemon-randomizer-zx#133]
I might just be blind, but I can't find the launcher for the randomizer. I've looked everywhere in the zip file, the closest thing I found was Launcher.java, rather than launcher.jar. I don't have a way to use it unless I go find the right program to run it with. I also tried loading it in eclipse and running it that way. It just throws a arbitrary error. To be sure, I'm on windows, and I just updated to the latest java version, 64 bit.

**Comment by tom-overton** [comment]
It sounds like you downloaded our code, rather than our pre-built releases. Head over to the releases page to grab a release instead: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases
