### ISSUE TITLE
Not a supported ROM?

### ISSUE THREAD

**Issue by Nadav-Nir** [Ajarmar/universal-pokemon-randomizer-zx#136]
I dumped pokemon omega ruby straight from my sd card using gm9 and when I put it into the randomizer it displays the error message: "Could not load 000400000011C400.00000000 Pokemon Omega Ruby (CTR-P-ECRA) (W).cxi - it's not a supported ROM"

Can I do anything about this?

**Comment by tom-overton** [comment]
Hmmm, I've dumped a game like that and it worked totally fine in 4.1.0. Since UPR also supports CIA files, can you dump as CIA (standard) and see if that works?

**Comment by Nadav-Nir** [comment]
![image](https://user-images.githubusercontent.com/73201814/112281899-3b6ad080-8c8f-11eb-9da3-8ec5176922cf.png)

**Comment by Nadav-Nir** [comment]
I am so sorry, just realized I am using the randomizer I downloaded from the website: https://pokehacks.dabomstew.com/randomizer/downloads.php

Sorry for wasting your time, I didn't pay attention to where I was downloading from and when it was uploaded.
