### ISSUE TITLE
[Help] 

### ISSUE THREAD

**Issue by Nadav-Nir** [Ajarmar/universal-pokemon-randomizer-zx#137]
**Describe your problem clearly:** 

**System (please fill in the following information):**
 - Operating System: Windows 64 bit
 - Randomizer Version: 4.1.0

**If your problem is that you can't start the randomizer:**
- If there is a `launcher-log.txt` created when you try to start the launcher, please attach it to this issue as an attached file.
[launcher-log.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6196549/launcher-log.txt)
- Open a terminal window (if you're not sure how, google your operating system + "terminal window"). Type in `java -version` and press Enter. Please include a screenshot of what 
you get:

![image](https://user-images.githubusercontent.com/73201814/112300332-66f6b680-8ca1-11eb-8749-674f66a6b43f.png)

**If your problem is that you can't randomize a game:**
If you get a popup saying that there has been an "unhandled exception", please attach the error log as an attached file to this issue.

**Comment by Ajarmar** [comment]
You need a 64-bit version of Java. More info here: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java (under "Java Downloads" there are links for where to download it)

**Comment by Nadav-Nir** [comment]
it works now, thanks!
