### ISSUE TITLE
[Bug] Type Themed setting for Foe Pokemon causes randomization to crash

### ISSUE THREAD

**Issue by bufar** [Ajarmar/universal-pokemon-randomizer-zx#138]
**To Reproduce**
1. Load a ROM
2. Go to *Foe Pokemon* tab
3. Select *Type Themed*
4. Click *Randomize (Save)*

**System:**
 - Operating System: Windows 10
 - Java Version: 1.8.0_281
 - Randomizer Version: 4.1.0

[error_2021-03-25-17-20-57.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6207955/error_2021-03-25-17-20-57.txt)

**Comment by tom-overton** [comment]
Thanks for the report! It will be fixed in the next release. For now, if you want to randomize type-themed trainers, please use version 3.1.0 or earlier.
