### ISSUE TITLE
[Contribution Idea]

### ISSUE THREAD

**Issue by FrostFalcon** [Ajarmar/universal-pokemon-randomizer-zx#139]
I was hoping to add a setting for the starter section, where instead of giving you 3 random starters out of any pokemon, it would give you a set of starters from any of the games. I actually coded this in the old randomizer before I realized this one existed. Problem now is I can't figure out how to add a button to the new UI, so 1. Do you think this is worth adding? 2. How do I make a button?

**Comment by Ajarmar** [comment]
Sorry, we think this is probably a bit too niche to be included as a feature because of how restrictive it is.
