### ISSUE TITLE
Ban Bad Item is impossible

### ISSUE THREAD

**Issue by kiliwily** [Ajarmar/universal-pokemon-randomizer-zx#14]
It is impossible to ban bad items when i try to randomize the items of the starters. The option is greyed out, even if i set the option to randomize the starter items. I used a english Pokemon Emerald Rom.

**Comment by Ajarmar** [comment]
Thanks for pointing this out. Fixed in f36eec74c477b2a21f26b44c2f8e64b881fffecb, will be included in the next release
