### ISSUE TITLE
Command-line Randomizer

### ISSUE THREAD

**Issue by sjb9774** [Ajarmar/universal-pokemon-randomizer-zx#141]
I had an idea bouncing around in my head regarding playing randomized Pokemon on a handheld Raspberry Pi setup and thought it might be convenient to have a CLI randomizer available for such a case. I imagine there also could be some use in pre-randomizing a large number of ROMs for some cases as well, and naturally for technically-inclined users a repeatable command is going to be much quicker than any GUI workflow. It was surprisingly easy to get a working program that takes a file path for settings, input ROM, and output ROM destination and spits out a randomized ROM and wanted to offer to share if it might be useful to others.

I defer to the regular contributors as to whether or not this would be a useful enough addition to warrant me submitting a Pull Request with the code for my current working example.

Example:
```bash
$ java -jar cli-randomizer.jar /Users/me/pokemon/ironmon-settings.rnqs /Users/me/pokemon/firered.gba /Users/me/pokemon/roms/randomzied-firered.gba
> Randomized successully!
```

**Comment by Ajarmar** [comment]
This is a nice idea, but we're trying to limit how much we include in the zip file we distribute in order to not confuse users - I think this would be great if it could go via the same jar file as the regular randomizer. So you'd have some specific argument that made it execute via CLI instead of starting the GUI, e.g. something like

`java -jar PokeRandoZX.jar cli ...`

**Comment by sjb9774** [comment]
@Ajarmar Understood, makes sense. Taking that suggestion into consideration I've created [this PR](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/pull/148) with the current iteration of the code I've been using.

(As a note, I have successfully been able to use this updated JAR on a Raspberry Pi to generate random ROMs on the fly for its emulator; pretty neat stuff!)
