### ISSUE TITLE
Unable to launch (MacOS)

### ISSUE THREAD

**Issue by N4164** [Ajarmar/universal-pokemon-randomizer-zx#142]
After installing multiple times, the application won't launch. I start by opening the launcher.jar, which fails due to security permission. Then once the security is cleared I launch it again to an error (although no log file is made, only a "config.ini" file). That file reads:

checkedcustomnames=true
checkedcustomnames172=false
unloadgameonsuccess=true
firststart=4.1.0

I try to launch the PokeRandoZX.jar file itself, which launches after another fail and clear of the security permission again. Subsequent attempts to launch via the launcher.jar all end in nothing being launched nor any files being created. When I launch via PokeRandoZX.jar, the program says I can't randomize 3DS titles, but I can't launch the program any other way.

Any ideas of what to do or how to get it to launch normally?

**Comment by Ajarmar** [comment]
Please read the "Java requirements" section here and make sure that you have a compatible version of Java: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java#java-requirements

**Comment by N4164** [comment]
I do. Terminal says it is the 1.8 64bit version, which should be the correct java version. I just downloaded it a few days ago.

**Comment by Ajarmar** [comment]
What error message do you get when you try to start the launcher?

**Comment by N4164** [comment]
It says "The launcher encountered an error. Error message can be found in launcher-log.txt."

There is no launcher-log.txt however. I've even searched for it using finder and nothing shows up.

**Comment by Ajarmar** [comment]
Can you try moving `launcher.jar` and `PokeRandoZX.jar` to a different folder and see if it makes any difference?

**Comment by N4164** [comment]
No, it does the same thing. It said to check console for error messages, and this is the section that seems applicable. Maybe it helps?


[console log.pdf](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6263669/console.log.pdf)

**Comment by Ajarmar** [comment]
Are you sure that came from the randomizer program? I don't see anything in there that seems relevant, and the randomizer also doesn't have any error message that says to check the console.

Anyway - can you try using this script as a launcher instead? It does the same thing as `launcher.jar` but is a lot more lightweight, so there are fewer things that can go wrong with it. Just unzip it, then put the script (`launcher_UNIX.sh`) in the same folder as `PokeRandoZX.jar` and run it. (GitHub doesn't let me upload the script directly, which is why it's zipped.)

[launcher_UNIX.zip](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6272722/launcher_UNIX.zip)

**Comment by N4164** [comment]
What program should I use to run it since it's a shell file?
<img width="558" alt="Screen Shot 2021-04-08 at 10 32 14 PM" src="https://user-images.githubusercontent.com/18110761/114133080-5148da00-98ba-11eb-8715-8e6203636acf.png">

**Comment by Ajarmar** [comment]
If it's not possible to double click the `.sh` file to run it, try renaming it to `launcher_UNIX.command` and see if it works to double click it.

If it still doesn't work, open a terminal window in the folder and run the following: `chmod +x launcher_UNIX.command` (This will set the file as executable). Then try to double click the file.

**Comment by N4164** [comment]
After renaming the file, setting it to executable, and double clicking it again, terminal gives me this message:

usage: dirname path
Unable to access jarfile PokeRandoZX.jar
Press Enter to exit...

**Comment by Ajarmar** [comment]
Huh, that's odd. I don't have much experience with Macs and also don't have one to test on, so you'll have to excuse that this is taking a while. Could you do the following for me?

Open `launcher_UNIX.command` in a text editor and add another line at the top that says `echo $0`. Save it and then try double clicking it again, and tell me what it says in the terminal. (This won't fix the problem, but you should get some more information in the terminal.)

**Comment by N4164** [comment]
Got this after adding the echo $0.

Last login: Sun Apr 11 02:16:28 on ttys001
noah@Noahs-MacBook-Pro ~ % /Users/noah/Desktop/Noah/Emulation/Pokemon\ Randomizer/launcher_UNIX.command ; exit;
/Users/noah/Desktop/Noah/Emulation/Pokemon Randomizer/launcher_UNIX.command
usage: dirname path
Error: Unable to access jarfile PokeRandoZX.jar
Press Enter to exit...

**Comment by Ajarmar** [comment]
Thanks, I see what the problem is now. Open up the script in a text editor again and make the following changes:

1. Remove the `echo $0` line.
2. Change the first line to `cd "$( dirname "$0" )"` (i.e. add quotes around `$0`)

Then save it, and try double clicking it again.

**Comment by N4164** [comment]
Great, now running the program with the script works perfectly. Thank you!!

**Comment by Ajarmar** [comment]
Nice! We're probably going to be moving towards a script-based launcher in the next release, so your testing of the script was useful for us as well. Thanks!
