### ISSUE TITLE
Clamperl Impossible Evolution

### ISSUE THREAD

**Issue by hepbest** [Ajarmar/universal-pokemon-randomizer-zx#143]
Clamperl does not evolve with Water Stone with the impossible evolution setting on FireRed. It looks like both evolutions are set to level 30.

https://i.imgur.com/3m1t3NI.png

**Comment by tom-overton** [comment]
Can you upload the log you're looking at? And can you specify which version of the randomizer you're using to generate your seed? I'm not seeing that in my testing with version 4.1.0 at all.

**Comment by hepbest** [comment]
I attached the log file from the file I noticed it in. When I look through the other log files I have, they also show both Clamperl evolutions as "at level 30" in the Impossible Evolution section. I tried to also attached the settings file I use, but file type is unacceptable. Do you want me to change the file type to upload it also?

[UltimateIronmon_FireRed_58.gba.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6221880/UltimateIronmon_FireRed_58.gba.log)

**Comment by tom-overton** [comment]
Thanks for the report. The problem was the combo of randomizing evos + doing Remove Impossible Evolutions; doing only the latter makes it work fine, which is what I was doing and thus why I didn't notice it before. Will go out in the next release.
