### ISSUE TITLE
I figured out why fossils were crashing...sort of [Bug] 

### ISSUE THREAD

**Issue by RevanXVIV** [Ajarmar/universal-pokemon-randomizer-zx#145]
Ok so it seems that issue I was having a few months ago seems to have made itself clearer.

So the reason fossils were crashing was because they were apparently randomized to holding an item, but even though it says they are holding an item, when checked in the PC, they in fact are not holding an item. The item name area is completely blank but the icon of holding an item is there. This also seems to happen for the Lavaridge spring egg.

There is a fix to this issue in-game where once you revive the fossil or hatch the egg keep them in your party, go into a wild battle, and then just run away and the problem should be solved.

However I'm reporting this in hopes this issue can be solved entirely for the future.

**Comment by tom-overton** [comment]
Just gonna close this one since I replied to #179
