### ISSUE TITLE
[Help] What app am i supposed to use to open the launcher? it says to choose an app i want to open with and it doesnt work opening with Desmume

### ISSUE THREAD

**Issue by jcthivierge** [Ajarmar/universal-pokemon-randomizer-zx#147]
plz help

**Comment by Ajarmar** [comment]
You need to open it with Java.

**Comment by tom-overton** [comment]
Just gonna close this one, as yeah, like Ajarmar said, you need to use Java. For more information, see our wiki page [About Java](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java)
