### ISSUE TITLE
Generation 8 compatibility?

### ISSUE THREAD

**Issue by Amazee-Dayzee** [Ajarmar/universal-pokemon-randomizer-zx#149]
Will generation 8 also be able to be used with this eventually in a few years time or is generation 7 as far as it will go? I know generation 8 is still pretty new but I just wanted to know if eventually this program will be expanded to that one.

Also does this work with the two Let's Go games?

**Comment by Ajarmar** [comment]
We're not working on Gen 8 support at the moment, we'll see what the future holds.

We don't support the Let's Go games, the latest game that works with the randomizer is Ultra Sun/Ultra Moon.

**Comment by Amazee-Dayzee** [comment]
> We're not working on Gen 8 support at the moment, we'll see what the future holds.
> 
> We don't support the Let's Go games, the latest game that works with the randomizer is Ultra Sun/Ultra Moon.

Will what the future holds also include support for the Let's Go games or are you never gonna going to work on that? Just figured I would ask.

**Comment by Ajarmar** [comment]
Not sure, can't really say for certain that we will or won't do it because we haven't planned anything. That said, if we did start working on support for more games, Let's Go probably wouldn't be the first since it's less interesting as a randomized game due to its very limited Pokemon pool

**Comment by Amazee-Dayzee** [comment]
> Not sure, can't really say for certain that we will or won't do it because we haven't planned anything. That said, if we did start working on support for more games, Let's Go probably wouldn't be the first since it's less interesting as a randomized game due to its very limited Pokemon pool

But if you did do it at some point and I'm not saying that you will or you won't, Pokemon Let's Go would be done but it would be the very last?

**Comment by Ajarmar** [comment]
Maybe. As I said, we haven't planned anything, so I can't say whether or not we would do it.

**Comment by Amazee-Dayzee** [comment]
Just as long as it is possible that you and your team would, that is enough for me. <3
