### ISSUE TITLE
Can't Randomize (Save) - stuck on "Saving" [Bug] 

### ISSUE THREAD

**Issue by agoodboyatheart** [Ajarmar/universal-pokemon-randomizer-zx#151]
**Describe the bug**
When trying to randomize (save) the screen becomes stuck on saving indefinitely. The only way to close the window is to force via task manager, and when I do the log doesn't produce anything to describe the issue. I have only been able to reproduce this when trying to randomize trainer pokemon as Type themed only. When using other settings it works fine. 

**To Reproduce**
1. Pokemon Red Version
2. Settings enabled: Type Themed Trainers 
3. Click Randomize (Save)
4. Stuck on saving
5. 
**Screenshots**

![image](https://user-images.githubusercontent.com/81884525/113493377-18a7aa00-9522-11eb-8c12-ea9d2bd22fb1.png)

**System (please complete the following information):**
 - Operating System: Windows 10 64-bit
 - Java Version: Version 8 Build 281 
 - Randomizer Version: 4.1.0

**Additional context**

I have one set of settings that produces the above issues and one that works. Please let me know if you would me to provide these for troubleshooting purposes.  I'm not sure if it is an interaction between the Type Themed trainers setting and another.

**Comment by Ajarmar** [comment]
Fixed in https://github.com/Ajarmar/universal-pokemon-randomizer-zx/commit/10d1d68040d196f8036b4f3e3ef947c35343ec9a, so this should work with the next release of the randomizer.

**Comment by ToonKnight** [comment]
Having the same issue with 4.2.1
