### ISSUE TITLE
[Help] All of the files inside the thing you download on this website are zipped

### ISSUE THREAD

**Issue by AlphaReps** [Ajarmar/universal-pokemon-randomizer-zx#152]
**Describe your problem clearly: The files inside of the WinRAR thing you download from this website are zipped, even after I extract them.

**System (please fill in the following information):**
 - Operating System: Windows 10
 - Randomizer Version: Version 4_1_0
![Annotation 2021-04-03 213847](https://user-images.githubusercontent.com/81888950/113496203-398de200-94c5-11eb-9dbd-402b6e4bf7cb.png)

**Comment by denaggels** [comment]
You set your computer to automatically open jar files with winrar. you have to open them with java instead

**Comment by AlphaReps** [comment]
> You set your computer to automatically open jar files with winrar. you have to open them with java instead

Thank you for the advice and quick response. Sorry to ask, but im not really sure how to do that. If you could tell me great if not I can try to look it up

**Comment by Ajarmar** [comment]
Closing since this seems to be solved.
