### ISSUE TITLE
[Bug] Saving loop narrowed down to special shops on german platinum version

### ISSUE THREAD

**Issue by denaggels** [Ajarmar/universal-pokemon-randomizer-zx#153]
When randomizing Pokemon Platinum - german version I encounter an infinite "saving" time. The randomizer cant then only be shut down via task manager. 

Randomizer is v4.1.0 and I used the launcher.jar
Java is up-to-date and the correct version.
Windows 10 is my operating system.

Other Roms I tested don't encounter this bug.

I tried every single setting I previously checked alone and the special shops seem to be the root.
Shuffling them produces [this error](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6254450/error_2021-04-04-13-26-07.txt) and randomizing them cause the infinite saving loop.

I hope this helps narrowing down the solution or problem. I am willing to provide help if I am able to and it is needed.

Thank you for still working on this!

P.S.: I did not test settings I did not want like random stats, types, evolutions or move pools

**Comment by Ajarmar** [comment]
Thanks for narrowing it down, it helped me figure out what was wrong. This will be fixed in the next release of the randomizer
