### ISSUE TITLE
after randomizing the rom, the randomized CXI file is not produced [Bug] 

### ISSUE THREAD

**Issue by calebka881** [Ajarmar/universal-pokemon-randomizer-zx#155]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - Operating System: 
 - Java Version:
 - Randomizer Version: 

**Additional context**

**Comment by Ajarmar** [comment]
Please describe the problem in more detail. What happens after you press "Randomize"? Does it get stuck on saving forever?

**Comment by calebka881** [comment]
im an idiot i just didnt update to the newest patch
