### ISSUE TITLE
[Help] Need help launching randomizer

### ISSUE THREAD

**Issue by johnnyrrodgers** [Ajarmar/universal-pokemon-randomizer-zx#158]
When i double click on the launcher.jar file it just opens up another folder (with all the files inside it)...its not launching the application. 
I have windows 10, with java 64bit. 
when i run the "java -Xmx4096M -jar PokeRandoZX.jar" in the command prompt, it runs/launches perfectly, however, this limits the usability of the randomizer because it was not launched from the "launcher.jar" file

any ideas what is happening?

**Comment by Ajarmar** [comment]
You have some non-Java program associated with the .jar filetype (probably WinRAR or something similar). Right-click the launcher, click "Open with" and select Java. You should also be able to set Java as the default program for .jar files from there.

**Comment by johnnyrrodgers** [comment]
sweet, i had to change it in properties...just clicking "open with" wasn't doing it. thanks
