### ISSUE TITLE
[Bug] Cannot choose No Game Breaking Moves

### ISSUE THREAD

**Issue by CoolWizard22** [Ajarmar/universal-pokemon-randomizer-zx#163]
On previous versions of the universal randomizer, the "No Game Breaking" moves option was in the "General Options".

Now it is in "Pokemon Movesets" and can only be selected by choosing "Random Movesets"

I think it was better where it was before since I don't want to randomize moves but do want to remove moves like Dragon Rage. Or at least mons that have those moves in the early stages of the game.

**Comment by tom-overton** [comment]
There is no bug here. On previous versions of the randomizer, selecting "No Game Breaking Moves" without randomizing movesets does nothing at all. The option can still be selected, but it has no effect; as a quick example, [Charmander can still learn Dragon Rage at level 16](https://i.imgur.com/AXovCAB.png) even with this checked. The only difference between current versions of the randomizer and older versions is that the option is correctly disabled when it doesn't do anything.
