### ISSUE TITLE
location of pokemon

### ISSUE THREAD

**Issue by OmegaYato37** [Ajarmar/universal-pokemon-randomizer-zx#166]
I'm done playing my nuzlocke and I want to check back and use some of the pokemon i couldn't try out but it doesn't tell me the location of where that pokemon is at

**Comment by tom-overton** [comment]
This information is in the log file. You had the option of creating it by saying "Yes" to this dialog prompt.

![image](https://user-images.githubusercontent.com/12245827/115126882-33006f80-9f87-11eb-8056-18aadbc773a4.png)

If you said "No" (or lost the file), then you will simply never know, sorry.

**Comment by OmegaYato37** [comment]
I do have the log it just doesn’t tell me where they are it shows me all
the other info like abilities or trainers that have it

**Comment by tom-overton** [comment]
You're looking for the section titled "Wild Pokemon" like so:

```
--Wild Pokemon--
Set #1 - New Bark Town Surfing (rate=15)
MAGBY Lvs 15-25          HP 45  ATK 75  DEF 37  SPATK 70  SPDEF 55  SPEED 83 
PARAS Lvs 10-20          HP 35  ATK 70  DEF 55  SPATK 45  SPDEF 55  SPEED 25 
POLIWRATH Lvs 15-25      HP 90  ATK 85  DEF 95  SPATK 70  SPDEF 90  SPEED 70 
LILEEP Lvs 15-25         HP 66  ATK 41  DEF 77  SPATK 61  SPDEF 87  SPEED 23 
FLYGON Lvs 15-25         HP 80  ATK 100 DEF 80  SPATK 80  SPDEF 80  SPEED 100
```

**Comment by OmegaYato37** [comment]
Thanks, I'll check it out.

**Comment by OmegaYato37** [comment]
Nothing shows up
