### ISSUE TITLE
[Bug] Pokemon Platinum Version not working

### ISSUE THREAD

**Issue by AxelElric8** [Ajarmar/universal-pokemon-randomizer-zx#167]
**Describe the bug**
When I randomize the Spanish Platinum Version it doesn't work. it doesn't generate the rom, it stays loading and never ends. I have to close the task manager cause i can't close the launcher.

**System (please complete the following information):**
 - Operating System: Windows 10
 - Java Version: SE 11
 - Randomizer Version: 1.4.0

**Comment by tom-overton** [comment]
Can you supply a log file that demonstrates what you mean by "doesn't work"?

**Comment by AxelElric8** [comment]
> Can you supply a log file that demonstrates what you mean by "doesn't work"?

no, I can't because it doesn't generate the rom, it stays loading and never ends. Sry if I don't explain myself.

**Comment by tom-overton** [comment]
Hmm, okay, thanks. In that case, can you post the settings you're using? You can get the settings string by hitting the Settings button and then hitting Get/Load Settings String. Just copy what's in the top box and paste it here. Here's a visual example if that helps:

![image](https://user-images.githubusercontent.com/12245827/115469150-f3d15900-a1e8-11eb-9d16-42a69775a327.png)

Just make sure the settings you're using are the same settings you were using before (the ones that fail to generate a ROM).

**Comment by AxelElric8** [comment]
There you have it
![image](https://user-images.githubusercontent.com/65228444/115469717-72ec7e80-a235-11eb-8889-ba052808b6bc.png)
I have the same issue with Diamond and Pearl version. I'm using the launcher, not the PokeRando, if you want to know.

**Comment by FreakyGamer** [comment]
i have the same problem with pokemon platin.
its just stuck in the Saving popup.  here is the Get/load string 

314GAgEAQKCAYUBiAEiAAKpIRgCLAMAFAA9GAABEwAAAAAABACAMpkyQQAICTIGBQAyFFBva2Vtb24gUGxhdGludW0gKEcplE2OuuPDOIo

![image](https://user-images.githubusercontent.com/18227311/116385216-da4b9500-a818-11eb-81a6-ba3e8b9d486e.png)

**Comment by Maffimo** [comment]
I have the same problem. I am using some configutations that are not present in the original upr, where it workd
I am using the italian version of the game, if that matters

314AygEAQKCAYUBiAEEAAEeJAgCTAAATAA9AQABAgAAAAAABAyAMoEyAQAICTIICAAyFFBva2Vtb24gUGxhdGludW0gKEkpf5KafOPDOIo=

![image](https://user-images.githubusercontent.com/43404824/116793656-49024a00-aac8-11eb-9758-34f2dafac474.png)

**Comment by Ajarmar** [comment]
Thanks for all the reports, the problem was with shop randomization and occurred in all non-English Gen 4 games. This will be fixed in the next release of the randomizer
