### ISSUE TITLE
[Bug] Base Stats Shuffle + Follow Mega Evolution not working

### ISSUE THREAD

**Issue by jonlocapo** [Ajarmar/universal-pokemon-randomizer-zx#169]
When you select 'Shuffle' and 'Follow Mega Evolutions' in any Gen 6-7 game, the randomizer shuffles the base mon's stats and the mega evo's independently, as if the second command hadn't been entered. Notably, this doesn't happen when using Random instead of Shuffle.

1. Select "Shuffle"
2. Select "Follow Mega Evolutions"
3. I selected "Update Base Stats" as well, haven't tested without it
4. Randomize the game
5. Open the log files and compare Base and Mega Stats

With "Follow Mega Evolutions", the Mega Stats should be the shuffled stats of the base form, plus the bonuses Mega Evolution gives them. Example using Alakazam in a Pokemon X log

 65|Alakazam               |PSYCHIC          |  45|  55| 135|  50|  95| 120|
770|Alakazam-Mega   |PSYCHIC          |  55| 175|  65|  50| 105| 150|

If this behaved normally, Alakazam-Mega's stats would be 55/55/175/50/105/150. You can see other examples in the logs

 - Operating System: Windows
 - Java Version: 8 update 241
 - Randomizer Version: 4.1.0

I haven't tested if this is just a log problem or if this is actually reflected in-game. Attaching both an X log and a Sun log, but this happens on any game with Mega Evolution
[Shuffle + follow X.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6358338/Shuffle.%2B.follow.X.log)
[Sun bug report.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6358339/Sun.bug.report.log)

**Comment by Ajarmar** [comment]
Thanks, this'll be fixed in the next release
