### ISSUE TITLE
Randomization for Gen 6 (at least)

### ISSUE THREAD

**Issue by CaronaCc** [Ajarmar/universal-pokemon-randomizer-zx#17]
I'm not quite sure if this is a me issue or an issue across multiple people's software but here's a small compilation of what didn't work when checked and what did work when checked:

Work:
Boss/Rival Battles Having 6 Members
Field Items Being Randomized
TM Compatibility Being Randomized
Abilities Being Randomized
Randomized Trainer Teams
Level Boosts

Did Not Work:
Starters Being Randomized (Rivals were able to choose the starters though. They were normal in my case)
Wild Pokemon Being Randomized (All encounters stayed the same as if nothing had been changed)
TM Moves Randomization (Compatibility was random but moves like Return stayed the same)
Special Shops (items in special shops were not randomized and still kept the same items as normal)

Any other options I had turned on I did not check to see if they had worked or not as I did not plan on playing too far with this many problems already. I tried on Pokemon Y a few different times, decrypted and everything, changed settings, and even redownloaded the randomizer. These problems all stayed the same no matter what. I have yet to come across another user who has encountered the same problems so I might just have issues on my end. Rom or not these issues persisted

**Comment by DatXFire** [comment]
Please see #16 and the [relevant page on the wiki regarding game updates](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Randomizing-the-3DS-games#3ds-game-updates).

**Comment by CaronaCc** [comment]
Thank you. I had checked both before and both were quite confusing in their wordings. I believe everything works now and if I find any other issues I'll make another post. Thank you for your help
