### ISSUE TITLE
[Bug] Failing to save file with filename in path. 

### ISSUE THREAD

**Issue by ShellbackSoftware** [Ajarmar/universal-pokemon-randomizer-zx#171]
When creating a seed, if you try to save the file as a string that exists in the filepath, it gets stripped from the filepath string, i.e.:
If you name it "m", then the save file looks for the path Desktop\Ros to save the file, rather than Roms. I tried saving as "t", and the file path ended up being "Deskop" rather than desktop. 

While writing this up, I checked and if I saved the file as "ms", then it looks for the "Ro" folder. 

Expected behavior is to save the file as whatever, without stripping the filename from the save path. 

The log throws a file not found exception, which lead me to look at the path. 

**System (please complete the following information):**
 - Operating System: W10
 - Java Version: 8 (just updated yesterday)
 - Randomizer Version: 4.1.0

**Additional context**
I haven't taken a look at the source code yet, but I'm assuming there's a str_replace (Java's version of it) getting greedy.

**Comment by ShellbackSoftware** [comment]
Forgot to add - I've only tried this with HeartGold, no idea if it is game specific or not.

**Comment by Ajarmar** [comment]
Good catch (it was a problem with all games, not just Heart Gold). Will be fixed in the next release
