### ISSUE TITLE
[Contribution Idea] - All Legendaries Options

### ISSUE THREAD

**Issue by apkaufman** [Ajarmar/universal-pokemon-randomizer-zx#174]
**Is your idea a new setting, a change to an existing setting, or something else? Please describe clearly:** 
It's actually several new settings. I used the Dabomstew universal-pokemon-randomizer as a base and already tested the five new options, with all legendaries for starters, static encounters, in-game trades, trainer Pokémon, and wild Pokémon.

**What problem would your contribution solve? Please describe:** 
I think it adds a new meta for these games, allowing you to add legendaries throughout the games. These options add several ways to make the games both harder and easier.

**Additional context:**
I already added the changes to a pull request on [my fork of that repository] (https://github.com/apkaufman/universal-pokemon-randomizer), before I found this repository, which seems to get updated more often than the Dabomstew one.

**Comment by Ajarmar** [comment]
Thanks, but we'll pass on this. This would be very restrictive - the randomization pools will be incredibly small (especially in earlier generations) and I have a hard time seeing it be a setting that appeals to many people.
