### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by Panthersfan1889** [Ajarmar/universal-pokemon-randomizer-zx#175]
Im trying to randomize alpha sapphire and I'm getting an annoying error every time i open the randomizer.  “The randomizer was not started via the launcher. You will not be able to load 3DS games into the randomizer.”

**Comment by tom-overton** [comment]
The error message is telling you what you need to do; launch the randomizer by using launcher.jar

**Comment by tom-overton** [comment]
Gonna close this because it's not an error, you just need to use the launcher. If the launcher doesn't work for you, feel free to open another issue.
