### ISSUE TITLE
I am trying to randomize a rom hack (Pokemon Theta Emerald Ex) and when I try to open the rom it says, there was an unhandled exception trying to load your rom. If anyone can help please do.

### ISSUE THREAD

**Issue by Ryzen3k** [Ajarmar/universal-pokemon-randomizer-zx#176]

**Comment by Ryzen3k** [comment]
[error_2021-04-27-14-22-43.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6387782/error_2021-04-27-14-22-43.txt)
here is the error file.

**Comment by tom-overton** [comment]
Sorry, we don't officially support ROM hacks. It looks like this ROM hack adds a bunch of Pokemon which breaks something.
