### ISSUE TITLE
Cannot open Alpha Sapphire Rom

### ISSUE THREAD

**Issue by CriminalPancake** [Ajarmar/universal-pokemon-randomizer-zx#178]
![image](https://user-images.githubusercontent.com/37886094/116498442-9d09f600-a85e-11eb-8aa5-2e0744e9fe20.png)

Above is the error that pops up when I try to open the rom, and below is the mentioned error log file.

[error_2021-04-28-20-14-12.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6396112/error_2021-04-28-20-14-12.txt)

**Comment by tom-overton** [comment]
Is this a ROM hack or something like that? Your ROM looks like this:
```
--ROM Diagnostics--
.code: 72B62B7F
romfs header: A2B66593
```

My Alpha Sapphire ROM, which works, looks like this:
```
--ROM Diagnostics--
.code: C1D8D6EA
romfs header: A2B66593
```
Regardless, I would suggest trying a different ROM, as it appears there's something about this one that isn't what we expect.

**Comment by CriminalPancake** [comment]
I was afraid of that being the issue, guess 3ds-cia has a bad rom because that's where I got this one.
