### ISSUE TITLE
[Bug] No randomization pokemon heartgold

### ISSUE THREAD

**Issue by Expensure** [Ajarmar/universal-pokemon-randomizer-zx#180]
The program is not working on heartgold version.

Loading the game normally without randomization works. but the rest doesnt. 

Logs:
Randomizer Version: 4.1.0
Seed: 252089578461795
Settings String: 314AAgEAQKXAJoAnQAEAAIeJAACCQAACQABAQABAAAAAAAAAACIMgEyAQAICTIGBQAyFVBva2Vtb24gSGVhcnRHb2xkIChVKZ9BwFjjwziK
Java Version: 15.0.2, Java HotSpot(TM) 64-Bit Server VM
ROM: Pokemon HeartGold (U)
Code: IPKE
Reported Support Level: Complete

java.lang.ArrayIndexOutOfBoundsException: Index 40 out of bounds for length 40
	at com.dabomstew.pkrandom.romhandlers.Gen4RomHandler.getMovesLearnt(Gen4RomHandler.java:2235)
	at com.dabomstew.pkrandom.romhandlers.Gen4RomHandler.setTrainers(Gen4RomHandler.java:2128)
	at com.dabomstew.pkrandom.romhandlers.AbstractRomHandler.randomizeTrainerPokes(AbstractRomHandler.java:1706)
	at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:338)
	at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$performRandomization$102(NewRandomizerGUI.java:869)
	at java.base/java.lang.Thread.run(Thread.java:832)

--ROM Diagnostics--
arm9: F1CCC042
a/0/0/2: DE8C5CAF
a/0/0/4: 347DA920
a/0/1/1: 284AEE7A
a/0/1/2: A7E3F740
a/0/2/7: 123DEB0B
a/0/3/2: 3AC93851
a/0/3/3: 2DF957F4
a/0/3/4: E1AA2D0A
a/0/5/5: E5912D15
a/0/5/6: BEB9A7DE

**System (please complete the following information):**
 - Operating System: Windows 10
 - Java Version: 11
 - Randomizer Version: 4.1.0

**Comment by Expensure** [comment]
I tried putting in the minor files myself using nitro, but the files don't randomize anything.

**Comment by Ajarmar** [comment]
Are you trying to randomize a ROM hack? Your ROM diagnostics don't match those of a regular Heart Gold ROM.

Yours:
```
arm9: F1CCC042
a/0/0/2: DE8C5CAF
a/0/0/4: 347DA920
a/0/1/1: 284AEE7A
a/0/1/2: A7E3F740
a/0/2/7: 123DEB0B
a/0/3/2: 3AC93851
a/0/3/3: 2DF957F4
a/0/3/4: E1AA2D0A
a/0/5/5: E5912D15
a/0/5/6: BEB9A7DE
```

Mine:
```
arm9: F1CCC042
a/0/0/2: DE8C5CAF
a/0/0/4: 373BBE93 <-- Different
a/0/1/1: 284AEE7A
a/0/1/2: A7E3F740
a/0/2/7: 123DEB0B
a/0/3/2: 3AC93851
a/0/3/3: F0F9B169 <-- Different
a/0/3/4: 6711E4B4 <-- Different
a/0/5/5: 8B9BD9CE <-- Different
a/0/5/6: E30BC8BE <-- Different
```

We don't officially support ROM hacks. Try using a regular Heart Gold ROM instead.

**Comment by tom-overton** [comment]
Closing this one due to lack of response from the OP. The HeartGold ROM does not look to be the original release, so please try again with the regular, unmodified game.
