### ISSUE TITLE
My launcher won't open

### ISSUE THREAD

**Issue by bobby3o** [Ajarmar/universal-pokemon-randomizer-zx#183]
**Describe your problem clearly:** 
I can't get it to launch

**System (please fill in the following information):**
 - Operating System: mac catalina
 - Randomizer Version: 4.1.0
![Screen Shot 2021-05-04 at 1 42 47 PM](https://user-images.githubusercontent.com/83673254/117067307-b2f43c80-acde-11eb-87bb-d1f03ee50f52.png)

I think I might just be being stupid but I can't find launcher.jar and I can only find launcher.java which brings up a bunch of code that doesn't run when I tell it to. I used this command from the readme java -Xmx4096M -jar PokeRandoZX.jar
but it said it couldn't access the jar file.

**Comment by tom-overton** [comment]
No worries, this actually happens all the time. You downloaded our source code when you needed to download one of our releases. You can [check out the Releases page](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases) to see all the releases, or you can just click this, which links directly to the latest release at the time of this writing: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases/download/v4.1.0/PokeRandoZX-v4_1_0.zip
