### ISSUE TITLE
Mac not launching

### ISSUE THREAD

**Issue by contiyeet** [Ajarmar/universal-pokemon-randomizer-zx#185]
**Describe your problem clearly:**
hi im using the following system + programs and the launcher will not open and give me this error
<img width="665" alt="Screen Shot 2021-05-09 at 9 19 13 PM" src="https://user-images.githubusercontent.com/83911201/117573739-37debc00-b10c-11eb-90e2-34d5951b9584.png">
<img width="409" alt="Screen Shot 2021-05-09 at 9 19 56 PM" src="https://user-images.githubusercontent.com/83911201/117573759-4e851300-b10c-11eb-91ed-9a27772f119e.png">
opening the launcher will NOT make the txt file 
also for some reason I could open the pokerando file but I could not upload roms according to the pop up message 

**System (please fill in the following information):**
 - Operating System: catalina 10.15.5 w/ latest java
 - Randomizer Version: 4.10.0

**If your problem is that you can't start the randomizer:**
- If there is a `launcher-log.txt` created when you try to start the launcher, please attach it to this issue as an attached file.
- Open a terminal window (if you're not sure how, google your operating system + "terminal window"). Type in `java -version` and press Enter. Please include a screenshot of what you get:
<img width="586" alt="Screen Shot 2021-05-09 at 9 18 07 PM" src="https://user-images.githubusercontent.com/83911201/117573709-0f56c200-b10c-11eb-87c0-2688b921d059.png">

**If your problem is that you can't randomize a game:**
If you get a popup saying that there has been an "unhandled exception", please attach the error log as an attached file to this issue.

**Comment by Ajarmar** [comment]
This seems to be a somewhat common problem, so we've been testing a new script-based launcher that probably will be part of the next release - you can try using it now if you want. You can try it by doing the following:

1. [Right click this link and choose "Save link as"](https://raw.githubusercontent.com/Ajarmar/universal-pokemon-randomizer-zx/master/launcher/launcher_MAC.command), and save it in the same folder as `PokeRandoZX.jar`.
2. Open a terminal window in the folder and run the following: `chmod +x launcher_MAC.command` (this will set the file as executable).
3. Double click `launcher_MAC.command` to launch it.

Please tell me if this works for you.

**Comment by contiyeet** [comment]
Thanks for the help ;DD it was really useful and easy to understand but for some reason I could not do the 2nd step but I prolly did it wrong 
<img width="600" alt="Screen Shot 2021-05-10 at 3 49 47 AM" src="https://user-images.githubusercontent.com/83911201/117585014-c66e3000-b142-11eb-84d0-724801c5d31e.png">

**Comment by tom-overton** [comment]
Don't worry, using the Terminal is pretty tricky if you've never used it before. Let me try to help:
- Type `cd ` in the terminal and *don't* press Enter. That's the "c" and "d" key followed by Space
- From your Finder, drag the PokeRandoZX-v4_1_0 folder onto the Terminal. Your terminal should now have a command that looks something like `cd [some path]/PokeRandoZX-v4_1_0`
- *Now* press Enter

Now continue with the steps Ajarmar told you to do, starting with the `chmod +x launcher_MAC.command ` step. The reason it wasn't working for you before is because the Terminal didn't know where to look for launcher_MAC.command; after following my steps, it will now be looking in the right place. Hope that helps!

**Comment by AChexy** [comment]
I've been following along and did what tom-overton suggested but still get an error message.
<img width="567" alt="Screen Shot 2021-06-01 at 1 46 32 AM" src="https://user-images.githubusercontent.com/85151045/120272493-3328a600-c27b-11eb-9795-12019ee91ce8.png">
<img width="520" alt="Screen Shot 2021-06-01 at 1 46 46 AM" src="https://user-images.githubusercontent.com/85151045/120272514-3a4fb400-c27b-11eb-9aa7-bf1f7d70444b.png">

**Comment by tom-overton** [comment]
We have switched to a new launcher in v4.2.0. Please try downloading [the latest randomizer version](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases) and see if it works for you. If you run into problems with the new launcher, go here: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/221
