### ISSUE TITLE
Hello, I just downloaded the randomizer and made sure I got the right thing. However, when I doubleclick on launcher, it just opens up winrar again.

### ISSUE THREAD

**Issue by BDOGG345** [Ajarmar/universal-pokemon-randomizer-zx#187]
First time using Github, and meant to make the title the first message lol

**Comment by tom-overton** [comment]
You have some WinRAR associated with the .jar filetype. Right-click the launcher, click "Open with" and select Java. You should also be able to set Java as the default program for .jar files from there. After doing that, double-clicking on the launcher in the future will correctly launch it with Java.

**Comment by BDOGG345** [comment]
I tried doing that, but Java won't open the file.

**Comment by BDOGG345** [comment]
Well, after changing the default program to Java, it worked! Thanks!

**Comment by marcossxx** [comment]
> Well, after changing the default program to Java, it worked! Thanks!

How did you do that, i have the same problem

**Comment by BDOGG345** [comment]
> > Well, after changing the default program to Java, it worked! Thanks!
> 
> How did you do that, i have the same problem

Just look at what tom-overton said above. I just followed his steps.

**Comment by marcossxx** [comment]
> > > Well, after changing the default program to Java, it worked! Thanks!
> > 
> > 
> > How did you do that, i have the same problem
> 
> Just look at what tom-overton said above. I just followed his steps.

I tried to open it with java but it didnt work.
How can i change the deault program to java?

**Comment by marcossxx** [comment]
> You have some WinRAR associated with the .jar filetype. Right-click the launcher, click "Open with" and select Java. You should also be able to set Java as the default program for .jar files from there. After doing that, double-clicking on the launcher in the future will correctly launch it with Java.

How?

**Comment by BDOGG345** [comment]
For me it was in the section where to choose what program to open with. It allowed me to change the default.

**Comment by marcossxx** [comment]
> For me it was in the section where to choose what program to open with. It allowed me to change the default.

Oh ok thx

**Comment by Ajarmar** [comment]
Closing this again since it seems to have been solved.
