### ISSUE TITLE
Update stats and move generation number is always the same

### ISSUE THREAD

**Issue by kiliwily** [Ajarmar/universal-pokemon-randomizer-zx#19]
When I load settings in which i used the options to update the base stats to generation x and the option to update the moves to generation x, the number of the generation to update is the same for both options even though i saved it with different generations to update. It seems that it is always the generation that i wanted to update the base stats. I used a english Pokemon Emerald Rom.

**Comment by Ajarmar** [comment]
Thanks for pointing this out - fixed in 99ce74f2b6b01b2dc1925fc55319b1fd3d7f58d1, will be included in the next release
