### ISSUE TITLE
[Bug] PKMN Gen #7: USUM: Random Trainer Pokémon: Minior will turn into an Egg and crashes the game

### ISSUE THREAD

**Issue by YuanRenegade** [Ajarmar/universal-pokemon-randomizer-zx#190]
**Describe the bug**
I'm playing Ultrasun randomized on real 3DS Hardware with all Trainer Pokémon shuffled. When encountering a trainer with a Minior it just says "Trainer is sending out Egg" and the game crashes right afterwards. The first trainer it happened in the attached file is "#41 (Ghostwriter Lillianna)":

[216612513045015_Ultrasun.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6470332/216612513045015_Ultrasun.log)

**To Reproduce**
1. Encounter a Trainer with a Minior
2. Trainer will send out an Egg
3. Real 3DS Hardware crashes with an ARM11 Exception Handler
4. See Error

**Expected behavior**
The Trainer should send out either a normal Minior or any Core Form of Minior.

**Screenshots**
![P_20210513_062156](https://user-images.githubusercontent.com/1375104/118077266-11db4500-b3b4-11eb-8ad7-138c1936a1f3.jpg)

**System (please complete the following information):**
 - Operating System: Win 10
 - Java Version: Java 8 Update 271
 - Randomizer Version: PokeRandoZX-v4_1_0

**Comment by tom-overton** [comment]
Thanks, will be fixed in the next release. Until the next release comes out, you can avoid this scenario by avoiding using "Type Themed Trainers" or other similarly type-themed options.
