### ISSUE TITLE
[Bug] PKMN Gen #7: USUM: Mega Forms will devolve into its normal Form when in Team

### ISSUE THREAD

**Issue by YuanRenegade** [Ajarmar/universal-pokemon-randomizer-zx#191]
**Describe the bug**
After catching a Mega Form of any Pokémon it will return to its normal Form when saving the game (and restarting) while having the Mega Form in Team. If the Pokémon was placed in the PC before the Mega Form is still available to use. This one I tested on both: Real 3DS Hardware as well as the latest Citra Build.

**To Reproduce**
1. Put any Mega Form in your Team.
2. Save the Game
3. Restart the Game.
4. See the devolved Mega Form Pokémon.

**Expected behavior**
In for e.g. Pokémon ORAS this issue did not happen - usually the Mega Form should stay as it is regardless if it's in Team or PC.

**System (please complete the following information):**
 - Operating System: Win 10
 - Java Version: Java 8 Update 271
 - Randomizer Version: PokeRandoZX-v4_1_0

**Comment by Ajarmar** [comment]
Did you use this setting?
![image](https://user-images.githubusercontent.com/37733838/118099073-08160980-b3d5-11eb-8551-b68f8f704d62.png)

**Comment by YuanRenegade** [comment]
That could be the reason. I can't confirm it anymore if that was the issue in the Randomized USUM I posted above - but it's working fine when triggered on a fresh Rando. I guess I may have forget to trigger this setting. Sorry for the inconvenience.
