### ISSUE TITLE
The randomizing process works fine with my Ultra Moon file. But when I press "Randomize Save", it continues saving forever. I've seen others with the same problem and I have to use task manager to close the program[Bug]

### ISSUE THREAD

**Issue by Rare7Rex** [Ajarmar/universal-pokemon-randomizer-zx#192]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - Operating System: 
 - Java Version:
 - Randomizer Version: 

**Additional context**

**Comment by Ajarmar** [comment]
Can you try again on the latest randomizer version (v4.2.0) and see if that works? Download here: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases/tag/v4.2.0

**Comment by tom-overton** [comment]
Closing as the OP hasn't responded for three weeks. @Rare7Rex if you're still seeing issues with v4.2.1, feel free to open a new issue.
