### ISSUE TITLE
Add Imposter to list of bad abilities

### ISSUE THREAD

**Issue by halqery** [Ajarmar/universal-pokemon-randomizer-zx#193]
Imposter does not benefit the player in any way and especially in a randomizer race situation it is an essential coinflip whether you survive or not. If it can be added to the list of bad abilities filtered out or at least given a toggle option that would be great. Thank you for all of the work you do on this and regardless of whether this is added I will still use the product!

Side note: Im aware theres already an option to limit pokemon by generations, but if it could be expanded further to limit specific pokemon that would be greatly appreciated as well. Shedinja is not very fun to deal with since you practically have to dedicate a move slot to deal with it in a randomizer race setting. >.<

**Comment by Ajarmar** [comment]
Hi, sorry but we intentionally did not include Imposter in the list of bad abilities and don't plan to change that. I don't agree with the suggestion that Imposter doesn't benefit the player in any way - having an Imposter Pokemon in your team to use as a backup can be very useful.

**Comment by halqery** [comment]
Ok I understand if it’s not able to be added as a bad ability based on personal preference. But the way it stands encountering imposter can easily ruin an experience, is it possible to at least include it as a toggle?
