### ISSUE TITLE
[Contribution Idea] Merge brentspector features

### ISSUE THREAD

**Issue by brentspector** [Ajarmar/universal-pokemon-randomizer-zx#194]
**Is your idea a new setting, a change to an existing setting, or something else? Please describe clearly:** 
This is a major overhaul to the codebase, but would add in almost 100 features that have been added between dabomstew's last commit and the current master branch of https://github.com/brentspector/universal-pokemon-randomizer
The major changes would include mavenizing the project, updating to java 8, adding unit tests, modifying the UI, revamping settings option creation, and merging settings state together so that features are able to be properly saved in a settings string.

**What problem would your contribution solve? Please describe:** 
We each have 2 very large diffs from dabomstew's master, and with features that are well-received by users. Getting both our changes into one branch would enhance the quality of the product we're making.

**Additional context:**
I'd like to discuss how this would happen, what parts you're unsure of, and what timeline would be expected.

**Comment by Ajarmar** [comment]
Hi - thanks for the offer, but to be frank, I don't think it would be worthwhile to try and merge your entire fork into ours. Saying that we each have 2 very large diffs is putting it lightly - we have both diverged immensely from Dabomstew's repo. There would be a ridiculous amount of merge conflicts, and we might also have had different visions for how certain features should be handled which would have to be resolved. It would require a huge amount of effort that I don't think is worth putting in.

That said, if there are any individual features you'd want to contribute to our fork, feel free to open separate `Contribution Idea` issues for those. How does that sound to you?

**Comment by brentspector** [comment]
That's totally fair. I fully agree there would be a ridiculous amount of merge conflicts. That's why it would be done in chunks (like 1 merge for the maven, one merge for java, one merge for logs, etc). I don't plan to switch over to your fork (I plan to continue work on my own fork), so any features I contribute would be things that you would want.
What I want to do is get all the features requested done and then continue on my major refactoring of the code. Unit tests have proven very useful, but cumbersome to maintain due to the way the legacy code is structured. For instance, you might have experienced having to update the `randomize trainers` method signature more than once. That makes every unit test break because that method is a bad design. I plan to make it accept a `TrainersOptions` POJO with each parameter as a field.
However, making those major changes would only diverge us more, so I thought it would be a good time to collaborate. If there is anything in my fork that you're interested in, let me know. Otherwise, feel free to close this issue.

**Comment by Ajarmar** [comment]
Sorry for the delay. I had a look at your repository but I don't think we're interested in any of your changes at the moment, so I'll close the issue. Thanks anyway, and good luck with the development!
