### ISSUE TITLE
[Contribution Idea] Support More Trainer Names for Some Repeated Names

### ISSUE THREAD

**Issue by wwtepicfail** [Ajarmar/universal-pokemon-randomizer-zx#196]
**Is your idea a new setting, a change to an existing setting, or something else? Please describe clearly:** 
My idea changes a small part of how trainer names work. It would give more possible trainer names to some trainers that would normally only show one for a certain trainer type, like "Jimmy" being the only trainer name for every Team Flare admin in _X_/_Y_, for example. Currently, only the trainer names "Grunt" and "Executive" add more possible trainer names for their respective trainers; while the former name is widely used in almost all _Pokémon_ core series games, the latter is only utilized in Generation 2.

**What problem would your contribution solve? Please describe:** 
While this is a mostly minor idea, it would give a little more life to randomized trainers. There are a few more types of trainers with repeating names in the series: "Shadow" (Team Plasma Shadow Triad), "Admin" (Team Rocket "executives" in _FireRed_/_LeafGreen_) and "Goon" (the Biker gang on Three Island in _FireRed_/_LeafGreen_).

**Additional context:**
Dabomstew did this for his "speedchoice" branch of his randomizer in 2019. The commit can be found [here](https://github.com/Dabomstew/UPR-Speedchoice/commit/66cf0bd972e48d7842d5bae1ffd482c3fea0f7a2).

If this were to be implemented, perhaps make it so trainer names are also consistent with a few specific types - this would make for the best experience. For the Shadow Triad, each of the three would have their own name without them being changed between rematches (the one with an Absol ace in _Black 2_/_White 2_ is battled twice in the main game and the others are battled once). Their regular Pokémon rosters are slightly different from one another, so it would not be hard differentiate between the three. For the Generation 2 Team Rocket Executives, the sole female executive should have one name for both battles against her. The male executives could either stay as is or one of them should match Petrel's role in _HeartGold_/_SoulSilver_; I remain unsure as to how it is handled in that generation.

**Comment by tom-overton** [comment]
Sorry for the delay on responding to this. This idea sounds good, so go ahead and give it a shot if you'd like. I'm not sure if the Shadow Triad idea would work, though, since we randomize trainer names/classes *after* randomizing Pokemon, so any way you could tell them apart from their vanilla teams would be obliterated.

**Comment by Ajarmar** [comment]
Closed by #197
