### ISSUE TITLE
[Help] Can't reopen launcher

### ISSUE THREAD

**Issue by X-Crimga** [Ajarmar/universal-pokemon-randomizer-zx#198]
- Operating System: Windows x64bit
 - Randomizer Version: 4.1.0

whenever I go to open the launcher I can get it to open only once and then when I close it I can't open it again without having to extract the launcher again
I'm only having this problem with the one that can do the 3ds games not the gen 1-5 launcher

**Comment by tom-overton** [comment]
We have switched to a new launcher in v4.2.0. Please try downloading [the latest randomizer version](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases) and see if it works for you. If you run into problems with the new launcher, go here: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/221
