### ISSUE TITLE
"the randomizer was not started via the launcher"

### ISSUE THREAD

**Issue by FidelCattsro** [Ajarmar/universal-pokemon-randomizer-zx#199]
I've deleted and reinstalled the randomizer, the menu for the randomizer works but I'm prompt with an alert saying "the randomizer was not started via the launcher and cannot import 3ds games ". l

**Comment by FidelCattsro** [comment]
Also before this the Java files wouldn't open so I installed Java fix. Both the launcher and the PokeRandoZx files are the same size. 
Are they supposed to be?

**Comment by Ajarmar** [comment]
We have switched to a new launcher in v4.2.0. Please try downloading [the latest randomizer version](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases) and see if it works for you. If you run into problems with the new launcher, go here: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/221

**Comment by AidanTheMedic** [comment]
I have this same problem but re-downloaded and it still says the randomizer was not started via the launcher???? How do i fix it
