### ISSUE TITLE
I cant open the launcher

### ISSUE THREAD

**Issue by marcossxx** [Ajarmar/universal-pokemon-randomizer-zx#200]
I cant start the launcher

![16220530419932137719289473595170](https://user-images.githubusercontent.com/84871074/119711097-bfbf0880-be24-11eb-932a-7a2eb787e16e.jpg)

Idk what happened, i have the latest version of java and  64x windows

**Comment by tom-overton** [comment]
We have switched to a new launcher in v4.2.0. Please try downloading [the latest randomizer version](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases) and see if it works for you. If you run into problems with the new launcher, go here: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/221
