### ISSUE TITLE
Feebas evolution in ORAS

### ISSUE THREAD

**Issue by igorzig13** [Ajarmar/universal-pokemon-randomizer-zx#202]
In the "Evolutions" page on the wiki it is said that Feebas' Beauty evolution is completely removed. Therefore, the only way to evolve Feebas in ORAS is by trading/leveling up (with 'change impossible evolutions' option) while holding a Prism Scale. The problem is: It is impossible to obtain a Prism Scale in Omega Ruby or Alpha Sapphire, making the evolution still impossible in those games.

**Comment by tom-overton** [comment]
Thanks, will be fixed in the next release.
