### ISSUE TITLE
[Feature Request] Custom Limit on Wild Pokemon

### ISSUE THREAD

**Issue by suvam7707** [Ajarmar/universal-pokemon-randomizer-zx#203]
Currently the limit available in the randomizer is generation wise, along with relational evolutions from other generations. This excludes a few pokemon in the evolution line. For example, if I have included gen 2 pokemon with gen 1 evolution relatives, I get gloom since Bellossom is gen2, but I don't get oddish or vileplume.

Another requirement is for regional pokedexes, which often contain evolution lines from different generations.

Hence, please consider making a custom "limit pokemon" list, maybe like a checkbox where users can select which pokemon they want to keep in the wild, or maybe read from a text file where users will write the names/national pokedex numbers of required pokemon in a given format, etc.

**Comment by Ajarmar** [comment]
Sorry, but we don't take feature requests.
