### ISSUE TITLE
[Help] 

### ISSUE THREAD

**Issue by VeryMerryMurray** [Ajarmar/universal-pokemon-randomizer-zx#204]

**Comment by DatXFire** [comment]
It seems you edited your post to remove the original content, but if you're still looking that information can be found on the wiki: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Evolutions#change-impossible-evolutions

**Comment by tom-overton** [comment]
Closing since yeah, this is on the wiki
