### ISSUE TITLE
Won't load launcher.jar

### ISSUE THREAD

**Issue by Pixelplayz2215YT** [Ajarmar/universal-pokemon-randomizer-zx#205]
**System (please fill in the following information):**
 - Windows 10
 - Randomizer Version: Latest

**If your problem is that you can't start the randomizer:**
My Log: [launcher-log.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6566575/launcher-log.txt)

**Comment by tom-overton** [comment]
It looks like you have 32-bit Java installed. Please install 64-bit Java instead and then the launcher should work. For more information, check out our [About Java](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java) wiki page.

**Comment by Pixelplayz2215YT** [comment]
Ok, I'll try!

**Comment by tom-overton** [comment]
We have switched to a new launcher in v4.2.0. Please try downloading [the latest randomizer version](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases) and see if it works for you. If you run into problems with the new launcher, go here: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/221
