### ISSUE TITLE
UNIQUE launcher problem

### ISSUE THREAD

**Issue by AChexy** [Ajarmar/universal-pokemon-randomizer-zx#206]
I'm using MacOS and have the latest 64-bit java. When I try to open the launcher, I get an error message.
<img width="659" alt="Screen Shot 2021-06-01 at 1 32 27 AM" src="https://user-images.githubusercontent.com/85151045/120271376-3b7fe180-c279-11eb-8b6e-e08977df90a5.png">
It directs me to a "launcher-log.txt" file it created, but that file just plain doesn't exist. It doesn't create it for me. I really need help, any ideas?

**Comment by AChexy** [comment]
<img width="533" alt="Screen Shot 2021-06-01 at 1 35 36 AM" src="https://user-images.githubusercontent.com/85151045/120271650-b8ab5680-c279-11eb-92f6-099615ea6a13.png">

**Comment by tom-overton** [comment]
We have switched to a new launcher in v4.2.0. Please try downloading [the latest randomizer version](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases) and see if it works for you. If you run into problems with the new launcher, go here: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/221
