### ISSUE TITLE
[Contribution Idea] Up STAB percentage

### ISSUE THREAD

**Issue by vjp-davidGA** [Ajarmar/universal-pokemon-randomizer-zx#207]
**Is your idea a new setting, a change to an existing setting, or something else? Please describe clearly:** 
The STAB percentage is very low, I batteled Kirlia with Fire type moves and no Psychic moves, Arcanine with Grass moves and a very long etc... I think you should up the moves preferring same type.

**Comment by Ajarmar** [comment]
Thanks, but we'll leave the "preferring same type" percentages where they are.
