### ISSUE TITLE
[Help] 

### ISSUE THREAD

**Issue by Oog5568** [Ajarmar/universal-pokemon-randomizer-zx#209]
Hello! so i am not able to run the launcher.jar file, it wont give me aa text file either! please help would be appreciated!

 - Operating System: Windows 10
 - Randomizer Version: Latest Version

**java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)**

it gives me the error "Unable to access jarfile Launcher.jar' when trying to use it through the CMD command line

**Comment by tom-overton** [comment]
We have switched to a new launcher in v4.2.0. Please try downloading [the latest randomizer version](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases) and see if it works for you. If you run into problems with the new launcher, go here: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/221
