### ISSUE TITLE
[Help] Troubleshooting the Launcher: Not Working

### ISSUE THREAD

**Issue by J1mbosl1ce** [Ajarmar/universal-pokemon-randomizer-zx#210]
The launcher wont open. I used WinRar to extract the folder, and when I double click, the black box appears for a split second and then disappears. None of the trouble shooting ideas seem to be helping, although I am by no means an expert so I am well aware this is probably something I am missing.. When running java -Xmx4096M -jar PokeRandoZX.jar in the command line, all it says is "unable to access jarfile". Any help would be greatly appreciated!
 - Operating System: Windows 10 64bit
 - Randomizer Version: v4.1.0

![2021-06-06 (2)](https://user-images.githubusercontent.com/85467674/120950653-360d1600-c715-11eb-8aa5-2b6b10cfe9b0.png)

**Comment by tom-overton** [comment]
We have switched to a new launcher in v4.2.0. Please try downloading [the latest randomizer version](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases) and see if it works for you. If you run into problems with the new launcher, go here: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/221
