### ISSUE TITLE
[Help]  Launcher will not open or run from inception

### ISSUE THREAD

**Issue by Microsoft-dan** [Ajarmar/universal-pokemon-randomizer-zx#211]
I have updated to the latest version of Java 64x, removed environmental variables, can't seem to get the launcher to run. Attached are the requested logs to help assess the issue. 

 - Operating System: Windows 10 Pro Version 2004 
 - Randomizer Version: 4.1.0
[launcher-log.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6611260/launcher-log.txt)
![Untitled](https://user-images.githubusercontent.com/85510934/121071828-123de480-c796-11eb-8cd2-229077d09b77.png)

**Comment by Ajarmar** [comment]
We have switched to a new launcher in v4.2.0. Please try downloading [the latest randomizer version](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases) and see if it works for you. If you run into problems with the new launcher, go here: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/221
