### ISSUE TITLE
[Help] Ultra Moon not randomizing.

### ISSUE THREAD

**Issue by Vhaerun** [Ajarmar/universal-pokemon-randomizer-zx#212]
**Describe your problem clearly:** 
I set up a randomization set for USUM but it doesn't allow it to go through, but the same rando settings work for ORAS. Both dumped from my 3ds

**System (please fill in the following information):**
 - Operating System: Windows 10 Home
 - Randomizer Version: 4.1.0

**If your problem is that you can't randomize a game:**
[error_2021-06-08-08-22-37.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6616360/error_2021-06-08-08-22-37.txt)

**Comment by tom-overton** [comment]
I can randomize Ultra Moon with your seed and settings just fine, as demonstrated here:\
[test.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6619038/test.log)

However, in the ROM Diagnostics section, it looks like the ROMs differ a little bit:
Mine:
```
.code: 1C3F1290
romfs header: FAB54485
a/0/1/1: E8CC46AA
a/0/1/3: 428BEF17
a/0/1/4: 14B009D5
a/0/1/5: AA8FA0AF
a/0/1/7: 7D4D7A45
a/0/3/2: 0FB62104
a/0/4/2: 2D66B8A4
a/0/8/3: 0FB10C58
a/1/5/9: 82A75234
```

Yours:
```
.code: 2AF29FAF
romfs header: 442801B4
a/0/1/1: 0ADC9D84
a/0/1/3: 12C177C1
a/0/1/4: 04881752
a/0/1/5: AA8FA0AF
a/0/1/7: 94AC96AA
a/0/3/2: DB18C861
a/0/4/2: F71DD01D
a/0/8/3: 8C5CD39B
a/1/5/9: 20231901
```

Is this a ROM hack of some kind?

**Comment by tom-overton** [comment]
Closing since it's been a month and the OP hasn't responded
