### ISSUE TITLE
Idea to improve the limit Pokemon setting 

### ISSUE THREAD

**Issue by JackpotJKR** [Ajarmar/universal-pokemon-randomizer-zx#215]
Hi, I had an idea for the ‘limit Pokemon’ setting that currently exists within the randomiser. 

Currently the limit Pokemon option allows you to include/exclude Pokemon based on entire generations so I could randomise say Black2 but choose to exclude all Pokemon from generation 5.

My idea would be to refine this so that users could exclude specific Pokemon as opposed to eliminating entire generations, not exactly sure how this would work as I don’t have much technical knowledge but I envisioned it as maybe a list of all the obtainable Pokemon for that particular game and users could maybe select a tick box on the Pokemon they wanted to exclude from randomisation? 

I’m not sure if this would be feasible but I think people would probably appreciate more control over this option.

Thanks for all your work on this project so far.

**Comment by Ajarmar** [comment]
Sorry, but we don't take feature requests. (As for this specific thing, I've thought about the same thing myself but it comes with the problem of increasing the size of the settings strings significantly)
