### ISSUE TITLE
Where in the code can I change the range for the Similar Strength setting, from 10% to something else

### ISSUE THREAD

**Issue by magmajp** [Ajarmar/universal-pokemon-randomizer-zx#217]
I want to edit the "Similar strength" setting for more variety. Looking at how its done I feel like I should be able to just change the range from 10 % to something else but I can't find where in the code I would need to edit. From there I can probably figure out how to compile it so I get mine working with the different range. I also think this might just be a good addition because you could just add a variable the user can change for the range of it

**System (please fill in the following information):**
 - Operating System: Windows 10
 - Randomizer Version: 4.1.0

**Comment by tom-overton** [comment]
The methods are in AbstractRomHandler.java. They all have "PowerLvlReplacement" in their names. So for example, `pickWildPowerLvlReplacement`, `pickStaticPowerLvlReplacement`, and `pickEvoPowerLvlReplacement` are all methods that use 10%. Hope that helps!
