### ISSUE TITLE
[Help] 

### ISSUE THREAD

**Issue by glum-torrent** [Ajarmar/universal-pokemon-randomizer-zx#218]
**Describe your problem clearly:** 
When I extract the file after downloading it, the file changes to just "launcher" instead of "laucher.jar" I would like some assistance.
**System (please fill in the following information):**
 - Operating System: 
 - Randomizer Version: 

**If your problem is that you can't start the randomizer:**
- If there is a `launcher-log.txt` created when you try to start the launcher, please attach it to this issue as an attached file.
- Open a terminal window (if you're not sure how, google your operating system + "terminal window"). Type in `java -version` and press Enter. Please include a screenshot of what you get:

**If your problem is that you can't randomize a game:**
If you get a popup saying that there has been an "unhandled exception", please attach the error log as an attached file to this issue.

**Comment by tom-overton** [comment]
We have switched to a new launcher in v4.2.0. Please try downloading [the latest randomizer version](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases) and see if it works for you. If you run into problems with the new launcher, go here: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/221
