### ISSUE TITLE
[Help] The launcher does not work

### ISSUE THREAD

**Issue by regasti** [Ajarmar/universal-pokemon-randomizer-zx#222]
When I try to open the launcher bat file a command prompt flashes and nothing happens, I don't have an antivirus on and I've tried disabling firewall.

**System:**
 - Operating System: Windows 10 Pro
 - Randomizer Version: 4.2.0

**Comment by Ajarmar** [comment]
Please take a look at this issue and see if your problem can be solved by the information already available there: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/221

If not, please add a comment on that issue with your problem and we'll troubleshoot it further.
