### ISSUE TITLE
Stuck on "saving" [Bug] 

### ISSUE THREAD

**Issue by YahaTheMajin** [Ajarmar/universal-pokemon-randomizer-zx#223]
**Randomiser saves forever**
I tried to randomize a french version of platinum but it always gets stuck at the save icon, I've tried with many different versions of the rom in case it was the roms fault,all had the same issue.
Im using the latest version of the randomiser

System:
 - Operating System: 8.1
 - Java Version: over 8
 - Randomizer Version: Latest version as of june 17th

**Comment by tom-overton** [comment]
Can you please verify you're using Version 4.2.0? Foreign versions of Pokemon Platinum had infinite saving issues when performing shop randomization in 4.1.0.

Additionally, can you provide the settings that you're attempting to use? You can go to Settings -> Get/Load Settings String and paste what appears there in here. On my end, French Platinum seems to work fine, but I have no clue if I'm doing the same thing you're trying to do.

**Comment by YahaTheMajin** [comment]
> Can you please verify you're using Version 4.2.0? Foreign versions of Pokemon Platinum had infinite saving issues when performing shop randomization in 4.1.0.
> 
> Additionally, can you provide the settings that you're attempting to use? You can go to Settings -> Get/Load Settings String and paste what appears there in here. On my end, French Platinum seems to work fine, but I have no clue if I'm doing the same thing you're trying to do.

I was indeed using 4.1.0,I hadn't noticed that there was a newer version released. I just tried with 4.2.0 and it took a bit more time than usual,but it seems like it did work. Though i noticed that the english version has more options in this version
Thanks for the reply

**Comment by tom-overton** [comment]
I'm glad you got it working with 4.2.0! As for the English version having more options, it's just the reality of some of the work we do. Some of the patches we need to write to enable certain functionality (like roamer randomization or music fixes) are very tricky, so we really only have time to add support for one version, which is the English version. Other versions should still *work* though, just with reduced functionality. The infinite saving bug in non-English Platinum in v4.1.0 was a miss on our part, and I'm glad that we got it all fixed and working once you updated.
