### ISSUE TITLE
[Help] 

### ISSUE THREAD

**Issue by Carson-wildcat** [Ajarmar/universal-pokemon-randomizer-zx#226]
can someone please help me

I am trying to randomize my Pokémon sun and after struggling to make space for the game I realize the universal randomizer won't open. I get the windows security message and when I say run anyways I just get like a millisecond pop up of the randomizer before it closes. I have no idea how to keep it open and am not sure of to shut off the windows security settings for a time (i think this might fix the problem). If anyone is familiar with this problem or just the universal randomizer program please help me out I have spent almost 4 hours today getting Luma and godmode and downloading my game places I just need  this to work thanks.

Also I learned this method from This video
https://www.youtube.com/watch?v=vN7l4gE0qgI 
so I am trying to open it that way if that described my problem more

**Comment by tom-overton** [comment]
Please use issue #221 for troubleshooting the launcher instead of making a new issue, thanks!
