### ISSUE TITLE
[Bug] The launcher won't start the randomizer program automatically

### ISSUE THREAD

**Issue by Randoguy123** [Ajarmar/universal-pokemon-randomizer-zx#227]
**Describe the bug**
By clicking the launcher i get the config file however the randomizer won't start up automatically. If press the randomizer program, i get the popup message saying "Since you did not use the launcher, your games won't load into the randomizer" I close the message and everything seems fine. 

I even started the launcher as an admin.

**System (please complete the following information):**
 - Operating System: Windows 10 Home 20H2 Build: 19042.928
 - Java Version: Version 8 Update 291
 - Randomizer Version: v4.2.0

**Comment by tom-overton** [comment]
Please use issue #221 for troubleshooting the launcher instead of making a new issue, thanks!
