### ISSUE TITLE
[Bug] UPR ZX 4.2.0 doesn't get started

### ISSUE THREAD

**Issue by Thyden** [Ajarmar/universal-pokemon-randomizer-zx#229]
It's just that, nothing else.

**To Reproduce**
1. Clicking on "launcher_WINDOWS.bat"
**Expected behavior**
Doesn't start up.

**System:**
 - Operating System: Windows 10 Home 20H2 19042.1052
 - Java Version: 1.8
 - Randomizer Version: 4.2.0

**Additional context**
I already restarted the PC and stuff, and If execute it as administrator it won't start up either. Nothing more else to say for now.

**Comment by tom-overton** [comment]
Please use issue #221 for troubleshooting the launcher instead of making a new issue, thanks!
