### ISSUE TITLE
[Help] 

### ISSUE THREAD

**Issue by EHeroNerd** [Ajarmar/universal-pokemon-randomizer-zx#230]
I cannot open the launcher. When I click on it nothing happens. I have windows not mac so the fix I saw doesn't work for me. I downloaded the randomizer today so I can only assume it is the correct and most recent version.

 - Operating System: Windows 10
 - Randomizer Version: 4.2.0

**Comment by AxelElric8** [comment]
I have the same issue. I just can open the .jar to randomize, not the .bat

**Comment by EHeroNerd** [comment]
When I do it that way it doesn't allow me to actually randomize anything.

**Comment by tom-overton** [comment]
Please download [v4.2.1](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases/tag/v4.2.1). If that doesn't solve your issues, consult #221 for further help.
