### ISSUE TITLE
Launcher_Windows.bat doesn't do anything

### ISSUE THREAD

**Issue by pelador** [Ajarmar/universal-pokemon-randomizer-zx#231]
I have extracted the contents of the zipped folder and followed the instructions to launch the program using Launcher_Windows.bat but this seems to do nothing. I can open the .jar file just fine but I get a message telling me that 3DS games won't work unless I use the Windows launcher.

**Comment by bigsrgh** [comment]
same here did you find a fix for this?

**Comment by pelador** [comment]
Yeah I just needed the 64 bit Java installed and it was fine. Sent from Mail for Windows 10 From: bigsrghSent: 03 July 2021 6:24 AMTo: Ajarmar/universal-pokemon-randomizer-zxCc: pelador; AuthorSubject: Re: [Ajarmar/universal-pokemon-randomizer-zx] Launcher_Windows.bat doesn't do anything (#231) same here did you find a fix for this?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by tom-overton** [comment]
Please download [v4.2.1](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases/tag/v4.2.1). If that doesn't solve your issues, consult #221 for further help.
