### ISSUE TITLE
[Bug] launcher_WINDOWS.bat not opening

### ISSUE THREAD

**Issue by PhatherJoseph** [Ajarmar/universal-pokemon-randomizer-zx#232]
**Describe the bug**
On windows I would go to the specified launcher and it would pop up with the normal "Unknown Publisher" thing so I clicked "more info" then "run anyway" it didn't run at first so I thought click it again and something popped up but only for a split second then it shut down and it won't run.

**To Reproduce**
1. Go to 'launcher_WINDOWS'
2. Click on 'launcher_WINDOWS'
4. Doesn't launch

**Expected behavior**
I just expected the randomizer to open

**Screenshots**
None

**System (please complete the following information):**
 - Operating System: Windows
 - Java Version: Version 8 Update 291
 - Randomizer Version: 4.2.0.

**Additional context**
Pops up for a split second then just goes away and now downloading this has seemed to screw with the universal randomizer I was using.

**Comment by tom-overton** [comment]
Please download [v4.2.1](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases/tag/v4.2.1). If that doesn't solve your issues, consult #221 for further help.
