### ISSUE TITLE
[Bug]  Black 2R crashing when playing on a real DS but not vanilla

### ISSUE THREAD

**Issue by samkurashiki** [Ajarmar/universal-pokemon-randomizer-zx#233]
**Describe the bug**
Black Screen crashes in menus in black 2 
**To Reproduce**
1. Open a randomized rom on Twilight menu++
2. Played up until I got the starter
3. clicked summery on starter OR after healing a pokemon with an item
4. Black screen crash.

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - Operating System: Arch (arco) linux 
 - Java Version: 16.0.1
 - Randomizer Version: 4.20 and also tried 4.10

**Additional context**
Works fine with a vanilla rom on Twilight Menu++. Tried multiple versions of the randomizer software, redumped my copy of Black 2, didn't have issues with the other games I checked (Platinum and white 1).

**Comment by tom-overton** [comment]
This has been discussed before in #63, the long and the short of it is that we delete the DSi binaries so Twilight Menu breaks if you try to boot the game in DSi mode. According to [this comment](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/63#issuecomment-729349097), you can boot the game in DS mode in Twilight Menu and it will work fine? I don't use Twilight Menu so I can't say for certain though.
