### ISSUE TITLE
everytime I try to to run the Launcher.windows it pops up for a split second and then dissapears. [Bug] 

### ISSUE THREAD

**Issue by mason-a5** [Ajarmar/universal-pokemon-randomizer-zx#234]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - Operating System: 
 - Java Version:
 - Randomizer Version: 

**Additional context**

**Comment by tom-overton** [comment]
Please download [v4.2.1](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases/tag/v4.2.1). If that doesn't solve your issues, consult #221 for further help.
