### ISSUE TITLE
[Contribution Idea] Sw/Sh or Lets Go Support?

### ISSUE THREAD

**Issue by GamingInfinite** [Ajarmar/universal-pokemon-randomizer-zx#235]
I apologize if this has been discussed previously but I just have to put this out there.  Obviously implementing stuff and testing it on the switch is dangerous, for ban reasons, so if you need someone to test any switch implementation ideas contributors may have for this project dm me at GamingInfinite | ✓ᵛᵉʳᶦᶠᶦᵉᵈ#6947 on discord.

But for the most part, tools like PkNX have at the very least barebones randomization options, and yuzu has a way to dump the switch games, and pkNX automatically outputs the edited romfs files during editing (which while not necessary, just randomizing in the background, using minimal resources while the person is still browsing options could be neat).  All I'm saying is the building blocks are there, and I'm pretty sure, at least to an extent, this is something that a lot of people want.  And again I'm open for testing stuff for switch since while my switch is banned online I can still do mod testing.

P.S.  When I say pkNX has barebones rando capability, I mean barebones.  Like actually while pokemon abilities and types and stats and the like get randomized properly, trying to do anything like give them a expanded learnset makes it where the learnset values get moved all over the place, which is something to report to them in there own issue.

**Comment by Ajarmar** [comment]
We don't have any plans for this at the moment, and if we do implement it we have the capability to test stuff ourselves. Thanks anyway!
