### ISSUE TITLE
[Help]  not able to launch

### ISSUE THREAD

**Issue by xXCasualKingXx** [Ajarmar/universal-pokemon-randomizer-zx#236]
I am running the most recent one 4.2.0 and I am clicking on the launch for Windows and it just pulls up the command and then closes completely doing nothing. what am I missing or not using properly? Thanks.

**Comment by PhatherJoseph** [comment]
there are about 3 other posts on this same issue and we're still waiting on a response

**Comment by tom-overton** [comment]
Please download [v4.2.1](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases/tag/v4.2.1). If that doesn't solve your issues, consult #221 for further help.
