### ISSUE TITLE
[Help] when i click "randomize (save)" and then "layeredFS" or "CXI" it appears to me 

### ISSUE THREAD

**Issue by portadicasa2623** [Ajarmar/universal-pokemon-randomizer-zx#238]
when i click "randomize (save)" and then "layeredFS" or "CXI" it appears to me unhandled exception
[error_2021-07-04-17-27-00.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6760138/error_2021-07-04-17-27-00.txt)

**Comment by tom-overton** [comment]
The same seed/settings combo works fine for me:
[test.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6766177/test.log)

Looking at your ROM Diagnostics section, I see some differences though:
Yours:
```
.code: 3AE5CEE2
romfs header: 2B6A334F
a/0/1/3: 85D26B50
a/0/1/4: 6161D68F
a/0/8/2: D5CA23D0
a/1/0/5: 9DB0D4BD
a/1/0/6: 460228F1
a/1/5/5: AD93AB53

```

Mine:
```
.code: DE47EF73
romfs header: EE3DB972
a/0/1/3: 4DA9DF72
a/0/1/4: 4732336F
a/0/8/2: C25E1A15
a/1/0/5: 51FC0767
a/1/0/6: 2F5EFBF1
a/1/5/5: 7E3092FF
```

Is this a ROM hack?

**Comment by portadicasa2623** [comment]
yes

Il giorno lun 5 lug 2021 alle ore 22:52 Tom Overton <
***@***.***> ha scritto:

**Comment by tom-overton** [comment]
Sorry, but we don't officially support ROM hacks. Unofficially, I can say that whatever ROM hack this is, it's crashing because the wild Pokemon data is not correctly formatted; you'd have to take it up with the author of the hack to get that fixed.
