### ISSUE TITLE
[Bug] Windows.bat will open with a terminal error now

### ISSUE THREAD

**Issue by PhatherJoseph** [Ajarmar/universal-pokemon-randomizer-zx#239]
**Describe the bug**
It now opens up a terminal but still with an error

**To Reproduce**
1. click on: 'Launcher_WINDOWS.bat' 

**Expected behavior**
To actually open 

**Screenshots**
![Error](https://user-images.githubusercontent.com/86450220/124673458-7a0f4a00-de7e-11eb-9a90-05f56fa8850c.PNG)

**System (please complete the following information):**
 - Operating System: Windows
 - Java Version:Version 8 update 291
 - Randomizer Version: 4.2.11

**Additional context**
none

**Comment by tom-overton** [comment]
This is not a bug with the randomizer. The error indicates some issue with your Java installation. Please uninstall and reinstall Java and see if that fixes it. Additionally, please don't open bugs related to launcher issues: use #221 instead.
