### ISSUE TITLE
Alternate forms not being easily caught with setting

### ISSUE THREAD

**Issue by WhySoMuchChaos** [Ajarmar/universal-pokemon-randomizer-zx#24]
I decided to randomize Pokémon Alpha Sapphire and set it to level 4 easy catch cuz I'm just doing a casual run. When I ran into a kyurem white I found that it was extremely hard to catch even in the red and asleep (lvl 10 as well), I had some trouble catching a mega alakazam as well. Compared to every other pokemon I've caught including some legendaries that are not alternate forms it seems as though the easy catch modifier does not work on alternate forms

**Comment by Ajarmar** [comment]
Yep, turns out they didn't work. Thanks for pointing this out. Fixed in 6346435006bd2e865742a29d9c26e2344b2db366, will be included in the next release
