### ISSUE TITLE
[Contribution Idea] Add Randomized Trainer Names/Classes Alongside Vanilla Names in Log Files

### ISSUE THREAD

**Issue by wwtepicfail** [Ajarmar/universal-pokemon-randomizer-zx#240]
**Is your idea a new setting, a change to an existing setting, or something else? Please describe clearly:** 
This slightly changes how trainer names/classes display in a log file. I am pretty sure it would work similarly to how trainers were logged before when they were randomized, only that the original names are still kept. If unrandomized, only the original names remain.

My idea changes the bolded portion:

> #246 (**Leader Roark**) - Magnemite@Expert Belt Lv13, Porygon@Lax Incense Lv13, Mawile@Custap Berry Lv15

To something like this:
> #246 (**Leader Roark -> Designer Marcellus**) - Magnemite@Expert Belt Lv13, Porygon@Lax Incense Lv13, Mawile@Custap Berry Lv15

**What problem would your contribution solve? Please describe:** 
This is mostly just for consistency. It is hard to know if a trainer name list actually works unless you boot up a randomized seed, which might take some time if you do not already have a save file. Since the Pokémon trades have the Pokémon's original nicknames on the left side and the new nicknames on the right side when randomizing their names, why not apply it to trainers?

**Additional context:**
N/A

**Comment by Ajarmar** [comment]
Sure, I can see the value of having this. I was a bit worried about the line lengths in the log file getting too long (especially for trainers with many Pokemon and/or with held items added), but I think the positives outweigh the negatives here. Feel free to go ahead with implementing this.

**Comment by wwtepicfail** [comment]
Decided to cancel my contribution idea, unless someone else is willing to try it out. I realized this might be too much for me.
