### ISSUE TITLE
'java' is not recognized as an internal or external command, operable program or batch file. Press any key to exit...[Help] 

### ISSUE THREAD

**Issue by xxxdrewwerdxx** [Ajarmar/universal-pokemon-randomizer-zx#241]
I downloaded the zip, unzipped it to a folder, and it said this when i booted windows.bat. I am using windows. 
the message was: 

'java' is not recognized as an internal or external command,
operable program or batch file.
Press any key to exit...

What do I do? Thx

**Comment by tom-overton** [comment]
Do you have Java installed? You need to have 64-bit Java 8 or higher installed as per the instructions on our [Java wiki page](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java). If you *do* have Java installed, then there might be something wrong with your installation if Windows can't find it; try reinstalling it.

**Comment by Johnm772** [comment]
i had java already installed and tried reinstalling it and it still isnt working im using the windows one and it keeps coming up with the same thing:
'java' is not reconized as an internal or external command,
operable program or batch file.
press any key to exit....

have anything else that might fix it

**Comment by tom-overton** [comment]
Try following along with [this post](https://stackoverflow.com/a/26438374). Please make sure to read the "Notes on Step 8" *very* carefully.

Also gonna close this one and ask that you move further launcher issues to #221, since we don't want any launcher issues other than that one.
