### ISSUE TITLE
Fatal exception+No Java Virtual Machine?

### ISSUE THREAD

**Issue by Clayboy692006** [Ajarmar/universal-pokemon-randomizer-zx#242]
This is what I get when I run the launcher on windows.  Any help?
![error](https://user-images.githubusercontent.com/87148758/124978664-10b74480-e000-11eb-8748-31905d0e9b29.JPG)

Invalid maximum heap size: -Xmx4096M
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Press any key to exit...

**Comment by tom-overton** [comment]
You have 32-bit Java installed; you need 64-bit Java installed. For more info, see the [Java section](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java) of our wiki.

Also, for future launcher-related issues, please don't open a new issue. Use #221 like the README asks you to do.
