### ISSUE TITLE
Problem Opening Launcher[Bug] 

### ISSUE THREAD

**Issue by EHeroNerd** [Ajarmar/universal-pokemon-randomizer-zx#243]
**Describe the bug**
When I click on the windows launcher it does not open and opens a window that reads the following:
Invalid maximum heap size: -Xmx4096M
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Press any key to exit...

**To Reproduce**
1. Click on Windows Launcher
2. See Window
3. Close Window as it prompts and it doesn't seem like you can do anthing else

**Expected behavior**
I expect it to open the randomizer and let me randomize

**System (please complete the following information):**
 - Operating System: Windows
 - Java Version: I don't know exactly but I did just update it a few days ago
 - Randomizer Version: 4.2.1

**Comment by tom-overton** [comment]
You have 32-bit Java installed; you need 64-bit Java installed. For more info, see the [Java section](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java) of our wiki.

Also, for future launcher-related issues, please don't open a new issue. Use #221 like the README asks you to do.
