### ISSUE TITLE
[Help] Unhandled exception trying to save gen 4 ROMs

### ISSUE THREAD

**Issue by Mizzraim** [Ajarmar/universal-pokemon-randomizer-zx#245]
I'm getting "There was an unhandled exception trying to save your ROM to disk" error while saving the gen 4 games (gen 2 remakes included).
I'm only trying to change impossible evolutions, nothing else.
The randomizer works normally on gen 3 and gen 5 games on my PC. I also tried SoulSilver, Diamond and Pearl, same issue.

 - Operating System: Windows 7
 - Randomizer Version: 4.2.1

[error_2021-07-14-08-49-01.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6817980/error_2021-07-14-08-49-01.txt)

[error_2021-07-14-20-41-34.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6817981/error_2021-07-14-20-41-34.txt)

**Comment by tom-overton** [comment]
I can randomize the same seed + settings combination just fine:
[test.nds.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6819487/test.nds.log)

Looking at the ROM Diagnostics, your ROM looks different from mine:
Yours:
```
arm9: 5D39375C
overlay9_1: 2166BEFE
```

Mine:
```
arm9: F1CCC042
overlay9_1: 3ACD000C
```

Is this a ROM hack of some sort? If it's not, then I think these might be corrupted or mislabeled in some way. I would try a different ROM and see if that works.

**Comment by Mizzraim** [comment]
The working ROMs I've tested are from the same source, checked the beginning and it seemed normal so I doubt it's a hack. Might be corrupted in some way then, guess I'll search another one somewhere.

**Comment by tom-overton** [comment]
@Mizzraim Did using a different ROM fix your issue?

**Comment by tom-overton** [comment]
I'm just going to assume the answer to my previous question is "yes" and close this out, but please let me know if that's not the case.
