### ISSUE TITLE
Pokemon Omega Ruby Randomizer Alternate form issue

### ISSUE THREAD

**Issue by RevanXVIV** [Ajarmar/universal-pokemon-randomizer-zx#25]
I don't know if this is being worked on but I'm doing a shiny living dex using the current version of this randomizer on Omega Ruby. Everything works fine except for one somewhat annoying bug, I found and caught a shiny primal kyogre under Slateport using the old rod, BUT, when I checked it out it reverted to it's original base form even though I disabled form reversion. Is this only for Primals or is this a bug? Either way figured I'd report it and let you guys know just in case :)

**Comment by tom-overton** [comment]
If you created a log file during randomization, can you upload it here? I'd like to recreate your seed as closely as possible to test this.

**Comment by tom-overton** [comment]
Actually, never mind, I see the issue. I'll see what I can do

**Comment by RevanXVIV** [comment]
Ok so I made a new save file and deleted the old one, so my question is does reversion disable actually work for ORAS? It worked for Mega Banette on the new file I made, but I have yet to find a primal form. If it's something that'll be in a future update, I'll just hold off continuing any new files. Also when trying to catch the shiny primal kyogre, even though I used the max cap rate settings it wouldn't stay in the ball. Just figured I'd let you know some forms may not be affected by the cap rate increase.

**Comment by tom-overton** [comment]
My understanding is that it works for everything except Primal Reversions, but I will make sure to test everything and make sure this is fixed in the next update. As for your catch rate question, that is indeed a bug. It was discussed in #24 and will *also* be fixed in the next update.

**Comment by RevanXVIV** [comment]
Ok perfect! Then I'll just do a normal shiny badge quest for now, and when the next update comes around I'll do living shiny dex. Thanks for the help! Also can I request a feature for the gen 4 and up games? Would it be possible to add the option to remove all shiny locks? Or is that a bit too much?

**Comment by tom-overton** [comment]
Sorry, but we don't take feature requests. There are only two active developers on this fork of the randomizer, and we generally work on things that we want to work on, taking into account how much effort it would take to complete, if it makes sense to include in the randomizer, if other people want it, etc.
