### ISSUE TITLE
[Help] how to fix application that require java runtime environment 1.6.0 in  universal-pokemon-randomizer-zx

### ISSUE THREAD

**Issue by anubio** [Ajarmar/universal-pokemon-randomizer-zx#250]
**Describe your problem clearly:** 

**System (please fill in the following information):**
 - Operating System: 
 - Randomizer Version: 

**If your problem is that you can't randomize a game:**
If you get a popup saying that there has been an "unhandled exception", please attach the error log as an attached file to this issue.

**Comment by tom-overton** [comment]
Install 64-bit Java 8 or above as per [the instructions on our Java wiki](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java)
