### ISSUE TITLE
[Bug] This version won't let use spanish roms

### ISSUE THREAD

**Issue by Devil-RS** [Ajarmar/universal-pokemon-randomizer-zx#251]
**Describe the bug**
I have tried using spanish roms for White 1 and HG and it crashes when saving the rom, whereas in older versions those same roms work fine.

**To Reproduce**
1. Upload spanish rom
2. Click on 'Randomize (save)'
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/87676896/126237082-f667f602-1332-4ec3-a3b0-6463d31417fe.png)

**System (please complete the following information):**
 - Operating System: Windows
 - Java Version: 8 update 261
 - Randomizer Version: 4.2.1

**Comment by tom-overton** [comment]
For your White issue, it will be fixed in the next release. Thanks for your report! For now, you can use v4.2.0 to prevent the crash.

As for HG, I cannot replicate a crash at all on my end.
