### ISSUE TITLE
[Bug]  Issue exporting randomized

### ISSUE THREAD

**Issue by lilgoodee** [Ajarmar/universal-pokemon-randomizer-zx#253]
**Describe the bug**
When trying to export the randomized save it throws an error and fails to randomize.

**To Reproduce**
Open the Omega Ruby save, set up the randomized options and then hit randomize.

**Expected behavior**
Program should create a randomized file with the new variables.

**Error list**
[error_2021-07-23-01-30-03.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6866927/error_2021-07-23-01-30-03.txt)

**System (please complete the following information):**
 - Operating System:  Windows 10 enterprise
 - Java Version: 64 bit
 - Randomizer Version:  4.2.1 , issue persists on 4.1 as well

**Additional context**

**Comment by tom-overton** [comment]
Using the same seed/settings combo worked fine for me:
[test.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6871655/test.log)

Looking at the ROM Diagnostics section of the logs, it looks like there are differences between your ROM and mine. Is this a ROM hack?

Yours:
```
.code: 69AFBA39
romfs header: 578622F5
DllBattle.cro: 91EE2FAE
DllField.cro: 10D03AFF
DllPoke3Select.cro: 38E17029
a/0/1/3: ADC65C2B
a/0/2/9: 38FBCB9E
a/0/3/6: F2F2FCFE
a/0/3/8: 6FFEECA7
a/0/7/1: 056B6FC1
a/0/7/2: 7FDE0257
a/0/7/3: 4622B34D
a/0/7/4: 335BC2CD
a/0/7/5: 85D8C6C8
a/0/7/6: 0CE87969
a/0/7/7: FA9DAD74
a/0/7/8: 14AA39A1
a/0/9/1: 2AA511AA
a/1/8/1: 5F52E7E2
a/1/8/9: D17DC884
a/1/9/1: C03B6E88
a/1/9/2: 7DC3D6D4
a/1/9/3: 43D2B7D0
a/1/9/5: D84EB635
```

Mine:
```
.code: 575A1629
romfs header: D39632B9
DllBattle.cro: E78107DF
DllField.cro: F929EB93
DllPoke3Select.cro: F4A1F22E
DllShinkaDemo.cro: 53AC2B89
a/0/1/3: BD3DF991
a/0/2/9: 3F312B82
a/0/3/6: F2F2FCFE
a/0/3/8: 9C55C332
a/0/7/1: 3012FCBF
a/0/7/2: 75638696
a/0/7/3: 0EF80A2A
a/0/7/4: 63BC908F
a/0/7/5: 79E211CF
a/0/7/6: 631C8EAA
a/0/7/7: 3467A16A
a/0/7/8: 29518B34
a/0/9/1: 2AA511AA
a/1/8/1: 0C1F0B7B
a/1/8/9: D17DC884
a/1/9/1: C03B6E88
a/1/9/2: 21DCE891
a/1/9/3: 43D2B7D0
a/1/9/5: ABB02044
a/1/9/7: 06267B89
```

**Comment by lilgoodee** [comment]
It is a omega ruby rom that had been randomized once already and I think
that was my issue.downloading a fresh rom let it work. Thanks for the
reply.

**Comment by tom-overton** [comment]
Glad you got it working! Yeah, make sure to use a clean ROM every time you want to randomize the game.
