### ISSUE TITLE
[Bug] Race Premade Files

### ISSUE THREAD

**Issue by ScrubZeroSkill** [Ajarmar/universal-pokemon-randomizer-zx#255]
Created a race premade file to play with friends using chosen Mega Pokemon as starters (ORAS) The 2 players downloading the file got different check codes and the starters were vanilla. The creator of the file had the chosen Mega starters. Went back to non Mega starters and the ROMs/patch files lined up properly.
Using 4.2.1

**Comment by tom-overton** [comment]
Thanks for the report; this will be fixed in the next release. Until then, note that all alternate formes will demonstrate this same issue. This has seemingly been broken forever so it's just something to look out for until the next release.

**Comment by ScrubZeroSkill** [comment]
Awesome, appreciate the response. Makes sense for it to apply to all alt forms, sorry if it's been reported multiple times.
