### ISSUE TITLE
it teel me that i cannot use a game because i need a version but i already using [Help] 

### ISSUE THREAD

**Issue by pokepini** [Ajarmar/universal-pokemon-randomizer-zx#256]
**Describe your problem clearly:** 

**System (please fill in the following information):**
 - Operating System: 
 - Randomizer Version: 

**If your problem is that you can't randomize a game:**
If you get a popup saying that there has been an "unhandled exception", please attach the error log as an attached file to this issue.

**Comment by tom-overton** [comment]
Just going to close this one as I responded in #257 instead
