### ISSUE TITLE
Unhandled exception trying to load ROM

### ISSUE THREAD

**Issue by Humdrumbun** [Ajarmar/universal-pokemon-randomizer-zx#261]
When I try to open my Rom it says that "there was an unhandled exception trying to load you ROM".

Expected behaviour: The ROM should be able to open
[error_2021-08-04-14-23-48.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6935452/error_2021-08-04-14-23-48.txt)
this is the log file it gave me
I am using windows 10 and randomizer version 4.2.1

**Comment by tom-overton** [comment]
This was fixed way back in v4.0.1, and we're on v4.2.1 now. Grab v4.2.1 from [here](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases) and your problem will go away.
