### ISSUE TITLE
Is there an option to make regular trainers pokemon fully randomized but Gym Leaders be type themed?

### ISSUE THREAD

**Issue by Metatayte** [Ajarmar/universal-pokemon-randomizer-zx#262]
Hey! I was wondering if there was an option to have gym leaders be randomly type themed (Brock => Rock, etc.) and have regular trainers be completely randomized. I was under the impression that "Type Themed" would accomplish this based on its description that 'Trainers in each gym, will all be given the same (random) type". However, I just randomized a Black version and two gyms in its clear that the route trainers are also type themed (a single trainer has 3 dragons, another has 4 fighting types, etc.) Did I misunderstand the functionality or is it just missing? If missing, I could be motivated to add the functionality myself. Let me know!

PS: Great tool. Love the effort that has gone into it. Ive been using it for years. 

**System (please fill in the following information):**
 - Operating System: Windows 10
 - Randomizer Version: 4.2.1

**Comment by Metatayte** [comment]
Looks like an 'if' statement around [line 1870 of AbstractRomHandler](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/blob/19043b142031ad4cc707c4351708267c72eae341/src/com/dabomstew/pkrandom/romhandlers/AbstractRomHandler.java#L1870) which blocks the randomization of 'unassigned' trainers until a check is made to confirm a request for type theming those unassigned trainers has been made (likely check-boxes similar to the 'Additional Pokemon for...' & 'Add Held Items to...' ones). Agreed?

**Comment by tom-overton** [comment]
There is no option for this; *all* trainers become type-themed with this setting. It's been requested before (see #32) but there are multiple trainers classes in the original game that are type-themed without being in a gym, like swimmers or bug catchers, so it doesn't make perfect sense to change it. The part of the code you highlighted is where trainers that are *not* in gyms and the E4 get their types assigned, so I guess from a *theoretical* perspective you could do non-type themed randomization there. But it would probably take a refactor of the trainer code to make it work, and I'm not sure it's really worth it given that plenty of trainers are already type-themed in the original game outside of gyms.

**Comment by Metatayte** [comment]
I made it myself:

https://github.com/Metatayte/universal-pokemon-randomizer-zx/tree/OptionalThemedRegularTrainers

Its a single check box, but it would pretty easy to make it highly customizable (one for gym leaders, elite four, etc.). Works in preliminary testing. If you'd like, I'd be happy to make a pull request, I know there are people who love the Foe Randomization and would appreciate this functionality.
