### ISSUE TITLE
Randomizer fails to randomize trainer names

### ISSUE THREAD

**Issue by game-sampler** [Ajarmar/universal-pokemon-randomizer-zx#263]
**Describe the bug**
The randomizer fails to randomize trainer names and classes.

**To Reproduce**
1. Install the randomizer as normal by unzipping the file into a folder on your computer.
2. Open the randomizer with the launcher and load a game.
3. Select only the options "Randomized", "Randomize Trainer Names", and "Randomize Trainer Classes" under Foe Pokemon, not selecting anything else.
4. Save the newly randomized game into a folder of your choice.
5. Check the log file to see that the names remain the same as a normal ROM.

**Expected behavior**
The ROM was expected to have randomized names but does not as shown by the log file

**Screenshots**
Note that the default custom name list is used across all screenshots, and all have the same options selected.
![bugreport](https://user-images.githubusercontent.com/88594395/128610552-0898e850-4c1b-4d69-a38c-942d0966420e.png)
![bugreport2](https://user-images.githubusercontent.com/88594395/128610553-0aaee1f9-0fee-4ac2-930b-361679e4c1b2.png)
![bugreport3](https://user-images.githubusercontent.com/88594395/128610554-65bf5423-4aad-4f81-aabc-4d38be4bf03c.png)
![bugreport4](https://user-images.githubusercontent.com/88594395/128610555-1471f600-4b00-476a-af0b-88afd5f9d9fb.png)
![bugreport5](https://user-images.githubusercontent.com/88594395/128610550-b2887bc7-658a-4ecf-9e3d-d9566acda950.png)

**System (please complete the following information):**
 - Operating System: Windows 10
 - Java Version: 1.8.0_281
 - Randomizer Version:  4.2.1

**Additional context**
The issue has occurred across Pokemon Platinum, Ultra Moon, and Black 2. It occurs regardless of the contents of the custom name list, and additionally occurs on a fresh install.

**Comment by tom-overton** [comment]
This isn't a bug; the names are actually randomized in the ROM, but are left unchanged in the log. This is a deliberate change from older versions of the randomizer. Keeping the trainers unchanged in the log makes it easier to look them up and find them in-game; people used to give us bug reports where a certain trainer would crash the game and they had some wild name like "Landlord Gary" or something like that.

There was some planned work to have the logs display *both* the original name and randomized name, but it never got done. Perhaps I should do that now....
