### ISSUE TITLE
Cant use the launcher on linux

### ISSUE THREAD

**Issue by harryos06** [Ajarmar/universal-pokemon-randomizer-zx#265]
i might be stupid

**Comment by tom-overton** [comment]
I don't think we've ever tried using the launcher on Linux. Can you describe in detail what happens? What operating system are you using and how are you attempting to start the launcher? Are you double-clicking on it or are you executing it via the terminal?

**Comment by FoteinoHelios** [comment]
I'm also having an issue with linux, when you go to open any of the launcher files it just opens them as a text file instead of actually using them as a command. I'm on Ubuntu version 21.04 if that helps at all.

**Comment by FoteinoHelios** [comment]
Nvm you can run the UNIX.sh file by using this command in terminal  $ ./launcher_UNIX.sh 
It's a little annoying but it works

**Comment by tom-overton** [comment]
Do the instructions here still apply? https://askubuntu.com/questions/38661/how-do-i-run-sh-scripts/1065846#1065846
We were hoping that Linux users could just double-click on the scripts to launch the randomizer like Windows/Mac users but it appears you may need to change some sort of configuration.

**Comment by tom-overton** [comment]
I added that StackOverflow post to the pinned issue about the launcher so I'm just going to close this one. If you have other issues involving the Unix launcher, please use that issue instead.
