### ISSUE TITLE
Can't use the launcher on windows [Bug] 

### ISSUE THREAD

**Issue by psy-chx** [Ajarmar/universal-pokemon-randomizer-zx#267]
**The bug**
I expected the launcher to, well, launch the program, but it didn't.
Whenever I try to open the windows launcher, I'm met with this error. 
Invalid maximum heap size: -Xmx4096M
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Press any key to exit...
Any way to fix it?

**To Reproduce**
1. Go to the file where its been extracted
2. Click on launcher_WINDOWS.bat
3. See error

**System (please complete the following information):**
 - Operating System: Windows 
 - Java Version: Version 8 Update 301
 - Randomizer Version: v4.2.1

**Additional context**

**Comment by tom-overton** [comment]
You're using 32-bit Java, which doesn't work with the randomizer. You need 64-bit Java installed; see the [Java section](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java) of our wiki for more information.

Additionally, please refer to #221 for launcher-related issues. There's a section in the first post dedicated specifically for this issue.

**Comment by psy-chx** [comment]
…Oh.
My bad. Sorry about that.
