### ISSUE TITLE
[Bug] Incorrect Japanese notation in Gen 1 and 2

### ISSUE THREAD

**Issue by Hoki0Niwa** [Ajarmar/universal-pokemon-randomizer-zx#271]
**Describe the bug**
In the Japanese version of the Game Boy ROM, the word that should be written as "オ" is changed to "ォ". 
For example, Dodrio is written in Japanese as "ドードリオ", but in the modified game it is written as "ドードリォ".

**Screenshots**
Correct
![bgb00001](https://user-images.githubusercontent.com/50765794/130447269-eca4b179-3a8c-474d-b9e4-bf07b488080c.png)

Incorrect
![bgb00002](https://user-images.githubusercontent.com/50765794/130447285-663b521a-d7f6-4b0a-8cdc-5716ca4ff7b8.png)
![image](https://user-images.githubusercontent.com/50765794/130446059-c2cac549-e5a1-4239-87a8-9f4321a7e205.png)

**System (please complete the following information):**
 - Operating System: Windows 10
 - Java Version: OpenJDK version 1.8.0-292
 - Randomizer Version: [4.2.1]

**Comment by tom-overton** [comment]
Thanks for the report; this will be fixed in the next release. To my knowledge, this has *always* been broken in Universal Pokemon Randomizer, even before we forked it!
