### ISSUE TITLE
Error when opening the launcher

### ISSUE THREAD

**Issue by Gabbenator69** [Ajarmar/universal-pokemon-randomizer-zx#274]
This is the error code I get when I open the launcher and I don't know what to do. Pls help.

'\\fs1.ad.ssis.nu\20garo\Desktop\pokemon'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
'\\fs1.ad.ssis.nu\20garo\Desktop\pokemon\'
CMD does not support UNC paths as current directories.
Error: Unable to access jarfile PokeRandoZX.jar
Press any key to exit...

**Comment by tom-overton** [comment]
Open up `launcher_WINDOWS.bat` in a text editor and replace the contents with this:
```
@echo off
pushd %~dp0
cd /d "%~dp0"
java -Xmx4096M -jar PokeRandoZX.jar please-use-the-launcher
echo Press any key to exit...
pause >nul
```

Does that work?

**Comment by Gabbenator69** [comment]
How do I open it in a text editor?

**Comment by Gabbenator69** [comment]
Never mind, it worked. Thanks for the help!

**Comment by tom-overton** [comment]
You're welcome! Glad it worked. You're the first person to try and run the launcher off of a network drive, so we needed to make a slight tweak to the launcher to get it working. The next release will include this change, but for now keep using what I sent you before and everything will work fine.
