### ISSUE TITLE
Not saving

### ISSUE THREAD

**Issue by Nod4mag3** [Ajarmar/universal-pokemon-randomizer-zx#275]
I have used the randomizer once to randomize US/UM, and it worked, but now I'm trying to randomize X/Y the saving doesn't work properly.  It says it's saving for around 2 hours and when it's done, the file is corrupted

 - Operating System: Windows 10
 - Randomizer Version: 4.2.1

**Comment by tom-overton** [comment]
There could be many different reasons why this is happening. Did a log file get created for this seed? Do you have disc space on your computer?

**Comment by Nod4mag3** [comment]
> There could be many different reasons why this is happening. Did a log file get created for this seed? Do you have disc space on your computer?

I think a log file was created, and I have around 30 gigs of space on the disk left

**Comment by tom-overton** [comment]
Well, if a log file was created, can you supply it here?

**Comment by Nod4mag3** [comment]
Where would I find that?

**Comment by tom-overton** [comment]
It would be in the same directory as the outputted ROM. It should have the same name, just with ".log" at the end of it.
