### ISSUE TITLE
[Contribution Idea] Randomization of pokemon encounters by evolutionary stage

### ISSUE THREAD

**Issue by Poppyanimal** [Ajarmar/universal-pokemon-randomizer-zx#279]
**Is your idea a new setting, a change to an existing setting, or something else? Please describe clearly:** 
------------------
Randomization of pokemon by evolution for wild pokemon and trainers. This would allow trainers and wild pokemon to be swapped with pokemon of the same evolution type (a stage 1 of 3 will be swapped with a stage 1 of 3, a pokemon that doesnt evolve with one that doesnt evolve, a stage 2 of 2 with a stage 2 of 2.)

If seen fit, I can also have stage 1 of 3s can be treated in the same pool as stage 1 of 2s (and vice versa) as well as stage 3 of 3s being swap-able with stage 2 of 2's (and vice versa), effectively treating fully evolveds and not evolveds equally

**What problem would your contribution solve? Please describe:** 
--------------------
A sense of logical randomization that is currently only filled by randomization of pokemon by similar bst.

**Additional context:**
---------------------
I have already implemented this previously on a fork of the original repo (not zx, but dabomstew's speedchoice) and the activity / wealth of notable changes made by zx has motivated me to want to try recreating it for the zx randomizer version.

**Comment by Poppyanimal** [comment]
some addendums:
addendum 1: this option would also be available for totem pokemon
addendum 2: it is likely that under certain conditions and selected options this may restrict the pool of available pokemon significantly, which may be something to account for when considering whether to group unevolved two/three stages and fully evolved two/three stages (note, in the case they are grouped, 2nd stage evos of 3 stage chains will be left with only other 2nd stage of 3 to swap with)

**Comment by tom-overton** [comment]
I don't see this as something significantly different from "similar strength" to cause users to choose it as an option. If someone wants Pokemon of similar strength, then the existing "similar strength" setting does a better job of ensuring this, since it doesn't allow random Bug Catchers in the first forest who originally had Kakuna to suddenly have things like Dragonair and Electabuzz. If someone doesn't care about maintaining similar strength, then they likely *also* don't care about maintaining the evolutionary line.

**Comment by Poppyanimal** [comment]
while I do think that by itself the changes are minimal, it does work in situations where similar strength would fail, such as randomizing bst totals and as such reaffirm their usage in that use case where similar strength would fail. I also have a bit of a personal bias towards seeing early routes having random base form pokemon, regardless of bst total, and similar for the inverse.
