### ISSUE TITLE
[Contribution Idea] Option to equalize all pokemon's base stat totals

### ISSUE THREAD

**Issue by Poppyanimal** [Ajarmar/universal-pokemon-randomizer-zx#281]
**Is your idea a new setting, a change to an existing setting, or something else? Please describe clearly:** 
------------------------------
This would add an option to change the base stat *total* of all pokemon to be the same total, the new total will be based on the average bst of a pokemon in general which without running the check myself would likely be a number around the mid 400s.

This option would either be a checkbox or a radial in the pokemon base statistics section. In the case of a checkbox it would equalize all pokemon's bst prior to the rest of the base statistic randomization and after the update base stats section so it will retain a pokemon's relative stat totals in the case other bst randomization is not desired.
in the case of it being a radial, it'd have to be decided whether or not it should be multiple radials and whether or not to include each of the following: equalize but dont randomize, equalize but shuffle, equalize but random. I am open to whatever approach is deemed best if any at all for this idea.

**What problem would your contribution solve? Please describe:** 
-------------------------------
The fact that despite the randomizer having an assortment of randomization options, the relative power of a pokemon stat wise from one to another remains rather consistent. this aims to help pokemon with lower base stat totals find their niche and also I just think the idea is neat.

**Additional context:**
--------------------------------
I know I've been submitting a lot of these, but I simply wish to know what I should attempt to carry over from my previous tinkerings with UPR as well as try a few of the ideas again from scratch with a more planned out end point.

**Comment by tom-overton** [comment]
I feel like #282 is just a much more interesting approach to solving the same problem, which is changing the relative strength of Pokemon from the base games. While that idea still allows for variation between Pokemon, this flattens their differences, which seems like it would get boring pretty quickly outside of maybe trying one or two seeds.
