### ISSUE TITLE
Hi, downloaded v4.2.1, on pc, windows 10, when the launcher, this comes up. thanks  [Help] 

### ISSUE THREAD

**Issue by Creasi0n** [Ajarmar/universal-pokemon-randomizer-zx#284]
**Describe your problem clearly:** 

**System (please fill in the following information):**
 - Operating System: 
 - Randomizer Version: 

**If your problem is that you can't randomize a game:**
If you get a popup saying that there has been an "unhandled exception", please attach the error log as an attached file to this issue.
[
![Screenshot 2021-08-28 154255](https://user-images.githubusercontent.com/89679011/131207696-4e143122-7655-4dda-82f2-5af387a7110c.png)
](url)

**Comment by Nod4mag3** [comment]
You need to download a 64-bit version of java, I think

**Comment by Creasi0n** [comment]
That was it, awesome thanks
