### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by BelgianThief** [Ajarmar/universal-pokemon-randomizer-zx#285]
you cannot enable no game breaking moves without having to randomise movesets. I want to do a similar strength pokemon randomiser that is as vanilla as possible but I cant enable no game breaking moves without having to randomise movesets which is frustrating.

**Comment by tom-overton** [comment]
This isn't a bug. Removing game-breaking moves without randomizing movesets has *never* worked, even if older versions of the randomizer (namely Dabomstew's original version of it) allowed you to select it. See #163 for more info.

**Comment by BelgianThief** [comment]
so are  you not planning on fixing it?

**Comment by tom-overton** [comment]
It's not a bug so no, I'm not going to fix it.

**Comment by BelgianThief** [comment]
is there anyone you know who I can contact who might want to include it?
