### ISSUE TITLE
Base Stats are not updating

### ISSUE THREAD

**Issue by leokatchu** [Ajarmar/universal-pokemon-randomizer-zx#286]
Hey there, I have a problem with the UPR ZX, version 4.2.0 and 4.2.1
When I select the option to update the base stats to either Generation 6 or 7 in a Gen 4 or 5 ROM (I tested it with both HG and B2), the log file says no base stats were changed.

![1](https://user-images.githubusercontent.com/73904568/131224988-21442efd-622a-457a-8f16-56104c3db2c3.PNG)
As you can see here, I selected the option to update base stats to Gen 7...

![2](https://user-images.githubusercontent.com/73904568/131225008-10456661-ce86-48b9-aabc-fe4b49538c56.PNG)
...and I selected the option to update the moves,

And here is what the log file says:

![3](https://user-images.githubusercontent.com/73904568/131225032-77bc45b9-414b-4385-93d0-87d6ed6d3819.PNG)
It says that multiple moves were updated...

![4](https://user-images.githubusercontent.com/73904568/131225047-9d1709f5-0ff7-4b3c-9874-d6b7358e8bfc.PNG)
But also that the base stats are unchanged.

Is this a bug or am I just interpreting the log file wrong?

**Comment by tom-overton** [comment]
Nope, you found a bug. The stats *are* being updated, but they're not being written to the log. I'll fix that in the next release.
