### ISSUE TITLE
[Bug] Similar strength in Platinum isnt working for Foe pokemon or Wild encounters

### ISSUE THREAD

**Issue by benb8002** [Ajarmar/universal-pokemon-randomizer-zx#289]
**Describe the bug**
After randomizing my Platinum pokemon game, the wild pokemon are still completely random despite the "use similar strength" option. Specifically finding rapidash and garchomp in the starting routes. 

**To Reproduce**
I am using a clean file of pokemon Platinum, only settings enabled are "use similar strength" under the wild encounter tab.

**Expected behavior**
Unless I am unaware of how the setting works, this should randomize all wild encounters based on BST and not consider evolutionary lines aside from the individual pokemon

**System (please complete the following information):**
 - Operating System: Windows 10
 - Java Version: build 1.8.0_281-b09
 - Randomizer Version: 4_2_1

**Comment by tom-overton** [comment]
Can you please supply a log file? Without a log file, there's nothing I can do.

**Comment by benb8002** [comment]
Sorry for the late reply, im still pretty new to this, how do I get the log file for you?

**Comment by benb8002** [comment]
sorry for the late reply, works kept me away for a bit. 

This is the log file from me using the program just now, confirmed the similar power isnt happening. Thank you for the fast reply
[plattest.nds.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/7110629/plattest.nds.log)

**Comment by tom-overton** [comment]
This exact same settings/seed combination works perfectly fine for me:
[test.nds.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/7114432/test.nds.log)

You can see the difference on Route 201:
Yours:
```
Set #373 - Route 201 Grass/Cave (rate=30)
HOUNDOUR Lv2             HP 45  ATK 60  DEF 30  SPATK 80  SPDEF 50  SPEED 65 
UXIE Lv2                 HP 75  ATK 75  DEF 130 SPATK 75  SPDEF 130 SPEED 95 
TRAPINCH Lv3             HP 45  ATK 100 DEF 45  SPATK 45  SPDEF 45  SPEED 10 
PIDGEY Lv3               HP 40  ATK 45  DEF 40  SPATK 35  SPDEF 35  SPEED 56 
FLYGON Lv3               HP 80  ATK 100 DEF 80  SPATK 80  SPDEF 80  SPEED 100
MACHAMP Lv3              HP 90  ATK 130 DEF 80  SPATK 65  SPDEF 85  SPEED 55 
CLEFABLE Lv3             HP 95  ATK 70  DEF 73  SPATK 85  SPDEF 90  SPEED 60 
UNOWN Lv3                HP 48  ATK 72  DEF 48  SPATK 72  SPDEF 48  SPEED 48 
DODUO Lv2                HP 35  ATK 85  DEF 45  SPATK 35  SPDEF 35  SPEED 75 
TYRANITAR Lv2            HP 100 ATK 134 DEF 110 SPATK 95  SPDEF 100 SPEED 61 
DUSKNOIR Lv2             HP 45  ATK 100 DEF 135 SPATK 65  SPDEF 135 SPEED 45 
MEW Lv2                  HP 100 ATK 100 DEF 100 SPATK 100 SPDEF 100 SPEED 100
```

Mine:
```
Set #373 - Route 201 Grass/Cave (rate=30)
MAKUHITA Lv2             HP 72  ATK 60  DEF 30  SPATK 20  SPDEF 30  SPEED 25 
NINCADA Lv2              HP 31  ATK 45  DEF 90  SPATK 30  SPDEF 30  SPEED 40 
MAKUHITA Lv3             HP 72  ATK 60  DEF 30  SPATK 20  SPDEF 30  SPEED 25 
MAGIKARP Lv3             HP 20  ATK 10  DEF 55  SPATK 15  SPDEF 20  SPEED 80 
MAKUHITA Lv3             HP 72  ATK 60  DEF 30  SPATK 20  SPDEF 30  SPEED 25 
NINCADA Lv3              HP 31  ATK 45  DEF 90  SPATK 30  SPDEF 30  SPEED 40 
MAKUHITA Lv3             HP 72  ATK 60  DEF 30  SPATK 20  SPDEF 30  SPEED 25 
NINCADA Lv3              HP 31  ATK 45  DEF 90  SPATK 30  SPDEF 30  SPEED 40 
MAKUHITA Lv2             HP 72  ATK 60  DEF 30  SPATK 20  SPDEF 30  SPEED 25 
NINCADA Lv2              HP 31  ATK 45  DEF 90  SPATK 30  SPDEF 30  SPEED 40 
MAKUHITA Lv2             HP 72  ATK 60  DEF 30  SPATK 20  SPDEF 30  SPEED 25 
NINCADA Lv2              HP 31  ATK 45  DEF 90  SPATK 30  SPDEF 30  SPEED 40 
```

Looking at your ROM Diagnostics section, I see some notable discrepancies:
Yours;
```
arm9: 306AE7BB
overlay9_5: BB9E62F5
overlay9_78: D50BC070
fielddata/encountdata/pl_enc_data.narc: 95E0021C
fielddata/pokemon_trade/fld_trade.narc: 37196950
fielddata/script/scr_seq.narc: B0C9F27C
msgdata/pl_msg.narc: C7E9D98E
poketool/personal/evo.narc: DB9D8521
poketool/personal/pl_personal.narc: EB4A21FF
poketool/trainer/trpoke.narc: 29E3B492
```

Mine:
```
arm9: 4D104949
overlay9_5: 3E286491
overlay9_78: 091E8E97
fielddata/encountdata/pl_enc_data.narc: 188084F5
fielddata/pokemon_trade/fld_trade.narc: B98CC1AF
fielddata/script/scr_seq.narc: 6D482515
msgdata/pl_msg.narc: 5666AAEC
poketool/personal/evo.narc: 6711E4B4
poketool/personal/pl_personal.narc: B16A8A01
poketool/trainer/trpoke.narc: 739A02EE
```

Is this some sort of ROM hack?

**Comment by tom-overton** [comment]
It's been almost a month since I asked my last question. @benb8002 did you ever get this working with a vanilla version of Platinum?

**Comment by tom-overton** [comment]
It's been a week since I asked my question, and more than a month since my initial response, so I'm going to assume you got this working.
