### ISSUE TITLE
[Bug] Pokemon X not randomizing properly

### ISSUE THREAD

**Issue by HomelezJosef** [Ajarmar/universal-pokemon-randomizer-zx#291]
Currently trying to randomize Pokémon X, and the only things that seem to be randomizing are the other trainer's Pokémon, and the move sets. I've re-randomized multiple times, but have had no success. It is a .3ds file, which should work properly with the randomizer. This is my first time trying to randomize a gen above 5, so some help would be nice, Thanks!

**Comment by tom-overton** [comment]
A few things:
1. Can you please supply a log file? Without it, it's hard to tell what's *supposed* to be happening here. You have the option of creating a log file every time you make a seed; just drag the resulting .log file into this text box and it will upload it so I can take a look.
2. Even without a log file, I'm just going to take a shot in the dark as to what's wrong. Are you outputting as CXI then loading it in Citra? If so, do you have a game update installed in Citra? You can tell if you have a game update installed by looking for something like "Ver 1.5" on the title screen like this:
![image](https://user-images.githubusercontent.com/12245827/132258202-d9eba0e6-c72a-436b-a06e-24ac48c98d4b.png)

If you have a game update installed in Citra or on your 3DS, you have two options:
- Delete the game update. You can follow the instructions [here](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Randomizing-the-3DS-games#managing-game-updates-in-citra) to delete it
- Load a CIA of the same game update inside the randomizer. You can follow the instructions [here](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Randomizing-the-3DS-games#3ds-game-updates) to load it

Now if you *don't* have a game update installed, that's fine. It just means I'll need to take a look at the log file to see what's going on.

**Comment by HomelezJosef** [comment]
[Try This Again.cxi.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/7121182/Try.This.Again.cxi.log)

That is the log file, I do have the update installed (v 1.5) so I'll attempt the deleting strat, and hopefully something works out.

**Comment by HomelezJosef** [comment]
The file deleting did work, thank you for your help
