### ISSUE TITLE
I cant randomize Black/White

### ISSUE THREAD

**Issue by Niklas2408** [Ajarmar/universal-pokemon-randomizer-zx#294]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - Operating System: Windows
 - Java Version: 8 update 301
 - Randomizer Version: 4.2.1

**Additional context**
Randomizer Version: 4.2.1
Seed: 259134382294795
Settings String: 316AAgEAQTuAfEB9AEEAAEeRAABFAAAFABABAABAAAAAAAAAAAAMgQyAQAICTIGBgAyABFQb2tlbW9uIEJsYWNrIChHKdIFphLjwziK
Java Version: 1.8.0_261, Java HotSpot(TM) 64-Bit Server VM
ROM: Pokemon Black (G)
Code: IRBD
Reported Support Level: Complete

com.dabomstew.pkrandom.exceptions.RandomizerIOException: java.lang.ArrayIndexOutOfBoundsException: 7198
	at com.dabomstew.pkrandom.romhandlers.Gen5RomHandler.getStaticPokemon(Gen5RomHandler.java:1988)
	at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:400)
	at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$performRandomization$105(NewRandomizerGUI.java:880)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 7198
	at com.dabomstew.pkrandom.romhandlers.Gen5RomHandler$RoamingPokemon.getPokemon(Gen5RomHandler.java:1732)
	at com.dabomstew.pkrandom.romhandlers.Gen5RomHandler.getStaticPokemon(Gen5RomHandler.java:1983)
	... 3 more

--ROM Diagnostics--
arm9: EBD87FEE
overlay9_10: 1FEE4A25
a/0/0/2: 088A95B9
a/0/0/3: 5064AD57
a/0/0/4: 227031B2
a/0/1/6: 3A3FDA3E
a/0/1/9: 494DF5A2
a/0/2/1: A62E835C
a/0/5/7: 471456A0
a/0/9/2: BF203832
a/0/9/3: A0C7D342

**Comment by tom-overton** [comment]
This was brought up in #259. The short summary is that non-English versions of Black/White don't work in v4.2.1 because of an incorrect assumption I made involving Thundurus/Tornadus. You can use v4.2.0 until the next release (either v4.2.2 or v4.3.0) is ready. Sorry for the bug!

**Comment by Niklas2408** [comment]
Thank you for your answer. It worked. I also tried to randomize rising ruby  / sinking saphire, but i cant save the randomize setting. Neo x worked but not sinking saph/ rising ruby. is that a known bug too?

**Comment by tom-overton** [comment]
Sorry, but we don't support ROM hacks of any kind. If a ROM hack like Neo X worked, it was purely by accident. So Sinking Sapphire/Rising Ruby not working is not a bug; it's basically what we expect.
