### ISSUE TITLE
[Bug] leveling up issue

### ISSUE THREAD

**Issue by Marcossxx123** [Ajarmar/universal-pokemon-randomizer-zx#296]
I randomized pokemon black version 2.
My pokemon aren't getting exp.
I use windows-java.

https://user-images.githubusercontent.com/91039434/133950958-7db121ae-335a-408d-9cc1-b28f8a09be53.mp4

Pls help, i want to finish the randomizer

**Comment by tom-overton** [comment]
This has nothing to do with the randomizer. The problem here is that for some reason, your emulator is triggering the native antipiracy baked into Black/White 2. To fix this, you'll either need to upgrade/switch your emulator or apply an antipiracy cheat code.
