### ISSUE TITLE
[Help] 

### ISSUE THREAD

**Issue by kacperineusz** [Ajarmar/universal-pokemon-randomizer-zx#298]
Hi 
When I run the launcher, I see it. Help me please
![134573763-8fc96fff-9a6f-4532-8cd4-cbfd02b93448 1](https://user-images.githubusercontent.com/91287624/134574904-9f6197cb-23af-4cb2-9f1a-181bda4d18ed.png)

**Comment by tom-overton** [comment]
This indicates that you have 32-bit Java installed. Please install 64-bit Java [as per the instructions on the Java wiki page](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java).

In the future, please use issue #221 for troubleshooting issues with the launcher.
