### ISSUE TITLE
[Help] Could not reserve enough space for object heap

### ISSUE THREAD

**Issue by KomodoSkull** [Ajarmar/universal-pokemon-randomizer-zx#299]
I get and error every time I try to launch the launcher I get the following error:
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
Press any key to exit...

 - Operating System: Windows
 - Randomizer Version: v4.2.1

**Comment by tom-overton** [comment]
Are you running a 32-bit operating system?
