### ISSUE TITLE
Main Class

### ISSUE THREAD

**Issue by TheBlaziking** [Ajarmar/universal-pokemon-randomizer-zx#30]
So I fixed my original issue and it's days later and I try running the program cause I heard it'd randomize the older games in newer ways but when I tried opening it it said I was missing the 'main class file' but I reextracted everything and still am missing it.
![Screenshot_16](https://user-images.githubusercontent.com/53891883/95672587-f2571200-0b6f-11eb-8e61-635a0cd3678d.jpg)

**Comment by Ajarmar** [comment]
What version of Java are you using? You can check it by opening a cmd window and typing `java -version`

You need Java 1.8 (or higher), 64-bit version.

**Comment by TheBlaziking** [comment]
> What version of Java are you using? You can check it by opening a cmd window and typing `java -version`
> 
> You need Java 1.8 (or higher), 64-bit version.

I have the latest version otherwise I wouldn't have got it to work the first time. I tried opening it again and saw what I posted. I reextracted the files and it didn't help. Is there some extra file that got added recently?

**Comment by Ajarmar** [comment]
If you downloaded and extracted the .zip from the release page, then you have every file you need.

If you got the program to run previously and it just suddenly doesn't work, that's certainly weird. Did you modify either of the .jar files in any way?

You can try the following and see if it works: open a cmd window in the folder where you extracted everything (shift+right click in the folder and click "Open command window here") and type `java -jar launcher.jar`

**Comment by TheBlaziking** [comment]
> If you downloaded and extracted the .zip from the release page, then you have every file you need.
> 
> If you got the program to run previously and it just suddenly doesn't work, that's certainly weird. Did you modify either of the .jar files in any way?
> 
> You can try the following and see if it works: open a cmd window in the folder where you extracted everything (shift+right click in the folder and click "Open command window here") and type `java -jar launcher.jar`

All I did to modify the files was to actually get them working but again things were working last week then I tried it again and I got that error. The command window thing works but it'd be a pain to have to do that every single time to get it working.

**Comment by Ajarmar** [comment]
You shouldn't have to modify the .jar files to get the program to work. What issue did you have before modifying them, and in what ways did you modify them?

Alternatively, if you'd prefer to stop troubleshooting and just go with what you have right now, you could put the command I gave you in a batch file and just run that to start the program. Just open a text editor and write `java -jar launcher.jar` in there, then save it in the same folder as the .jar files with a filename ending in .bat (for example, you could call it `run.bat`). Then you should be able to just double click that to start the program.

**Comment by TheBlaziking** [comment]
> You shouldn't have to modify the .jar files to get the program to work. What issue did you have before modifying them, and in what ways did you modify them?
> 
> Alternatively, if you'd prefer to stop troubleshooting and just go with what you have right now, you could put the command I gave you in a batch file and just run that to start the program. Just open a text editor and write `java -jar launcher.jar` in there, then save it in the same folder as the .jar files with a filename ending in .bat (for example, you could call it `run.bat`). Then you should be able to just double click that to start the program.

I had to download a jarfix program because it was stuck as a zip file at first even after extracting it. Not everyone had the issue but me and a few others did and I helped them out of that issue once I found it out but it is an issue that not all computers download it properly at first as mentioned in an old issue I opened. I'll just have to add that other file into things to have it be a 'quick' fix.

**Comment by Ajarmar** [comment]
I haven't used jarfix myself, but I'd wager that there's something with that program that's causing this problem (because I've never seen anyone else have this "Could not find the main class" error before). Anyway, if you're fine with the solution I gave you, feel free to close the issue.

**Comment by TheBlaziking** [comment]
> I haven't used jarfix myself, but I'd wager that there's something with that program that's causing this problem (because I've never seen anyone else have this "Could not find the main class" error before). Anyway, if you're fine with the solution I gave you, feel free to close the issue.

I still think it should be something to look into. The jarfix didn't cause an issue initially, it helped a problem with a faulty download. Some bugs with the zip file should be looked into but that's all I'll note before closing it out since I'm not the only one having issues, just reporting them as they come.
