### ISSUE TITLE
[Help] My universal randomizer for my pokemon sun that is decrypted wont save. I would put everything in and save it as layered and it just says saving for 2 hours and hasn"t finished my friends cant load the randomizer when they open there rom in the randomizer

### ISSUE THREAD

**Issue by savageghost420** [Ajarmar/universal-pokemon-randomizer-zx#302]
**Describe your problem clearly:** 

**System (please fill in the following information):**
 - Operating System: 
 - Randomizer Version: 

**If your problem is that you can't randomize a game:**
If you get a popup saying that there has been an "unhandled exception", please attach the error log as an attached file to this issue.

**Comment by tom-overton** [comment]
1. Can you tell me which version of the randomizer you're using?
2. Assuming you're on Windows, can you open the command prompt (hit Start, type "cmd.exe", and press Enter) then type `java -version` and paste what comes up?
