### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Pepeluuis** [Ajarmar/universal-pokemon-randomizer-zx#312]
Invalid maximum heap size: -Xmx4096M
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Press any key to exit...

**Comment by tom-overton** [comment]
This indicates you have 32-bit Java installed. Uninstall 32-bit Java and install 64-bit Java and this error will go away. See our [Java wiki page](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java) for more info.
