### ISSUE TITLE
Resetting randomiser settings

### ISSUE THREAD

**Issue by Ririchu21** [Ajarmar/universal-pokemon-randomizer-zx#313]
I made a mistake when I was doing my settings for my ultra sun playthrough.

 - Operating System: Windows 10
 - Randomizer Version: v4.2.1

![image](https://user-images.githubusercontent.com/92225399/136667924-e093225d-4bc9-427e-85fd-804dc837178e.png)

![image](https://user-images.githubusercontent.com/92225399/136667958-23798e03-75d0-4ddf-83ad-cd06e8d53e55.png)

**Comment by tom-overton** [comment]
Is this some sort of ROM hack? The ROM Diagnostics look different from my clean ROM of Pokemon Sun:
```
--ROM Diagnostics--
.code: DE47EF73
romfs header: EE3DB972
a/0/1/1: 1E3831AE
a/0/1/4: 4732336F
a/0/1/5: 4001BBAB
a/0/1/7: 81A28B5B
a/0/3/2: 7C6240E6
a/0/4/2: B651F900
a/0/6/2: 7B1D8B2A
a/0/7/7: 76C0FCE0
a/0/8/2: C25E1A15
a/0/9/1: 8B6B447D
a/1/0/5: 51FC0767
a/1/0/6: 2F5EFBF1
a/1/5/5: 7E3092FF
```

**Comment by Ririchu21** [comment]
So would anyone know how I would change my randomiser settings to change a few things? Also when I'm using the randomiser and playing is it possible to reset the changes to say get different starter pokemon? 
thanks
