### ISSUE TITLE
TMs not randomizing for Pokemon Ultra Sun

### ISSUE THREAD

**Issue by darkbrother321** [Ajarmar/universal-pokemon-randomizer-zx#314]
Simply put, the TMs will not randomize no matter what I do. Everything else randomizes except for TMs

**Comment by tom-overton** [comment]
I'm fairly certain what's happening is that you have a game update installed in Citra or on your 3DS. See if you have something like "Ver 1.5" on the file select screen like this:

![image](https://user-images.githubusercontent.com/12245827/97775269-90f5e380-1b1c-11eb-98de-e482b1db036b.png)

If you have a game update installed in Citra or on your 3DS, you have two options:
1. Delete the game update. You can follow the instructions [here](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Randomizing-the-3DS-games#managing-game-updates-in-citra) to delete it
2. Load a CIA of the same game update inside the randomizer. You can follow the instructions [here](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Randomizing-the-3DS-games#3ds-game-updates) to load it
