### ISSUE TITLE
[Bug] Text error in my pokemon sun randomizer rout 2e PC trade

### ISSUE THREAD

**Issue by dragonfang93** [Ajarmar/universal-pokemon-randomizer-zx#315]
Hello,

Please note, when i play through the randomizer for pokemon sun, i experience a text issue: my name replace both the name of the pokemon the NPC wanted and will give. Please see the image below.

I did not proceed too far into the game to see if this issue reappear with another NPC trader.

I hope this helps

![route 3 text glitch to name not pokemon](https://user-images.githubusercontent.com/92344584/136872433-a76d271f-859d-4785-8735-471e8a8d0f2a.png)

**Comment by tom-overton** [comment]
Thanks for reporting this! I fixed this issue, and it will be part of the upcoming 4.3.0 release of the randomizer.
