### ISSUE TITLE
[Feature Request] Type themed trainers exclusive to Gym Trainers/Leaders/Elite 4

### ISSUE THREAD

**Issue by forsetite** [Ajarmar/universal-pokemon-randomizer-zx#32]
In regular Pokemon games type-themed trainers are usually mostly found in gyms while regular trainers on routes have more diverse teams - would be cool if the randomiser could reflect this sort of thing where either every trainer in a gym has a randomised team of the same type (eg all gym trainers are rock type) or just randomising the types of gym leaders or type specialists only - dunno just spitballing here

**Comment by Ajarmar** [comment]
Sorry, but we don't take feature requests. As for this particular case, I don't think it really makes sense to change it because there are many regular trainers that have type themes in the regular Pokemon games.
