### ISSUE TITLE
[Bug] Everytime i double click on "launcher_WINDOWS.bat" it opens a window where it says "Error: Unable to access jarfile PokeRandoZX.jar" 

### ISSUE THREAD

**Issue by Tinghow** [Ajarmar/universal-pokemon-randomizer-zx#320]
**Describe the bug**

Everytime i double click on "launcher_WINDOWS.bat" it opens a window where it says "Error: Unable to access jarfile PokeRandoZX.jar" 

**To Reproduce**
1. Go to 'PokeRandoZX-v4_2_1'
2. Click on 'launcher.jar'
3. Double click on "launcer_WINDOWS.bat'

**Expected behavior**
I thought that it would open the client to let me use the universal pokemon randomizer
**Screenshots**
![POKEMON HELP](https://user-images.githubusercontent.com/92941800/138319396-0148094d-4f29-4322-a7ba-d0f1e8e1c106.png)

**System (please complete the following information):**
 - Operating System: I am on a laptop but i don't know the specific model
 - Java Version: 8.0.3110.11
 - Randomizer Version: 4_2_1

**Additional context**

**Comment by tom-overton** [comment]
Did you move the PokeRandoZX.jar file out of the folder you downloaded it from? If not, try moving the randomizer to a different directory; sometimes, permission issues can cause the launcher to not work.

In the future, please use #221 to troubleshoot launcher issues.

**Comment by OzawaTorio** [comment]
Help, I've encounter this similar situation. I did move the file to different location but it doesn't work. It's kept popping up the same window

**Comment by KichiBird** [comment]
the launcher.jar is gone from my files
