### ISSUE TITLE
[Help] Error when trying to save randomized file

### ISSUE THREAD

**Issue by aznboi97** [Ajarmar/universal-pokemon-randomizer-zx#322]
**Describe your problem clearly:** 

**System (please fill in the following information):**
 - Operating System: 64x
 - Randomizer Version: Latest downloaded same day

**If your problem is that you can't randomize a game:**
If you get a popup saying that there has been an "unhandled exception", please attach the error log as an attached file to this issue.
[error_2021-10-21-22-28-31.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/7394493/error_2021-10-21-22-28-31.txt)
[error_2021-10-21-22-30-02.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/7394494/error_2021-10-21-22-30-02.txt)

**Comment by supar00** [comment]
I have almost the same problem , please can you help me 
[error_2022-08-22-15-59-39.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/9395704/error_2022-08-22-15-59-39.txt)
.
