### ISSUE TITLE
[Help] 

### ISSUE THREAD

**Issue by 09vivid** [Ajarmar/universal-pokemon-randomizer-zx#326]
**Describe your problem clearly:** 
I have opened the launcher several times and the game is up to date, but the launcher says I’m not using the launcher or I haven’t got the updated version when I have
**System (please fill in the following .information):**
 - Operating System: 
 - Randomizer Version: 

**If your problem is that you can't randomize a game:**
If you get a popup saying that there has been an "unhandled exception", please attach the error log as an attached file to this issue.

**Comment by tom-overton** [comment]
Did you double-click on launcher_WINDOWS.bat (assuming you're using Windows)?
