### ISSUE TITLE
hello i randomized my omega ruby but when i walk out of the truck this happens

### ISSUE THREAD

**Issue by Bobbymanbo** [Ajarmar/universal-pokemon-randomizer-zx#328]
im using version 4.2.1 

![IMG_2469](https://user-images.githubusercontent.com/93375482/139465140-85d0df86-b32a-4475-b7f0-e926742dae71.jpg)

**Comment by tom-overton** [comment]
Can you share the log file for this randomization? I'd like to try it myself.

**Comment by Bobbymanbo** [comment]
sry it wouldnt let me send the log file but this is everything in it
Randomizer Version: 4.2.1
Random Seed: 175117139324085
Settings String: 316AAgEAQL7AP4AAQEEAAEeRAABFAAAFABABAABAAAAAAAAAAAAMgQyAQAICTIHBwAyABJQb2tlbW9uIE9tZWdhIFJ1Ynlato1M48M4ig==

Pokemon base stats & type: unchanged

--Random Starters--
Set starter 1 to Abra
Set starter 2 to Zigzagoon
Set starter 3 to Goldeen
Set starter 4 to Cleffa
Set starter 5 to Swoobat
Set starter 6 to Mudkip
Set starter 7 to Sewaddle
Set starter 8 to Rufflet
Set starter 9 to Corsola
Set starter 10 to Helioptile
Set starter 11 to Mantyke
Set starter 12 to Gurdurr

Move Data: Unchanged.

Pokemon Movesets: Unchanged.

Trainers: Unchanged.

Static Pokemon: Unchanged.

Wild Pokemon: Unchanged.

TM Moves: Unchanged.

Move Tutor Moves: Unchanged.

------------------------------------------------------------------
Randomization of Pokemon Omega Ruby completed.
Time elapsed: 422ms
RNG Calls: 12
------------------------------------------------------------------

--ROM Diagnostics--
.code: 575A1629
romfs header: D39632B9
DllField.cro: F929EB93
DllPoke3Select.cro: F4A1F22E
DllShinkaDemo.cro: 53AC2B89
a/0/1/3: BD3DF991
a/0/3/6: F2F2FCFE
a/0/3/8: 9C55C332
a/0/7/3: 0EF80A2A
a/0/9/1: 2AA511AA
a/1/8/9: D17DC884
a/1/9/2: 21DCE891
a/1/9/3: 43D2B7D0
a/1/9/5: ABB02044

**Comment by tom-overton** [comment]
This exact same seed/setting combo worked fine for me. Your log and my log look identical outside of the time elapsed:
[test.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/7457945/test.log)
 
Are you sure that your layeredFS is completely cleaned out before copying the randomized files over? If you have other layeredFS hacks applied simultaneously, they may cause conflicts with the randomizer.
