### ISSUE TITLE
[Feature Request] Randomize Pokemon by Specific Type or Typings

### ISSUE THREAD

**Issue by Sharkdragon247** [Ajarmar/universal-pokemon-randomizer-zx#33]
Since it's almost Halloween, I thought it would be fun to play a game where all the Pokemon were randomized to be Ghost Types or other spooky themed types, but UPR doesn't have that feature and using a romhacking tool just to change every Pokemon's type is tedious. I would love to see UPR implement this feature so that it's easy to just pick a type to randomize to.

**Comment by Ajarmar** [comment]
Sorry, but we don't take feature requests.
