### ISSUE TITLE
Early mega evolutions on alpha Sapphire[Help] 

### ISSUE THREAD

**Issue by Underusedapple** [Ajarmar/universal-pokemon-randomizer-zx#330]
I recently randomized an alpha sapphire file and everything is working. I actually very early on managed to get latias and a latiasite but if I give it the latiasite I can't mega it. I just beat the second gym. Do you have to get to post game content, am I missing a feature the randomizer has, or is this as intended?

**Comment by FrostedGeulleisia** [comment]
Script modifications are still in their infancy in gen6-7, There's simply no way to set the "Enable Mega Evolution" flag early on, and it's not a modifiable flag in PkHeX in Gen 6 (It is in Gen 7 IIRC). Because of that, there's sadly no way to Mega Evolve before obtaining Lati@s after gym 5.

**Comment by Underusedapple** [comment]
I was thinking that but just wanted to confirm. Thank you!

**Comment by tom-overton** [comment]
Yeah, there's no setting for this currently. There could potentially be one assuming that we could get it working for both Gen 6 and Gen 7, but there frankly isn't a ton of motivation to make this work.
