### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ayx700** [Ajarmar/universal-pokemon-randomizer-zx#331]
I have no issues pulling up the randomizer, but it won't let me limit the pokemon generation once I open the ROM, that option in the top right corner disappears.

**Comment by tom-overton** [comment]
Can you describe which version of the randomizer you’re using, as well as which game you’re trying this for?

**Comment by ayx700** [comment]
Omega Ruby (but I also tried with ultra moon) and the most up to date version v4.2.0.

**Comment by tom-overton** [comment]
Limit Pokemon works fine in the current version of the randomizer. Have you actually tried it yourself in v4.2.1? If you're watching an older YouTube video, they could be using older versions where it was not supported.
