### ISSUE TITLE
[Help] Is it possible to get the log of an already randomized game?

### ISSUE THREAD

**Issue by feephoenixx** [Ajarmar/universal-pokemon-randomizer-zx#332]
**Describe your problem clearly:** 
I previously randomized Pokemon X but did not save a log, and now want to know what was changed. Is it possible to dump the game and check what's been randomized or would I need to just start over again?

**System (please fill in the following information):**
 - Operating System: Windows 10
 - Randomizer Version: v4.2.1 Currently, the version I used originally might have been either 3.1.0 or 4.0.x

**Comment by tom-overton** [comment]
Unfortunately, no, there's no way within the randomizer itself to get the log of an already randomized game. You could use a ROM hacking utility like [pk3DS](https://projectpokemon.org/home/forums/topic/34377-pk3ds-xy-oras-rom-editor-and-randomizer/) to get a look at the files in the game to see what's different, but it won't be as convenient as a log.
