### ISSUE TITLE
I tried to load it from launcher_Windows and error occurred on Windows 10 21H1[Bug] 

### ISSUE THREAD

**Issue by MichaelPonGithub** [Ajarmar/universal-pokemon-randomizer-zx#334]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - Operating System: 
 - Java Version:
 - Randomizer Version: 

**Additional context**

**Comment by tom-overton** [comment]
Please look at #221 for launcher-related issues. In particular, follow the troubleshooting steps to see if any resolve your problem.
