### ISSUE TITLE
Unhandled Exception when trying to Randomize

### ISSUE THREAD

**Issue by KrypticBeard** [Ajarmar/universal-pokemon-randomizer-zx#335]
When I try to randomize a .3ds game (OmegaRuby) it throws an unhandled exception. I have tried both CXI and the LayeredFS. I tried both a clean rom and one was already randomized. I tried this with both 4.2.0 and 4.2.1
[error_2021-11-11-12-45-21.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/7522286/error_2021-11-11-12-45-21.txt)

**Comment by tom-overton** [comment]
Is the log you shared the one that you called "a clean rom"? Because I randomized using your settings and it worked fine:
[test.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/7522652/test.log)

Our ROM Diagnostics are pretty different:
Yours:
```
.code: EDF0DA38
romfs header: 371A1FFD
DllBattle.cro: E78107DF
DllField.cro: 63367726
DllPoke3Select.cro: EA2E7CA3
a/0/1/3: A18FED98
a/0/3/6: C5C2C75A
a/0/3/8: 8A870E54
a/0/7/1: 3012FCBF
a/0/7/2: 75638696
a/0/7/3: 0A767FE9
a/0/7/4: 63BC908F
a/0/7/5: 79E211CF
a/0/7/6: 631C8EAA
a/0/7/7: 3467A16A
a/0/7/8: 29518B34
a/0/9/1: 2AA511AA
a/1/8/9: D17DC884
a/1/9/1: C03B6E88
a/1/9/2: C5FD52A5
a/1/9/3: 43D2B7D0
a/1/9/5: ABB02044
```

Mine:
```
.code: 575A1629
romfs header: D39632B9
DllBattle.cro: E78107DF
DllField.cro: F929EB93
DllPoke3Select.cro: F4A1F22E
DllShinkaDemo.cro: 53AC2B89
a/0/1/3: BD3DF991
a/0/2/9: 3F312B82
a/0/3/6: F2F2FCFE
a/0/3/8: 9C55C332
a/0/7/1: 3012FCBF
a/0/7/2: 75638696
a/0/7/3: 0EF80A2A
a/0/7/4: 63BC908F
a/0/7/5: 79E211CF
a/0/7/6: 631C8EAA
a/0/7/7: 3467A16A
a/0/7/8: 29518B34
a/0/9/1: 2AA511AA
a/1/8/1: 0C1F0B7B
a/1/8/9: D17DC884
a/1/9/1: C03B6E88
a/1/9/2: 21DCE891
a/1/9/3: 43D2B7D0
a/1/9/5: ABB02044
```

**Comment by KrypticBeard** [comment]
Thanks for the check! I must of  done something to the 3ds rom that I was testing. I dumped my game again and was able to get it to work.

**Comment by tom-overton** [comment]
No worries, glad it eventually worked!
