### ISSUE TITLE
fatal error 

### ISSUE THREAD

**Issue by coldestash14205** [Ajarmar/universal-pokemon-randomizer-zx#336]
when i open the launcher_windows i get the cmd pop up saying: Invalid maximum heap size: -Xmx4096M
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Press any key to exit...
how do i fix this?

**Comment by tom-overton** [comment]
This error occurs because you have 32-bit Java installed. You can fix it by installing 64-bit Java. For more information, see [the Java section of our wiki](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java).
