### ISSUE TITLE
Error while launching randomizer app

### ISSUE THREAD

**Issue by JackCarve** [Ajarmar/universal-pokemon-randomizer-zx#337]
Asked for missing dll files such  as api-ms-win-crt-heap-l1-1-0, api-ms-win-crt-runtime-l1-1-0 and vcruntime140.
downloaded the dll files still unable to launch application. Getting error as below screenshot. Please advice
![error](https://user-images.githubusercontent.com/94318607/141696120-541e84c7-c21e-490c-8540-5246b1197135.PNG)

**Comment by tom-overton** [comment]
Try reinstalling Java and seeing if that fixes the issue.
