### ISSUE TITLE
Wont stop saving

### ISSUE THREAD

**Issue by Goosypie** [Ajarmar/universal-pokemon-randomizer-zx#338]
I'm using version 4.2.1 of the randomizer and I'm trying to randomize Pokemon Moon. I waited for about an hour but it won't stop saving, help.

**Comment by tom-overton** [comment]
Can you try again using the newly-released v4.3.0? https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases/tag/v4.3.0
