### ISSUE TITLE
[Help] Invalid Maximum Heap Size - Xmx4096m

### ISSUE THREAD

**Issue by NcGamer69** [Ajarmar/universal-pokemon-randomizer-zx#339]
**Describe your problem clearly:** 
When I launch the Windows Batch file, I get the above error message as well as "Could not create Java Virtual Machine"
I followed the steps for a similar issue and updated my Java program but that did not resolve the issue.

**System (please fill in the following information):**
 - Operating System: Windows 10
 - Randomizer Version: ZX v4.2.1

**If your problem is that you can't randomize a game:**
Cannot launch the randomizer program.

**Comment by tom-overton** [comment]
This error occurs because you have 32-bit Java installed. You can fix it by installing 64-bit Java. For more information, see [the Java section of our wiki](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java).

**Comment by maddiethesexslave** [comment]
> This error occurs because you have 32-bit Java installed. You can fix it by installing 64-bit Java. For more information, see [the Java section of our wiki](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java).

that is wrong i used the 64 bit and it still happened
