### ISSUE TITLE
Replace "java" with "start javaw" in the Windows launcher, and remove pause

### ISSUE THREAD

**Issue by TheFreezingChicken** [Ajarmar/universal-pokemon-randomizer-zx#340]
Nothing revolutionary, just a simple tweak that makes the application more "user friendly" as it closes the command prompt as soon as the jar is launched, and the JVM process gets killed as soon as you exit the program (X on the window), like any other program.

So the launcher bat would become:
```
@echo off
cd /d "%~dp0"
start javaw -Xmx4096M -jar PokeRandoZX.jar please-use-the-launcher
```

I'm saying Windows as I'm not familiar with Linux and Mac, but I'm guessing this tweak might work on those too.

EDIT:
even better like this
```
@echo off  
cd /d "%~dp0"  
echo Wait a few seconds for the randomizer to open...
start javaw -Xmx4096M -jar PokeRandoZX.jar please-use-the-launcher  
timeout 5
```
this way the user knows what's happening before the prompt disappears

**Comment by Ajarmar** [comment]
While removing the terminal looks cleaner, having the terminal stay open is helpful when we need to troubleshoot issues that users run into, so we'll keep it as it is. Thanks anyway!

**Comment by TheFreezingChicken** [comment]
Makes sense, didn't think about that. Although it's usually best practice to use logging for that purpose, but you do you, doesn't change a thing. And now that I think about it I think there's a way to redirect all the console output to a text file even without the console showing 🤔... I'll check that out
