### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by RPZamer** [Ajarmar/universal-pokemon-randomizer-zx#341]
**Describe the bug**
i might be dumb but, when i try to open the launcher, it says "Invalid maximum heap size: -Xmx4096M
The specified size exceeds the maximum representable size." as well as an error "Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit." i already installed the latest version of java, so i dont know whats wrong and why i cant open it
**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/94807684/142780783-a8de08f5-f4d3-433d-9605-66c2a078d8f4.png)

**System (please complete the following information):**
 - Operating System: 
 - Java Version:
 - Randomizer Version: 

**Additional context**

**Comment by tom-overton** [comment]
This error occurs because you have 32-bit Java installed. You can fix it by installing 64-bit Java. For more information, see [the Java section of our wiki](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java).

**Comment by RPZamer** [comment]
ok thanks, i though i had just updated it, so ill try again and do just that

**Comment by tom-overton** [comment]
Yeah, Oracle for whatever reason makes 64-bit Java annoyingly hard to get on Windows. You can run `java -version` in the command prompt; if it says "64-bit" in the response, then you're good.
