### ISSUE TITLE
Feature to make the type coverage similar to the original state.

### ISSUE THREAD

**Issue by Smaxtr** [Ajarmar/universal-pokemon-randomizer-zx#344]
I always found it odd that for example a find a random Aggron swimming on Water or fishing a Groudon which is almost a ton or fighting a water arena but the users there just use Fire Type.

Would it be possible to implement a checkmark while randomizing to keep the overall type of an Area or Arena or Trainers.

I like playing with the Random Aspects but it feels, odd, whenever there are heavy steel types in a supposing flying type arena.

**Comment by Ajarmar** [comment]
Sorry, we don't take feature requests.
