### ISSUE TITLE
Endless loading after selecting a ROM.

### ISSUE THREAD

**Issue by gabongo** [Ajarmar/universal-pokemon-randomizer-zx#345]
Trying to select a ROM of Ultra Sun leads to an endless loading screen. Using v4.2.1

![Capturar](https://user-images.githubusercontent.com/95833461/145317706-74be3de1-08ce-4e4f-bdb4-6cc6a014b59b.PNG)

**Comment by tom-overton** [comment]
Can you try again on the newly-released v4.3.0? https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases/tag/v4.3.0

**Comment by gabongo** [comment]
It worked! Thank you for your work.
