### ISSUE TITLE
[Bug]  So I am using the latest version of Java and I have the 4.2.1 version of the randomizer but it says, "The randomizer was not started via the launcher. You will not be able to load 3DS games into the randomizer." What should I do?

### ISSUE THREAD

**Issue by SN3AKE** [Ajarmar/universal-pokemon-randomizer-zx#346]
I have reset it many times and I have also redownloaded the launcher but that hasn't worked. Also the WINDOWS.bat script doesn't say anything.

**Comment by tom-overton** [comment]
You need to start the launcher by double-clicking on the launcher_WINDOWS.bat script to remove this error. When you double-click on the script, what happens?

**Comment by SN3AKE** [comment]
Oh, it worked. I didn't realize that I had to do that. Thanks!

**Comment by tom-overton** [comment]
You're welcome! Glad that it worked!
