### ISSUE TITLE
Horde battles

### ISSUE THREAD

**Issue by 18penguin** [Ajarmar/universal-pokemon-randomizer-zx#347]
I don’t know if this is the right place to ask this, but I’m wondering how does the randomizer work on Gen 6 hordes? The Pokémon itself is randomized but the hordes are all the same Pokémon. I’ve seen randomizers where hordes are more diverse. Is there any way to do this? 

 - Operating System: Windows 10 
 - Randomizer Version: whatever the most recent one is

**Comment by tom-overton** [comment]
Two questions:
- Are you using area-1-to-1 randomization?
- Are you playing on Omega Ruby or Alpha Sapphire? "Gen 6" is not specific enough

You can also just provide a log of your randomization, since that would answer both of these questions for you.

**Comment by 18penguin** [comment]
I’m playing ORAS using the totally random setting (not area or global 1-to-1)

**Comment by 18penguin** [comment]
Omega Ruby specifically

**Comment by tom-overton** [comment]
Yeah, that's what I figured. In Omega Ruby and Alpha Sapphire specifically, there's an absolute hard limit on the number of unique Pokemon species that can be on any given route. That number is specifically 18. If you exceed this limit, the game crashes as soon as you attempt to load the route.

As a consequence of this crashing behavior, for Omega Ruby and Alpha Sapphire only, our "totally random" setting actually *isn't* totally random; it's limiting itself to prevent a crash. There are a total of 15 horde "slots" for each route; three different rarities (common, uncommon, and rare) and five Pokemon per rarity. If each was filled with a unique Pokemon species, the route would only have room for three more species before it crashed.

If you've seen other randomizers have more diverse hordes, then you were probably looking at an XY or Gen 7 randomizer. ORAS imposes a strict limit on the number of unique species that makes it impossible for *any* randomizer to put more than 18 Pokemon on any given route.

**Comment by 18penguin** [comment]
I know this issue has been closed but there are some areas like certain caves where hordes are more diverse, like I’ve found a few cave encounters with 5 different Pokémon. I have found a few more diverse hordes in the grass as well.
