### ISSUE TITLE
[Help] How to Use .cxi File with Homebrewed 3DS

### ISSUE THREAD

**Issue by tymadey** [Ajarmar/universal-pokemon-randomizer-zx#348]
Hi, I am trying to randomize Pokemon Ultra Sun to then play it on my homebrewed 3ds (it's an old 3ds xl). 

I downloaded a .3ds rom of the game and decrypted it which gave me a .cci file. I then put it in the Randomizer ZX latest release and spit out a .cxi file.

How do I install the .cxi file on my homebrewed 3ds?

Before I have spit out the layeredfs file and loaded that into luma to patch Pokemon Sun because I have a catridge of that, but I do not have a cartridge of Ultra Sun so I went with the .cxi file. Am I able to install that onto my 3DS? 

My OS is Windows 10 and my release is the 4.2.1.

**Comment by tom-overton** [comment]
You cannot install a CXI onto a 3DS. You'll need a CIA of the game in order to install it. You cannot turn a CXI into a CIA because a CXI is lacking in information that a CIA has.

**Comment by I-Love-Technology** [comment]
Use FBI
