### ISSUE TITLE
[DPI Scaling] 'General Options' and 'ROM Information' sections are inaccessible

### ISSUE THREAD

**Issue by steelpenguins** [Ajarmar/universal-pokemon-randomizer-zx#35]
When I launch the randomiser the first sections are kinda crammed in at the top of the window, as seen below. This makes them inaccessible (can't click on the visible options or scroll up to reveal the others) and changing the window size doesn't seem to have any effect. Seems like it's probably an issue on my end, but any help troubleshooting would be appreciated.

<img width="454" alt="Screen Shot 2020-10-13 at 8 36 14 PM" src="https://user-images.githubusercontent.com/72786753/95831256-4e4eb000-0d95-11eb-8a59-8b7f6be89318.png">

**Comment by tom-overton** [comment]
Can you navigate to System Preferences ->Displays and show your resolution settings? I cannot reproduce this on a 15-inch MacBook Pro with the resolution set to "Default for Display"

<img width="1018" alt="Screen Shot 2020-10-14 at 1 40 35 AM" src="https://user-images.githubusercontent.com/12245827/95965218-84545a00-0dbe-11eb-824c-4f562f6ca373.png">

**Comment by erictheactivist** [comment]
Im also on a MacBook Pro and I am having the same issue

**Comment by steelpenguins** [comment]
<img width="661" alt="Screen Shot 2020-10-15 at 10 05 37 PM" src="https://user-images.githubusercontent.com/72786753/96102807-6e1bda80-0f33-11eb-8295-aea9e09c4b6a.png">

Yeah mine's on 'Default for Display' too. I'll upload a full screenshot of what the randomiser looks like for me in case that helps at all.

<img width="1014" alt="Screen Shot 2020-10-15 at 10 10 13 PM" src="https://user-images.githubusercontent.com/72786753/96102706-4e84b200-0f33-11eb-88ec-9b2561e6cddc.png">

**Comment by erictheactivist** [comment]
which resolution allowed it to work for u ?

**Comment by tom-overton** [comment]
Can you two provide me with three more pieces of information?
1. Under Apple Logo -> About Mac, what version of macOS are you running?
2. In the same About Mac section, what model of Mac does it list?
3. Open the Terminal and type "java -version". What does it report?

To give an example, here's what I'm running:
1. macOS Catalina, Version 10.15.7
2. Macbook Pro (16-inch, 2019)
3. openjdk version "1.8.0_242-release"
OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
OpenJDK 64-Bit Server VM (Build 25.242-b3-622259, mixed mode)

**Comment by steelpenguins** [comment]
1. MacOS Sierra, Version 10.12.6
2. Macbook Pro (Retina, 13-inch, mid-2014)
3. java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

My default display is listed as 1280 x 800, and the rightmost option (with which the randomiser works for me) has a listed resolution of 1680 x 1050. It also works at 1440 x 900.

**Comment by tom-overton** [comment]
Sorry for the nearly month-long delay, but I finally managed to test this on a high DPI screen myself. This isn't a Mac thing or a Java thing; this is 100% a DPI thing. In my own testing, the DPI scale needs to be *below* 180% if you want all options to be visible. In your example, you Macbook Pro has a resolution of 2560x1600, and when you run it at 1280x800, that's effectively a 200% scale. Running it at 1440x900 is a 177.77% scale, which is just enough that everything fits. I'm not really sure how to fix this, but I'll see if there's something fairly cheap we can do to make the UI play nice with high DPI screens.

**Comment by tom-overton** [comment]
After a long time, I finally have good news. As part of an unrelated commit (570bc0d59e3d9bb9dd3ef181f3e626296fa7c9de), Ajarmar fixed this issue. So in the next release of the randomizer, it will no longer be a problem.
