### ISSUE TITLE
[Help] Game Not Randomizing

### ISSUE THREAD

**Issue by JpTem** [Ajarmar/universal-pokemon-randomizer-zx#350]
The launcher works for me, and I've used UPR in the past before the launcher existed, and it randomized fine for gens 1-5. I know I have to use the windows launcher to randomize the game, and I have, but it just doesn't randomize at all. It's just the same game. I uninstalled and reinstalled both my emulator and the randomizer, nothing worked.

**Comment by tom-overton** [comment]
Are you talking about randomizing a 3DS game? If so, I'm fairly certain what's happening is that you have a game update installed in Citra or on your 3DS. See if you have something like "Ver 1.5" on the file select screen like this:

![image](https://user-images.githubusercontent.com/12245827/97775269-90f5e380-1b1c-11eb-98de-e482b1db036b.png)

If you have a game update installed in Citra or on your 3DS, you have two options:
1. Delete the game update. You can follow the instructions [here](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Randomizing-the-3DS-games#managing-game-updates-in-citra) to delete it
2. Load a CIA of the same game update inside the randomizer. You can follow the instructions [here](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Randomizing-the-3DS-games#3ds-game-updates) to load it

**Comment by JpTem** [comment]
ok, thank you! It was updated.
