### ISSUE TITLE
could not create java virtual machine [Help] 

### ISSUE THREAD

**Issue by benwebster0912** [Ajarmar/universal-pokemon-randomizer-zx#351]
**Describe your problem clearly:** 

**System (please fill in the following information):**
 - Operating System: 
 - Randomizer Version: 

**If your problem is that you can't randomize a game:**
If you get a popup saying that there has been an "unhandled exception", please attach the error log as an attached file to this issue.

**Comment by tom-overton** [comment]
Is the error "Invalid maximum heap size: -Xmx4096M"? If so, this indicates you have 32-bit Java, and you need 64-bit Java installed to use the launcher.

**Comment by benwebster0912** [comment]
Thank you for the reply

I have now sorted it and managed to get it working
