### ISSUE TITLE
Different files

### ISSUE THREAD

**Issue by drewlobel** [Ajarmar/universal-pokemon-randomizer-zx#353]
So I randomized pokemon SS and it gave a bunch of separate files instead of just 1 NDS file. Any way that I can compile them to just 1 NDS?

**Comment by tom-overton** [comment]
Are you looking at a folder that starts with "tmp"? This is a temporary folder that the randomizer uses. When you hit "Randomize (Save)", it lets you pick a location to write the output .nds file.
