### ISSUE TITLE
[Help] Wont randomize on Ultra Sun

### ISSUE THREAD

**Issue by Coqui1234** [Ajarmar/universal-pokemon-randomizer-zx#355]
I am attempting to randomize Ultra Sun, but nothing has been randomized. I created a titles folder in the luma folder and put the randomized update in it. I have enabled luma to download patches. I have ensured the versions match. Yet nothing works. Does anyone know what went wrong.

**Comment by tom-overton** [comment]
Could you try again with the newly-released v4.3.0? https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases/tag/v4.3.0
