### ISSUE TITLE
[Help] Is there a way to select certain abilities to be excluded from the randomiser?

### ISSUE THREAD

**Issue by Nopett** [Ajarmar/universal-pokemon-randomizer-zx#356]
I would like to randomise the abilities but remove certain ones (namely Imposter). Is there a way to do this?

**System (please fill in the following information):**
 - Operating System: WINDOWS
 - Randomizer Version: v4.2.1

**Comment by tom-overton** [comment]
No, there is no way to do this. If you have proficiency with programming, you can add Imposter to the list of useless abilities, which would thus remove it from the pool.
