### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by whatcorey** [Ajarmar/universal-pokemon-randomizer-zx#357]
**Describe the bug**
Crashing when saving settings
**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - Operating System: windows 10 pro
 - Java Version:
 - Randomizer Version: latest

**Additional context**
[error_2021-12-24-18-23-53.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/7775389/error_2021-12-24-18-23-53.txt)

**Comment by tom-overton** [comment]
This appears to be a romhack, based on the ROM Diagnostics. We do not support romhacks.
