### ISSUE TITLE
[Help] Installing Pokemon Black Randomiser on 3DS

### ISSUE THREAD

**Issue by lacvie** [Ajarmar/universal-pokemon-randomizer-zx#359]
I have been able to successfully install and play a pokemon y randomiser previously following this method ( https://www.youtube.com/watch?v=vN7l4gE0qgI ), though when I am downloading the randomised files for pokemon black I am getting a .nds file and do not know where to put it.

Previously, the randomiser for pokemon y downloaded as a layeredfs folder and I simply had to copy that into the titles folder in luma on the SD card, though I am pretty new to all of this and this same method does not seem to work with the black .nds file, and there is not an option to save the file as anything other than .nds. 

( https://3ds.hacks.guide/ ) this is the custom firmware I am currently using on my 3DS system, as well as the latest (v4.2.1) version of the randomiser, though I am unsure if there is any other firmware I should be using instead, or if there is another location that the .nds file should be moved to? Would appreciate the help :)

**Comment by tom-overton** [comment]
You either need a flashcart or something like [Twilight Menu](https://github.com/DS-Homebrew/TWiLightMenu) to run a DS game on your 3DS. Note that Twilight Menu can be *really* finicky with some of the DS Pokemon games due to antipiracy stuff, so be warned.
