### ISSUE TITLE
[Bug] Mega Rayquaza Gift Invalid Item ID

### ISSUE THREAD

**Issue by sora10pls** [Ajarmar/universal-pokemon-randomizer-zx#36]
If Swap Mega Evolvables is enabled with ORAS, your gift Latias/Latios may end up becoming Rayquaza with an invalid item. The program writes 0xFFFF for its Held Item, though that is obviously invalid, as the Max Item ID for ORAS is 775 (0x0307 - Eon Flute).

Rayquaza can only Mega Evolve after you've set a certain in-game flag (through progressing in the Delta Episode) in addition to Rayquaza having Dragon Ascent in its moveset. As such, including Rayquaza in the pool could lead to an unintended result.

If possible, giving it no Held Item, forcing one of its moves to be Dragon Ascent, and setting the required flag would be an ideal solution. Alternatively, you could also just remove it from the pool entirely.

**Comment by tom-overton** [comment]
Whoops, good catch. I'll take a look. I think removing Rayquaza from the pool makes the most sense because I think enemy trainers might not be able to Mega Evolve it either.

**Comment by RevanXVIV** [comment]
Wait does this mean mega rayquaza will be removed from the wild pokemon pool too or just the event pokemon pool?

**Comment by sora10pls** [comment]
@RevanXVIV - Specifically the Mega Evolution pool.

**Comment by RevanXVIV** [comment]
So then I'll still be able to find Mega Rayquaza in the wild then? I'm not really familiar with what constitutes the "Mega evolution pool"

**Comment by Ajarmar** [comment]
@RevanXVIV Yes, this concerns the "Swap Mega Evolvables" settings for Static/Trainer Pokemon specifically
