### ISSUE TITLE
[Help] Pokemon Y Not Randomizing

### ISSUE THREAD

**Issue by Sunspot17** [Ajarmar/universal-pokemon-randomizer-zx#360]
Yo! As title says, it's not randomizing and instead is still linked to the base Vanilla file. I'm using Citra Nightly for this, randomizer is v4.2.1. I've looked at solutions provided before, such as checking for updates and then uninstalling said updates, however I have no updates installed nor the ability to see the update location. 

So I don't think it's that. 

Attached is my log file, would really be appreciative of anyone's advice or help, cause I have no idea. 
[TrueY4.cxi.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/7783907/TrueY4.cxi.log)

**Comment by tom-overton** [comment]
Could you try again with the newly-released v4.3.0? https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases/tag/v4.3.0
