### ISSUE TITLE
While trying to randomize pokemon white 2, it says this file already exists and that it can not be randomized, when the file isn't randomized at all. 

### ISSUE THREAD

**Issue by Rolsafrair** [Ajarmar/universal-pokemon-randomizer-zx#363]
**Describe your problem clearly:** 

**System (please fill in the following information):**
 - Operating System: 
 - Randomizer Version: 

**If your problem is that you can't randomize a game:**
If you get a popup saying that there has been an "unhandled exception", please attach the error log as an attached file to this issue.

**Comment by tom-overton** [comment]
Did you try to save the randomized ROM over the original ROM? You can't do that with DS games.
