### ISSUE TITLE
[Bug] I cannot use "Additional Pokemon for..."

### ISSUE THREAD

**Issue by Antimatterzero** [Ajarmar/universal-pokemon-randomizer-zx#368]
**Describe the bug**
Hi, so I'm trying to use the "Additional Pokemon for..." feature of the randomizer and it is not working for me, when I enable it no matter for which trainers, I cannot increase the numbers (there isn't even anything in the box) or type into the box, I would really like to use this feature please help.

EDIT: Okay so the feature itself seems to work for me, its just that I cant SEE the numbers increasing (like when i use the up arrow, it doesn't show me a 2, 3, 4, etc)

**System (please complete the following information):**
 - Operating System: Window 10 64bit
 - Java Version: 
 java 17.0.1 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)

 - Randomizer Version:  4.2.1 (doesn't work on older versions either)
 - 
![Screenshot_177](https://user-images.githubusercontent.com/65208967/148671402-20ce42cc-9ac3-4162-9092-8ac13e91d698.png)

**Comment by tom-overton** [comment]
Does the newly-released v4.3.0 make any difference? https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases/tag/v4.3.0
I kind of doubt it will, but let's check just in case.

Also, you're the first person we've seen that's using Java 17. Do you know if it works on earlier versions of Java?

**Comment by Antimatterzero** [comment]
It didn't fix anything. I would rather avoid experimenting with early versions of Java because my experience with doing so is aggregating, either way as I said in the edit above, it worksm just doesnt visually display the count. I will just close the issue for the moment.
