### ISSUE TITLE
When i open the Universal randomizer it says :your java version is out of date: when my java version is the newest one can someone help me?

### ISSUE THREAD

**Issue by Maraxxxusz** [Ajarmar/universal-pokemon-randomizer-zx#369]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - Operating System: 
 - Java Version:
 - Randomizer Version: 

**Additional context**

**Comment by tom-overton** [comment]
Can you post a screenshot of the error you're seeing?
