### ISSUE TITLE
Forced Dragon Ascent in Delta Episode

### ISSUE THREAD

**Issue by P23CZ** [Ajarmar/universal-pokemon-randomizer-zx#37]
In ORAS Delta Episode, if the static Rayquaza is caught with a full party, it cannot be swapped out for another Pokemon immediately after being caught (I'm pretty sure you're aware of this issue already). This doesn't seem to cause any progression issues, but Zinnia will automatically teach Dragon Ascent to whatever the first Pokemon in your party is if Rayquaza isn't in the party, overwriting that Pokemon's fourth move.

**Comment by Ajarmar** [comment]
Thanks, but both of these are known issues - see https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Known-Issues

The first issue (being able to swap out one of your party Pokemon for Rayquaza) will be fixed in the next release (see ae4e1cddb47754d8dd2569d9018514e0d2047198)
