### ISSUE TITLE
Can't make new save files on Ultra Sun

### ISSUE THREAD

**Issue by Lloyd0202** [Ajarmar/universal-pokemon-randomizer-zx#370]
I have one run on Ultra Sun, and I want to start another one. Every time I make a new run with new settings on the randomizer, I go to open it and it launches my first run wherever I left off. How can I fix this issue?

**Comment by FrostedGeulleisia** [comment]
Simple, you just delete the old save file from within the game.
If you do want to keep it, use a tool like Checkpoint to dump it first.
The save file is bound to the actual cartridge or installed title, not the randomizer run.

**Comment by Lloyd0202** [comment]
Thank you for the information! As you might be able to tell, I'm rather new at this.
