### ISSUE TITLE
[Help] I can't save CXI file

### ISSUE THREAD

**Issue by ELITExECHO** [Ajarmar/universal-pokemon-randomizer-zx#371]
The randomizer (launched from launcher) will open the decrypted ultra sun file just fine, but once I try and save the CXI file the comand window will read Exception in thread "Thread-5" java.lang.OutOfMemoryError: Java heap space. Then a bunch of different lines that start with "at com". I figured this maybe the memory exception the launcher is supposed to deal with so i left it going but it will never complete it just continues to save without making the file. 
**System (please fill in the following information):**
 - Operating System: Windows 10
 - Randomizer Version: 4.2.1

**If your problem is that you can't randomize a game:**
If you get a popup saying that there has been an "unhandled exception", please attach the error log as an attached file to this issue.

**Comment by ELITExECHO** [comment]
Update I let it run for 24 hours and no dice

**Comment by tom-overton** [comment]
Can you try again on the newly-released v4.3.0? https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases/tag/v4.3.0

**Comment by ELITExECHO** [comment]
Will try thank you

**Comment by kochdennis** [comment]
i have the same problem. When i use the launcher it opens a command prompt that says: picked up _JAVA_OPTIONS: -2048M even though i have not changed anything in the Launcher.bat.

**Comment by tom-overton** [comment]
@kochdennis We have steps on the wiki to resolve that problem: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java#when-i-try-to-randomize-the-game-it-fails-and-i-see-something-like-picked-up-_java_options--xmx512m-in-the-terminal-window

**Comment by kochdennis** [comment]
> @kochdennis We have steps on the wiki to resolve that problem: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java#when-i-try-to-randomize-the-game-it-fails-and-i-see-something-like-picked-up-_java_options--xmx512m-in-the-terminal-window

ah thank you very much. i totally forgot i added this environment variable. it works now.

**Comment by ELITExECHO** [comment]
> Can you try again on the newly-released v4.3.0? https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases/tag/v4.3.0

I am still not getting it to save, its been about an hour i'll leave it going for another several hours and update this post

**Comment by tom-overton** [comment]
Alright, two things then:
1. When you loaded the ROM in 4.3.0, did it tell you the ROM wasn't clean?
2. What is the CMD prompt showing you right now? We added some logging in 4.3.0 specifically to help diagnose this case

**Comment by ELITExECHO** [comment]
> Alright, two things then:
> 
> 1. When you loaded the ROM in 4.3.0, did it tell you the ROM wasn't clean?
> 2. What is the CMD prompt showing you right now? We added some logging in 4.3.0 specifically to help diagnose this case

Alright so 1. There was no weird error or messages that popped up or showed on the CMD prompt. It reads that it was done reading romfs after loading a bunch of the parts of the file. 

2. Exception in thread "Thread-5" java.lang.OutOfMemoryError: Java heap space
        at com.dabomstew.pkrandom.ctr.GARCArchive.getBytes(GARCArchive.java:292)
        at com.dabomstew.pkrandom.romhandlers.Abstract3DSRomHandler.writeGARC(Abstract3DSRomHandler.java:185)
        at com.dabomstew.pkrandom.romhandlers.Gen7RomHandler.savingROM(Gen7RomHandler.java:706)
        at com.dabomstew.pkrandom.romhandlers.Abstract3DSRomHandler.saveRomFile(Abstract3DSRomHandler.java:90)
        at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:670)
        at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$performRandomization$112(NewRandomizerGUI.java:918)
        at com.dabomstew.pkrandom.newgui.NewRandomizerGUI$$Lambda$161/440553885.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
        
        It never stops after that ^^^. It will just continue to try and save forever. For reference I randomized Omega Ruby with 4.3.0 and it took about 2 mins.

**Comment by ELITExECHO** [comment]
> Great, thanks for the info. One other question: when you first run the launcher, before ever opening a ROM or anything like that, do you see a message in the CMD prompt like "picked up _JAVA_OPTIONS: -2048M" or something similar? The reason why you're saving forever is because the program ran out of memory, but in 4.3.0 we bumped the memory limit specifically to address this sort of thing. However, it can be overridden by your environment variables, which is what happened to @kochdennis and what I _believe_ is happening to you as well.

Picked up _JAVA_OPTIONS: -Xmx2G
thats what pops up when launching

**Comment by tom-overton** [comment]
Yep, you have the same issue as @kochdennis then. Follow along with the steps here to remove this environment variable: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java#when-i-try-to-randomize-the-game-it-fails-and-i-see-something-like-picked-up-_java_options--xmx512m-in-the-terminal-window

**Comment by ELITExECHO** [comment]
This did fix it thank you

**Comment by tom-overton** [comment]
Great, glad that worked!
