### ISSUE TITLE
[Bug] Fixed Impossible Evolutions Doesn't Change Abilities (Pokemon X)

### ISSUE THREAD

**Issue by pokegirl19** [Ajarmar/universal-pokemon-randomizer-zx#374]
I turned on "Fix Impossible Evolutions" for Pokemon X.  I caught a Haunter and it did level up and evolve to a Gengar, but it kept Haunter's Levitate ability.  I couldn't even fix it in PKHeX - Levitate was the only option under the "Ability" drop down.  Anyone know how to fix this?

**Comment by tom-overton** [comment]
There's no bug here; Gengar still has Levitate in Pokemon X.
