### ISSUE TITLE
Launcher is displaying a bug which i can't really find

### ISSUE THREAD

**Issue by Scrunchify** [Ajarmar/universal-pokemon-randomizer-zx#377]
![image](https://user-images.githubusercontent.com/94121217/150759772-bd563e57-8337-4dc9-b489-5803f49adcb2.png)

**Comment by Scrunchify** [comment]
Found the error you have to download java 64 Bit

**Comment by tom-overton** [comment]
Yep, this is indicating that you have 32-bit Java, @KidVulcan. You can download 64-bit Java and everything should work fine. Take a look at #221 to diagnose any other issues with the launcher that you might run into. Glad you figured it out, @Scrunchify !
