### ISSUE TITLE
[Contribution Idea]Type Randomization: Mono/Dual Type Only

### ISSUE THREAD

**Issue by Corruption-Echoes** [Ajarmar/universal-pokemon-randomizer-zx#378]
**Is your idea a new setting, a change to an existing setting, or something else? Please describe clearly:** 
This idea would be a new setting
**What problem would your contribution solve? Please describe:** 
Large numbers of pokemon being randomized to only Monotypings, and giving players more nuanced choices when randomizing
**Additional context:**
I believe this would be a good setting to add, as Dual types are fun! Currently learning the codebase to attempt to get this working myself, but Java isn't my main scripting language

**Comment by Corruption-Echoes** [comment]
Currently have it working in a brute force way, implementing it as a setting now.

**Comment by Corruption-Echoes** [comment]
Current progress:

Added to Settings.java dualTypeOnly added as a private boolean plus the following code
```
    public boolean isDualTypeOnly(){
        return dualTypeOnly;
    }
    public void setDualTypeOnly(boolean dualTypeOnly){
        this.dualTypeOnly=dualTypeOnly;
    }
```
Changed in AbstractRomHandler.java

||settings.isDualTypeOnly() added to lines 431, 438, 451, and 465 within the if statement

Currently digging through the UI code, but drowning slightly.

**Comment by Corruption-Echoes** [comment]
Success!
Feature is built, functional and integrated to the UI successfully.

**Comment by tom-overton** [comment]
Gonna close this one since it got merged. Thanks for the contribution!
