### ISSUE TITLE
Cant load the rom? 

### ISSUE THREAD

**Issue by SeifoMowafi05** [Ajarmar/universal-pokemon-randomizer-zx#38]
I’m trying to randomize ultra sun and when I load the rom, it just says “Loading” and is stuck on that. What should I do??

**Comment by tom-overton** [comment]
1. Did you launch the randomizer via launcher.jar?
2. Are you running 64-bit Java? You can check by running `java -version` in a command prompt

**Comment by tom-overton** [comment]
Closing since it's been a long time and I'm not sure the OP is coming back
