### ISSUE TITLE
[Help] eahc time I click on teh windows laucher it says it cant access pokemonwimodwsfile

### ISSUE THREAD

**Issue by Asminia** [Ajarmar/universal-pokemon-randomizer-zx#381]
![Screenshot (316)](https://user-images.githubusercontent.com/98427275/151058055-64236db4-b7e4-4bf5-ba4d-dd7011957703.png)

**Comment by Corruption-Echoes** [comment]
![image](https://user-images.githubusercontent.com/5022325/151065012-2db049ff-a7c8-4ef1-a16d-62db4b7328de.png)
Make sure both the jar file and bin file are together in the same folder, also check that the jar files name is "PokeRandozx.jar" as shown in this picture and noted in the command line output

**Comment by tom-overton** [comment]
One other problem might be the location of the randomizer; sometimes Windows permissions can cause issues with the launcher script. Try moving the randomizer to a different folder.
