### ISSUE TITLE
[HELP] Java Virtual Machine

### ISSUE THREAD

**Issue by HyperFrog21** [Ajarmar/universal-pokemon-randomizer-zx#383]
So when im starting the WINDOWS launcher it says:
ERROR: Could not create the Java Virtual Machine.
I dont know what that means and I would apreachiate some help with that.
Thanks!

 - Operating System: Windows 10
 - Randomizer Version: v4.2.1

**Comment by tom-overton** [comment]
Could you post the error message in full?

**Comment by macopp** [comment]
> 

![Uploading IMG_20220128_213410.jpg…]()

**Comment by tom-overton** [comment]
For whatever reason, that image didn't actually upload. Can you copy-paste the text instead?

**Comment by substance59** [comment]
Having the same issue: my command prompt reads:

"Invalid maximum heap size: -Xmx4608M
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Press any key to exit..."

I can still launch the ,jar file itself, but it won't let me load ROMs and it tells me once it launches.

**Comment by tom-overton** [comment]
@substance59 This error indicates that you have 32-bit Java installed. You need 64-bit Java installed to use the randomizer. For more information, see [the Java section of our wiki](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java)

**Comment by PigGamer1468** [comment]
> @substance59 This error indicates that you have 32-bit Java installed. You need 64-bit Java installed to use the randomizer. For more information, see [the Java section of our wiki](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java)

Gotten this exact same error, and installed the latest version of 64 bit Java although I was sure I had already had it installed. Issue doesn't seem to have been fixed. Also tried running in admin mode, no change. Is there anything else the error could mean?

**Comment by PigGamer1468** [comment]
Nevermind, for whatever reason I discovered that only the recommended version of 64 bit Java listed on your Java Wiki Section works instead of installing it from a different page on Java's website.

**Comment by tom-overton** [comment]
Gonna close this one since it's been open a while. Feel free to use #221 to diagnose launcher errors.
