### ISSUE TITLE
[Help] launching

### ISSUE THREAD

**Issue by macopp** [Ajarmar/universal-pokemon-randomizer-zx#384]
![IMG_20220128_213410](https://user-images.githubusercontent.com/98630044/151645777-3f14b8b9-b282-493d-8bec-531beb4ea6ad.jpg)

**Comment by tom-overton** [comment]
This error indicates that you have 32-bit Java installed; you need 64-bit Java in order to use the randomizer. For more info, see the [Java section of our wiki](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java).
