### ISSUE TITLE
[Help] 

### ISSUE THREAD

**Issue by teusflips** [Ajarmar/universal-pokemon-randomizer-zx#385]
**Describe your problem clearly:** 
When I attempt to Launch Launcher_WINDOWS.bat I keep having a screen that says "this app can't run on your PC, to find a version for your pc, check with the software publisher"
I can run the regular software fine but my computer seems to have a problem with the launcher, and I can't figure you what that message could mean.
**System (please fill in the following information):**
 - Operating System: Windows 11
 - Randomizer Version: V.4.3.0

**If your problem is that you can't randomize a game:**
If you get a popup saying that there has been an "unhandled exception", please attach the error log as an attached file to this issue.

**Comment by tom-overton** [comment]
Huh, we have never seen that message before either. One thing to try: does double-clicking on "PokeRandoZX.jar" work? If it does, it will complain that you didn't use the launcher, but that's totally fine; it at least proves that the randomizer itself works okay.

**Comment by teusflips** [comment]
> Huh, we have never seen that message before either. One thing to try: does double-clicking on "PokeRandoZX.jar" work? If it does, it will complain that you didn't use the launcher, but that's totally fine; it at least proves that the randomizer itself works okay.

This does work, however, I'm trying to randomize omega ruby and the software is telling me that I need to use the launcher. So I'm not entirely sure how to get omega ruby randomized now.

**Comment by tom-overton** [comment]
Yeah, that makes sense. I just wanted to make sure that your error *didn't* indicate some problem with Java; it sounds like Java is working fine on your machine. Can you try the following two things?
1) Can you right-click launcher_WINDOWS.bat and select "Run as Administrator"? I'm wondering if this error is indicating some sort of permissions issue, so maybe running it as an admin will make it work.
2) If you hold Shift and then right-click within the randomizer folder in Explorer, you should see an option like "Open PowerShell window here" or "Open Command Prompt here". Select that, and then run `java -Xmx4608M -jar PokeRandoZX.jar please-use-the-launcher`. Does that work?

**Comment by teusflips** [comment]
Okay, I just figured out what I did wrong, apologies as I didn't extract all the files properly.

**Comment by tom-overton** [comment]
Glad to see you got it working!
