### ISSUE TITLE
[Help] Megas without changed stats or types

### ISSUE THREAD

**Issue by Breakons** [Ajarmar/universal-pokemon-randomizer-zx#387]
When randomizing everything seems to work except for mega's typing and stats.

Found a primal groudon which should be ground fire that was taking super effective from ice moves, and did stat calcs and learned a mega abomasnow didnt have any stats raised.

Side note: some abilities SEEM to have stayed unrandomized but only on a handful of pokemon.

**System ryzen 7 2700x, 1070ti,:**
 - Operating System: windows 10
 - Randomizer Version: 4.3.0

**If your problem is that you can't randomize a game:**
If you get a popup saying that there has been an "unhandled exception", please attach the error log as an attached file to this issue.

**Comment by tom-overton** [comment]
Can you supply a log file demonstrating this problem?

**Comment by Breakons** [comment]
Are you referring to the one when generating the ROM or do you mean while actively running the game, sorry I don't exactly know how to get it when the game is actively running.

I can find it but I may need some direction

**Comment by tom-overton** [comment]
Yeah, the one that you can make when you generate the ROM.

**Comment by Breakons** [comment]
Alright I'll generate a new one with the same settings  [here[](url)](url
[TestFile.cxi.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/8029277/TestFile.cxi.log)
)

**Comment by tom-overton** [comment]
I can't seem to reproduce it. In this clip, you can clearly see that my ice attack is dealing neutral damage ![in this video](https://user-images.githubusercontent.com/12245827/153129399-0bba8fb9-af8e-4a38-a8f2-90312f1ec507.mp4). Additionally, your log indicates that Primal Groudon has the correct type
```
792|Groudon-P       |GROUND/FIRE      
```

Are you sure you aren't mistaken? This seems to be completely fine to me.

**Comment by Breakons** [comment]
Ohhhhhhhhhhh, I got them to check the encounter again, I think I might've just missed it and assumed it wasnt, sorry that's my bad, you're right and everything seems to work fine, Sorry if I took up your time thank you for assisting me.

**Comment by tom-overton** [comment]
No worries! I'm glad there ended up being no issues.
