### ISSUE TITLE
All the text is tiny?

### ISSUE THREAD

**Issue by Stardust3033** [Ajarmar/universal-pokemon-randomizer-zx#388]
when i open the program all the text is super tiny and nearly impossible to read. is there a scaling or zoom in option somewhere?

**Comment by tom-overton** [comment]
We don't have scaling/zoom options; it usually looks pretty sensible. Can you give us your OS, Java version, and screen resolution?

**Comment by tom-overton** [comment]
Gonna close this one since it's been quite a while with no response from the OP. Feel free to reply with that information if you want me to take a look, though.
