### ISSUE TITLE
Not randomizing the file, stuck for over an hour

### ISSUE THREAD

**Issue by Swift1304** [Ajarmar/universal-pokemon-randomizer-zx#39]
![ZXissue](https://user-images.githubusercontent.com/72012166/96331866-ae28ad80-1058-11eb-994b-cfa6ca1be0c3.JPG)

I can load in the rom fine, do the settings etc but when I click: randomize (save), it just gets stuck on this screen for over an hour?

What am I doing wrong?

**Comment by tom-overton** [comment]
1. Did you launch the randomizer via launcher.jar?
2. Are you running 64-bit Java? You can check by running `java -version` in a command prompt

**Comment by Swift1304** [comment]
I assumed I was, but then went and double checked and yeah it worked after I downloaded 64 bit java
