### ISSUE TITLE
[Help] Trade Evolution Change Not Working While Playing (R/B/Y)

### ISSUE THREAD

**Issue by antillies** [Ajarmar/universal-pokemon-randomizer-zx#390]
Hi, I'm having an issue where a changed trade evolution (Graveler) is not evolving once reaching level 37.

I should note:
- The ROM I modified is Pokemon Red
- I'm playing on an existing save file
- I load the Red Anniversary patch

The randomizer works just fine.  I checked the "impossible evolutions" checkbox and nothing else and then chose "Randomize (Save)" to export the ROM.  Everything in-game runs just fine but I recently leveled my Graveler from level 36 to 37 and it did not evolve.  Is there something I am doing wrong on the export step?  Or is it perhaps because I'm running a patch on top of the ROM?

Any help would be very much appreciated.

**System:**
 - The randomizer version I used was the most recent release as of today, 1.7.2.
 - The system I used the randomizer on was Windows 10, 64-bit, but I'm actually playing the ROM on Linux Mint.

**Comment by tom-overton** [comment]
Hey, I'm not sure if you noticed, but this is Universal Pokemon Randomizer ZX, not the original Universal Pokemon Randomizer. The most recent release as of today is not 1.7.2, but actually [4.3.0](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases/tag/v4.3.0).

Even still, I'm skeptical that this scenario would work. Existing romhacks frequently work very poorly with the randomizer due the randomizer being a bit "dumb" about how it finds things in the ROM. It's bad enough that we don't officially support romhacks in any way, so I'm going to close this issue. However, I would encourage you to try with 4.3.0 too, just in the off-chance it works. If it still doesn't work, then you'll likely have to just randomize the original Pokemon Red.
