### ISSUE TITLE
I have multiple ideas to share from my playtest of all generation.

### ISSUE THREAD

**Issue by dragonfang93** [Ajarmar/universal-pokemon-randomizer-zx#392]
### **New setting - For Gen 1-4, when you are gifted or picking up a TM, you get a selected amount. Also, the Selling price of the TM will be divided by the selected amount.** 

- The selected amount would be a drop down field with options like 5, 10, 50. 
- This will solve the limited TM in the older game and with the price nerf, TM would not be a tactic to farm money. 

### **New setting - For Generation 5 and ORAS games, add an option to buff the spawn rate of shaking grass (gen 5), Hidden Grotto (B2W2), Dex NAV (gen 6).**

- This option increases the rate of shaking grass/ splashing water/ dust cloud and dexNAV appearance. 
- For the Hidden Grotto specifically, guarantee a Pokémon encounter.
- Can be added in wild Pokémon or Misc. section. 
- Hidden Grotto are usually empty or have a useless item for the day.
- Also, another buff that can be added is to guarantee for those Pokémon encounters to have their Dream World/Hidden Ability. 

### **New setting - in the Misc. section, add Easy egg hatch.**

- All egg have Magikarp hatch step rate.
- This would make egg hatch/breeding much easier.

### **New setting - in the Misc. section, add nerf Crit damage for older games (gen 1 to 5).**

- In generation 6, crit damage was reduced to 1.5x from 2x. This new setting will modernize the game mechanic for the older Pokémon game.

### **New setting - in the Misc. section, add buff Crit damage for newer games (gen 6 to 8).**	

- In generation 6, crit damage was reduced to 1.5x from 2x. This will revert the game mechanic to the original crit rate.	

### **Contribute to an existing Idea - In the Pokémon Ability section, have a checkbox to guarantee all Pokémon have 3 abilities.** 

- This gives trainers more variety to use a certain Pokémon. This also “fills the space” after seeing a lot of white spaces in the log generated after randomizing a game. Personally, seeing a basic stage Pokémon having 2 abilities and its evolution having only 1 (not counting the hidden ability) seemed weird to me. 
- The ability capsule can be useable on every Pokémon 

### **Contribute to an existing Idea - when randomizing Pokémon type, have a checkbox to balance type distribution so all types will be fairly distributed.**

- This option will balance the type distribution in game 
- I don't know if it was already coded in and I had a bad RNG but I played a Leaf Green randomizer with so many rock, grass and normal types.

### **Contribute to an existing Idea - For the wild Pokémon section, Have a checkbox rearrange encounters table based on BST: Higher BST will have a lower encounter rate.** 

- For example the old rod has a 70% and 30% encounter rate. Weedle would be the 70% while Mewtwo would be the 30%. 
- This might not be a popular option and it would be similar to the Similar Strength option for some areas but this option can be applied with the catch’em all option to rearrange the encounter.

### **Contribute to an existing Idea -In the Item section, option to reduce Shop buying and selling price by moving the decimal 1 slot to the left: ( effectively 90% off) or it can be x% based.** 

- For example, a Pokeball would cost 20 instead of 200. 
- If you cannot do all items, you can just apply it to the main mart items or just reduce the Pokeball (and the different ball type) price. This can also be applied to TM in gen 1-4 since these generations do not have unlimited TM use.

### **Contribute to an existing Idea - For the Move data section, randomize the chance of the damaging moves secondary effect. 

- It is another value that can be randomized to hax someone or get haxed.**  
- If this option is added, another option may be to cap the max damaging moves secondary effect chance to 30% so this would not get out of hand, like ice beam can freeze 80% every time.

### **Contribute to an existing Idea - For the Move data section, randomize damaging moves secondary effect.** 

- You can group secondary effect into 2 categories: 
       - Stats ( move the changes Attack, Defense, S. Attack, S. Defense, Speed, Accuracy, or Evasion)
       - Status ( move that inflict Burn, Paralyze, Poison, Badly Poison, Freeze, Confused, Infatuated, Trapped, Flinch or Drowzee)
- There are multiple ways to randomize this option:
       - Same strength: Similar to totem aura - same strength, secondary effect will be at the same value but change the secondary effect. Example: Discharge can burn or Overheat can -2 in Attack.
       - Shuffle: Have the same pool of secondary effects but rearrange within the category.  
       - Completely - Secondary effects are not limited to a category. Example: Overheat giving you a +1 in every stat (like Silver Wind), Scald is a guaranteed paralyze (like Zap Cannon) or Thunder dropping your Sp. Attack by 2 stages (like Overheat). 
- This would be a lot of work like editing text of the move and tm to reflect the changes.

- ### **Contribute to an existing Idea -  Lastly, for the Move data section, for status move, randomize the status, stat buff, or debuff. Similar to the Secondary effect but with non damaging moves**
- Again, you can group Status move into 3 categories and 1 and 2 move could be randomize: 
       - Buff/ Debuff Stats which change Attack, Defense, S. Attack, S. Defense, Speed, Accuracy, Evasion, and crit rate of your Pokémon, your allies or the opponent.
       - Inflict Status ailment to receivers like Burn, Paralyze, Poison, Badly Poison, Freeze, Confused, Infatuated, Trapped, Drowse.
       - Cannot be randomize yet due to the the move unique effect: Change type, ability, item usage, weather, terrain, hazard, protection, recovery, Destiny bond,
- There are multiple ways to randomize this option:
       - Same strength: Similar to totem aura - same strength, secondary effect will  be at the same value but change the Status. Example: Yawn can burn, Leer can -1 in Accuracy, or Calm Mind will give you +1 in Sp. Defense and Speed
       - Shuffle: Have the same pool of Status effects but rearrange within a category.  
       - Completely - Status effects are not limited to a category. Example: Bulk Up gives you a +2 in every stat, Growl is a guaranteed paralyze (like thunder Wave) or Screech can badly poison (like Toxic). 
- Again, this would be a lot of work like editing text of the move and tm to reflect the changes.

### **New setting - For Generation 2-5, can the “???” type be coded to have the property as Fairy type?**
- This might be a stretch but if possible, the Fairy type can be added to the previous generation. This will modernize the older games.

I hope this was clear to process

**Comment by tom-overton** [comment]
I'm not 100% sure if we're on the same page as to the meaning of "Contribution Idea". We want people to use that tag to let us know about code they're interested in adding to the randomizer. Are you planning on contributing code for all of this yourself? If so, that would be an incredible feat!

**Comment by dragonfang93** [comment]
Thank you for explaining... please disregard this post and feel free to remove.
I will try something and post something later on.
