### ISSUE TITLE
[Help] Is there a way to pull a randomized file seed after creation and closing window?

### ISSUE THREAD

**Issue by Saultyn** [Ajarmar/universal-pokemon-randomizer-zx#395]
Describe your problem clearly:
No massive issue, but regret not creating a randomization log to note where to find specific mon's. Tried to run the file through the randomizer again with no changes and log only marked all areas as "unchanged". As far as I can tell I'd have to pull the file seed and input in the randomizer to create a log from there but can't seem to find a method to do so, if it exists.

System:
 - Operating System: Windows 10
 - Randomizer Version: 4.2.1

**Comment by tom-overton** [comment]
Unfortunately, there's no way to do this. This is sort of intentional to prevent cheating; if you're racing with someone, we don't want you to be able to pull the log out from the seed they sent you in order to cheat.
