### ISSUE TITLE
Idk if this is an option but can I change the shiny rate on this randomizer[Help] 

### ISSUE THREAD

**Issue by Chriso196** [Ajarmar/universal-pokemon-randomizer-zx#396]
**Describe your problem clearly:** 

**System (please fill in the following information):**
 - Operating System: 
 - Randomizer Version: 

**If your problem is that you can't randomize a game:**
If you get a popup saying that there has been an "unhandled exception", please attach the error log as an attached file to this issue.

**Comment by RevanXVIV** [comment]
No you cannot change the shiny rate with UPR, maybe some day, but I seriously doubt it'll ever happen.

**Comment by tom-overton** [comment]
Yeah, no option for this exists at the moment. This is actually a really hard thing to do, especially across all the dozens of Pokemon games we support. I also seriously doubt it will ever happen.
