### ISSUE TITLE
[Bug] "Could not create the Java Virtual Machine."

### ISSUE THREAD

**Issue by DragonARandom** [Ajarmar/universal-pokemon-randomizer-zx#397]
Whenever I try to use the launcher for the randomizer, it comes up with two errors, which are within the screenshot provided. I am using the latest released on both the randomizer and Java. 

![Screenshot 2022-02-20 143500](https://user-images.githubusercontent.com/86082791/154863340-4d27e5c0-e3d4-41ec-aa01-fca3f3fe7024.png)

**Comment by tom-overton** [comment]
This error indicates that you have 32-bit Java installed. You need 64-bit Java installed to use the randomizer. For more information, check out the [Java section of our wiki](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java).
