### ISSUE TITLE
[Bug] ORAS Randomization bug 4.3.0

### ISSUE THREAD

**Issue by RevanXVIV** [Ajarmar/universal-pokemon-randomizer-zx#398]
**Describe the bug**
Ok so this one seems pretty simple I play on a modded 2DS, Alpha Sapphire runs fine on version 4.2.0 even with all the modded stuff I added, however Omega Ruby on 4.3.0 seems to crash when I dashboard in the middle of a pokemon battle. This isn't a massive issue for me, but I figured I'd better report it anyway.

**To Reproduce**
1. Load up the ORAS Randomizer on my 2DS
2. Enter a Wild Battle
3. Hit the "home" button whilst in battle
4. Game crash

**Expected behavior**
I expected it to be able to take me to the home menu. It's late here so once I finish my current Alpha Sapphire run I'm gonna try a new run with that. Like I said before this problem isn't massive but it can get annoying.

**Screenshots**

**System (please complete the following information):**
 - Operating System: 2DS
 - Game: ORAS
 - Randomizer Version: 4.3.0

**Additional context**
I don't know if anyone else is aware of this issue, but I hope me bringing it up helps a fix show up down the line.

**Comment by tom-overton** [comment]
Could you provide a log for a seed that crashes your 2DS like this? I want to make sure I can replicate the conditions as closely as possible.

**Comment by RevanXVIV** [comment]
Do you mean a log of my randomization like the spoiler log?

**Comment by tom-overton** [comment]
Yeah, that's what I mean. The spoiler log that the randomizer prompts you to create when the seed is generated.

**Comment by RevanXVIV** [comment]
[Seed 1.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/8120943/Seed.1.log)


That's the spoiler log for my current seed.

**Comment by tom-overton** [comment]
I tried this on my own 3DS with a capture card and I could not replicate the issue:

https://user-images.githubusercontent.com/12245827/155260358-0cc01caf-1e0c-4757-afb4-e8dd42bed9e9.mp4

It definitely can take a while to enter the Home menu, but this was true of the unrandomized ORAS as well. Just to double check:
- How are you running the mod on your 3DS? Via luma's layeredFS?
- Do you have any other mods running alongside this? Or *just* the randomized files?
- Do you happen to have a European copy of Omega Ruby? These are well-known for having many defects

**Comment by RevanXVIV** [comment]
- Yes running on an old Modded 2DS layeredFS setup
- Yes a custom shiny garc file and some custom music files
- No, it was extracted from my US Cartridge.

**Comment by tom-overton** [comment]
Can you remove all of your own mods and try again? We don't (and more accurately, simply can't) support all the various romhacks that exist in the world, so I want to make sure that the randomizer, with no mods enabled, works properly.

**Comment by RevanXVIV** [comment]
I can make a randomizer seed as a test and try it some time next week. I've been busy running errands this week and won't have much time to do so.

**Comment by tom-overton** [comment]
Gonna close this one due to inactivity.
