### ISSUE TITLE
[Bug] ORAS Randomized evolutions per level bug

### ISSUE THREAD

**Issue by RevanXVIV** [Ajarmar/universal-pokemon-randomizer-zx#399]
Ok so with the same seed spoiler I linked on my other bug report regarding a 2DS crash, I also had Force change enabled for the "pokemon randomly evolves every level" but they constantly seem to get put into an infinite loop I've already had 5 mons eventually get to the point where they just loop between the same 3-6 evolutions.

**Comment by tom-overton** [comment]
There is no logic in place to prevent such a loop, nor is there any way to guarantee that there *isn't* a loop with certain settings, so there is no bug here.
