### ISSUE TITLE
Wild Pokemon Level Slider and Trainer Level Slider

### ISSUE THREAD

**Issue by Moonbeam111** [Ajarmar/universal-pokemon-randomizer-zx#4]
Is there a fix where I can change trainer & wild pokemon levels without randomizing anything? I think that would be a good option to include but I'm not well versed enough in java to figure out how to do it myself.

**Comment by Ajarmar** [comment]
This is a good suggestion. Fixed in commit 83541c447fc399f78388546830e9648660d3cd0d, will be included in the next release.
