### ISSUE TITLE
Gen II NullPointerException

### ISSUE THREAD

**Issue by FeatherHeart** [Ajarmar/universal-pokemon-randomizer-zx#40]
I get a NullPointerException when using the Update Base Stats option for Pokemon Silver (U), Pokemon Gold (U), and Pokemon Crystal (U 1.1).
[error_2020-10-17-12-54-37-PC11UBS8.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5396077/error_2020-10-17-12-54-37-PC11UBS8.txt)
[error_2020-10-17-12-55-16-PGUBS6.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5396078/error_2020-10-17-12-55-16-PGUBS6.txt)
[error_2020-10-17-12-55-44-PGUBS7.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5396079/error_2020-10-17-12-55-44-PGUBS7.txt)
[error_2020-10-17-12-56-18-PGUBS8.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5396080/error_2020-10-17-12-56-18-PGUBS8.txt)
[error_2020-10-17-12-56-46-PSUBS6.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5396081/error_2020-10-17-12-56-46-PSUBS6.txt)
[error_2020-10-17-12-57-17-PSUBS7.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5396082/error_2020-10-17-12-57-17-PSUBS7.txt)
[error_2020-10-17-12-57-51-PSUBS8.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5396083/error_2020-10-17-12-57-51-PSUBS8.txt)
[error_2020-10-17-12-52-48-PC11UBS6.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5396084/error_2020-10-17-12-52-48-PC11UBS6.txt)
[error_2020-10-17-12-53-47-PC11UBS7.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5396085/error_2020-10-17-12-53-47-PC11UBS7.txt)

**Comment by Ajarmar** [comment]
Thanks - this was already pointed out to me elsewhere and was fixed in 97b02ea610c4df7961254d9d92c26c661d585321, will be included in the next release
