### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by JkHowling** [Ajarmar/universal-pokemon-randomizer-zx#401]
Selecting "Forced Challenge Mode" for black 2/white 2 doesn't base te randomizer settings off such mode.

This is important for settings such as giving bosses additional pokemon, or adjusting the level scale. You'd expect giving a +10% boost with Challenge Mode enabled to base that boost off the Challenge Mode levels (ie: Chharen's ace is 14 in Challenge Mode, so it'd be 15 with a 10% boost). Instead, it bases it off Normal Mode (his ace is 13, which gets boosted to 14, basing the boost off normal mode's level.) Another example is we gave gym leaders +1 pokemon to their teams, assuming it'd be based off the Challenge Mode settings (where Cheren has 3 Pokemon total, thus bringing him to 4.) Instead he just has 3.

This makes Forced Challenge Mode practically worthless in terms of randomization. It doesn't seem intentional given there's nothing in the program itself mentioning it. If it is intended, please add a note when hovering over the option stating that randomization settings are based off Normal Mode's settings, not Challenge Mode's.

**Comment by tom-overton** [comment]
Thanks for the report. The problem is *not* that the randomizer wasn't basing its settings off Challenge Mode, the problem was that Force Challenge Mode didn't work at all! That has since been fixed.
