### ISSUE TITLE
Frost Breath is 45bp, but Storm Throw is 60?[Bug] 

### ISSUE THREAD

**Issue by JkHowling** [Ajarmar/universal-pokemon-randomizer-zx#403]
Applying the setting to update moves to gen 7 on an Unovan game makes Frost Breath 45bp rather than 60bp.
On the other hand, with the same option toggled, Storm Throw (which is identical in concept- it always crits) DOES get updated to 60bp.

I'm unsure which is the bug here- Frost Breath being 45bp (or 90 after crit, which is on par with gen 7's crit nerf) or Storm Throw being 60bp (which makes it effective 120bp, due to 2x crits). But one of them is incorrect. 

![Frost Breath](https://user-images.githubusercontent.com/26156840/156861724-1a001d4b-e06d-43a7-9489-d070cc8c32a2.png)
![Storm Throw](https://user-images.githubusercontent.com/26156840/156861725-5f336ea9-c6e7-4278-8ae5-dbc6b7aa58a7.png)

**Comment by tom-overton** [comment]
Thanks, it's fixed now and will be in the next release. I think there was just a bit of confusion because Storm Throw *also* got its BP updated from 40 -> 60 starting in Gen 6; we were doing that, but not accounting for the extra crit damage like we were with Frost Breath.
