### ISSUE TITLE
help me fix the bug please

### ISSUE THREAD

**Issue by nick123122e** [Ajarmar/universal-pokemon-randomizer-zx#404]
the universal randomizer says: the randomizer was not started via the launcher. You will not be able to load 3ds games in randomizer

*

: 
 - Java Version: i open universal pokemon randomizer  file with java
 : 

.

**Comment by tom-overton** [comment]
Did you start the randomizer by double-clicking on launcher_WINDOWS.bat (or the equivalent for your operating system)?

**Comment by sprite9906** [comment]
i have the same issue. This is the error message i get 
![image](https://user-images.githubusercontent.com/101961906/159148778-b7713109-965b-4e8b-b364-8423073a9824.png)

**Comment by sprite9906** [comment]
i fixed it just had to have the latest java version

**Comment by tom-overton** [comment]
Yeah, that error indicates you had 32-bit Java installed. But when you installed 64-bit, it fixed it.
