### ISSUE TITLE
Randomize(Save) CXI Long Saving Time?

### ISSUE THREAD

**Issue by aansari9** [Ajarmar/universal-pokemon-randomizer-zx#41]
How long is it supposed to take? It's been an hour and this hasn't saved yet.
![Capture](https://user-images.githubusercontent.com/70219656/96354885-a80eed00-10a9-11eb-9752-0f8b702ec737.PNG)

**Comment by tom-overton** [comment]
1. Did you launch the randomizer via launcher.jar?
2. Are you running 64-bit Java? You can check by running `java -version` in a command prompt

**Comment by aansari9** [comment]
It's working now thanks for the help!
