### ISSUE TITLE
[Help] 

### ISSUE THREAD

**Issue by Paps696969** [Ajarmar/universal-pokemon-randomizer-zx#412]
When I try to Open my windows launcher, it says:
Error: opening registry key 'Software\JavaSoft\Java Runtime Environment'
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment.
Press any key to exit... 

**System:**
 - Operating System: Windows 11 Version 21H2 
 - Randomizer Version: 4.4.0

![2022-04-01 (53)](https://user-images.githubusercontent.com/102828001/161324418-b785e281-39d1-4fde-90c0-0bca6edbd804.png)

**Comment by voidchaos23243** [comment]
you do not have java 64 bit installed

**Comment by Paps696969** [comment]
(Disclaimer:I do have java installed, have searched for the files and found them)

**Comment by Paps696969** [comment]
> you do not have java 64 bit installed i think

Except i do

**Comment by tom-overton** [comment]
Try doing this for me:
- Open a command prompt (click Start, then type "cmd.exe" and press Enter)
- Type `java -version` in the command prompt and press Enter.

What happens? If you get the same error about not being able to find java.dll, then even if you *think* you have Java installed, your installation is still broken, and the easiest way to fix it is just to uninstall and reinstall it.

**Comment by Paps696969** [comment]
> Try doing this for me:
> - Open a command prompt (click Start, then type "cmd.exe" and press Enter)
> - Type `java -version` in the command prompt and press Enter.
> 
> What happens? If you get the same error about not being able to find java.dll, then even if you *think* you have Java installed, your installation is still broken, and the easiest way to fix it is just to uninstall and reinstall it.

Hi! I did and it work, also on system variable for path I had to add the path to my bin. I have another problem: now, if I write java -version in my cmd.exe all works, but if I try to open the launcher, it says it couldn't create java virtual machine

**Comment by tom-overton** [comment]
Does it say something like "Invalid initial heap size" when it says that it couldn't create the Java Virtual Machine? If so, then that indicates you have 32-bit Java installed, whereas you need 64-bit Java to use the randomizer. We have a [Java page](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java) on our wiki that goes into more detail.
