### ISSUE TITLE
[Help] When attempting to open a 3ds rom, i am left with a loading screen that does not end. 

### ISSUE THREAD

**Issue by winreg** [Ajarmar/universal-pokemon-randomizer-zx#417]
When i try to open the rom on the ui to randomize the save it just leaves me on a loading screen that is indefinite . I've tried many ways to fix it for an hour with no luck.

**System (please fill in the following information):**
 - Operating System: Windows 10
 - Randomizer Version: Latest 4.4

**Comment by tom-overton** [comment]
What does the command prompt look like when it's stuck like that?
