### ISSUE TITLE
[Contribution Idea] Additional BadItems in FRLG

### ISSUE THREAD

**Issue by ljmcdonald86** [Ajarmar/universal-pokemon-randomizer-zx#420]
**Is your idea a new setting, a change to an existing setting, or something else? Please describe clearly:**
A change to an existing setting -> Field Item setting 'Ban Bad Items'. Rom specific change for removing Shards, Flutes, and Shoal items from FRLG.

**What problem would your contribution solve? Please describe:**
These items are relevant in other Gen 3 roms but are useless in FRLG. I frequently run randos in FRLG with random field items, and these are quite common, as there are 11 items total between them. The expectation with Ban Bad Items on would be that all items found would have some use in the game.

**Comment by Ajarmar** [comment]
Sure, this sounds like a good idea. That said, the flutes function the same in FRLG as they do in RSE, so they are actually useful and shouldn't be counted as bad items. Shards and Shoal items sound reasonable to call bad items in FRLG though.

**Comment by tom-overton** [comment]
Hey, it's been a month since this was posted. Do you need any help implementing this?

**Comment by tom-overton** [comment]
I don't know where the OP went, so I just implemented it myself in 460d0fc57d62d4cf712993fd7141de15c8be36ca
Therefore, I'm going to close this. OP, if you were interested in implementing this, sorry!
