### ISSUE TITLE
[Help] Can I dont know how to open the randomizer for 3ds games please help.

### ISSUE THREAD

**Issue by Kakashi5777** [Ajarmar/universal-pokemon-randomizer-zx#421]
**Describe your problem clearly:** 

**System (please fill in the following information):**
 - Operating System: 
 - Randomizer Version: 

**If your problem is that you can't randomize a game:**
If you get a popup saying that there has been an "unhandled exception", please attach the error log as an attached file to this issue.

**Comment by tom-overton** [comment]
Just launch the randomizer using the launcher. It's called launcher_XXX, where the XXX you want to use depends on your operating system.
