### ISSUE TITLE
[Contribution Idea] Guarantee Secondary Ability

### ISSUE THREAD

**Issue by Frozeh** [Ajarmar/universal-pokemon-randomizer-zx#422]
Hi,

I love this software and I am so happy to see how much of an improvement this software is compared to the old randomizer and seeing the community effort in continuing with QoL updates. I have played a ton of different Pokémon games in different randomizer settings using ZX.

**Is your idea a new setting, a change to an existing setting, or something else? Please describe clearly:**
I was wondering if a "Guarantee Secondary Ability" option in Pokémon Abilities would be possible as it makes for more interesting variations in randomization.

**What problem would your contribution solve? Please describe:**
Something I have noticed while using Ability Capsules is that there seems to be a lack of a secondary ability on many randomized Pokémon. I think adding a "Guarantee Secondary Ability" option for all Pokémon would be a great addition to the randomizer.

Best regards,
Frozeh

**Comment by tom-overton** [comment]
Sure, this sounds like a good idea. If you have any questions while implementing this, just let us know and we'll be happy to answer.

**Comment by tom-overton** [comment]
Hey, it's been a month since this was posted. Do you need any help implementing this?

**Comment by Frozeh** [comment]
I misunderstood a bit, it was more of a suggestion, not sure how to implement it, would appreciate some help. Thank you in advance.
