### ISSUE TITLE
[Bug] Evolution Loop on Omega Ruby Randomized

### ISSUE THREAD

**Issue by AgentK7** [Ajarmar/universal-pokemon-randomizer-zx#423]
**Describe the bug**
When i get an Evolution to Drifblim (from Makuhita) i am catched in a never ending loop, because in Randomizing Logs 
on Evolutions there is 
Makuhita        -> Drifblim       
Drifblim        -> Makuhita 

To be fair, i dont know if thats an one off or a bug 

**Expected behavior**
Not catched in an Evolution Loop between the two same Pokemon 

**System (please complete the following information):**
 - Operating System: MacOS Monterey
 - Java Version: 8u321
 - Randomizer Version: 4.4.0

**Additional context**
At first i thought its an one off but after three or so loops i am now thinking i have cought a bug here.

Randomizer Version: 4.4.0
Random Seed: 71833311012473
Settings String: 318AAIEAQL7AP4AAQEEAAIeJAAEFAAAFAABAQCAAAAAAAAAAACIMgEyAQAICTIHBwAyAAESUG9rZW1vbiBPbWVnYSBSdWJ5ZJlyvuPDOIo=

**Comment by AgentK7** [comment]
Randomizer Log https://controlc.com/18d0e538

**Comment by tom-overton** [comment]
This is entirely normal. When evolve every level is on, it is impossible to avoid evolution loops, so we do absolutely nothing to prevent them from occurring. You managed to find a particularly unfortunate case where the loop is very short, but it's still expected to see something like this.

**Comment by AgentK7** [comment]
Thanks for explaination, was really weird that i directly Level 6 started to loop
