### ISSUE TITLE
[Bug] Give national dex at start not working in white/black

### ISSUE THREAD

**Issue by Fuzzy2319** [Ajarmar/universal-pokemon-randomizer-zx#424]
**Describe the bug**
Give national dex at start not working in white/black

**To Reproduce**
1. Go to Misc. Tweaks
2. Click on Give national dex at start
3. Randomize the game

**Expected behavior**
When you open the pokedex you have to see the national dex but you actually see the regional dex 

**Screenshots**
![image](https://user-images.githubusercontent.com/61144247/165383782-9ed69f84-7755-49ac-8a0b-6368adf438d7.png)

**System (please complete the following information):**
 - Randomizer Version: 4.4.0

**Comment by tom-overton** [comment]
You have the National Dex. Just press Select.
