### ISSUE TITLE
Launcher Error

### ISSUE THREAD

**Issue by DarkStarX0829** [Ajarmar/universal-pokemon-randomizer-zx#425]
so when i launch the windows launcher, it does pop up, but it then has the following message:

Invalid maximum heap size: -Xmx4608M
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Press any key to exit...

does this have to do with storage space, or something to do with my laptop? i do have the latest version of java installed, and the latest windows 10 version installed, so idk what's happening here. i'm using pokerandozx4.4.0, and it won't allow me to randomize 3DS games of any kind

**Comment by tom-overton** [comment]
You need 64-bit Java. That error indicates 32-bit Java is installed instead. Please see the [Java section](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java) of our wiki for more info.
