### ISSUE TITLE
[Help] Pokemon Soulsilver

### ISSUE THREAD

**Issue by diligentnotetaking** [Ajarmar/universal-pokemon-randomizer-zx#432]
**Describe your problem clearly:** 
Manually added an AP Patch of a rom dumped from my actual cartridge. Tried to randomize, got this error spat out at me.

**System (please fill in the following information):**
 - Operating System: Windows 10
 - Randomizer Version: 1.7.2

**If your problem is that you can't randomize a game:**
If you get a popup saying that there has been an "unhandled exception", please attach the error log as an attached file to this issue.
[error_2022-05-09-13-36-25.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/8651713/error_2022-05-09-13-36-25.txt)

**Comment by tom-overton** [comment]
We don't support romhacks, and that includes those that have been AP patched. If you need to apply an AP patch, you need to do so after randomization. I should also note that I'm surprised you're AP patching at all, considering that almost nothing these days actually requires it to be AP patched.

**Comment by diligentnotetaking** [comment]
Isn't a romhack, just a standard rom. The AP patch was apparently supposed to stop the red screen bug in loading screens when playing on 3DS, but nothing seemed compatible. Guess I'll just have to figure out a fix on my own.
