### ISSUE TITLE
[Bug] TM in platinum

### ISSUE THREAD

**Issue by Baat01** [Ajarmar/universal-pokemon-randomizer-zx#436]
**Describe the bug**
while not randomizing the tms nor their locations(I only put "Full HM compatibility" in the tm/hm menu), it appears that some tms are changed with other

**To Reproduce**
randomize a rom with these string: 
Settings String: 318AygECgKCAYUBiAEEAAKtJEEkFAEAFAANCQABEgAAAAAADAyAvPm8QZIICTIICAC8AwUUUG9rZW1vbiBQbGF0aW51bSAoRik4bRgs48M4ig==

**Screenshots**
![image](https://user-images.githubusercontent.com/75745165/168470139-eb83ea3a-3d83-44ee-b052-6d00a020b95d.png)
![image](https://user-images.githubusercontent.com/75745165/168470185-0d9dbe95-a833-48cc-ab28-609e46a64046.png)
Randomizer Version: 4.4.0
Random Seed: 250272897748963
Settings String: 318AygECgKCAYUBiAEEAAKtJEEkFAEAFAANCQABEgAAAAAADAyAvPm8QZIICTIICAC8AwUUUG9rZW1vbiBQbGF0aW51bSAoRik4bRgs48M4ig==

![image](https://user-images.githubusercontent.com/75745165/168470450-d7ac0392-666f-4aba-b205-49ed5836fc9c.png)
![image](https://user-images.githubusercontent.com/75745165/168470337-ea9fd76e-5e25-4275-b045-19c8d0e42e1b.png)
Randomizer Version: 4.4.0
Random Seed: 202059753610851
Settings String: 318AygECgKCAYUBiAEEAAKtJEEkFAEAFAANCQABEgAAAAAADAyAvPm8QZIICTIICAC8AwUUUG9rZW1vbiBQbGF0aW51bSAoVSlZglm+48M4ig==

**System (please complete the following information):**
 - Randomizer Version: 4.4.0

**Comment by tom-overton** [comment]
This is not a bug; if you turn on random field items, the TMs present on the field may change their number, even if TMs themselves are not randomized.
