### ISSUE TITLE
Doesn't randomize starters or encounters for me?

### ISSUE THREAD

**Issue by cbrinkman1** [Ajarmar/universal-pokemon-randomizer-zx#44]
I can randomize trainer battle, but that is it. Nothing else randomizes. My guess is a faulty rom, but I'm not sure. Any good places I can grab a better one?

**Comment by tom-overton** [comment]
What game are you even trying to randomize? Can you provide a log of your randomization?

**Comment by cbrinkman1** [comment]
I am trying to randomize a 3ds file of Pokemon Y, and everything seems to work. I used random starter, static, and trade (given only) pokemon, as well as opposing trainer pokemon, wild pokemon, tms, and items. I turned on fastest text. Then I saved it all as a CXI file, and ran it on citra. The game was not randomized, except for trainer pokemon. I have tried it multiple times, with the same result.

**Comment by tom-overton** [comment]
I'm fairly certain what's happening is that you have a game update installed in Citra. See if you have something like "Ver 1.5" on the file select screen like this:
![screen](https://user-images.githubusercontent.com/12245827/97213538-f776ac80-177e-11eb-928d-900c5c851d9d.png)

If you have a game update installed in Citra, you have two options:
1. Delete the game update. You can follow the instructions [here](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Randomizing-the-3DS-games#managing-game-updates-in-citra) to delete it
2. Load a CIA of the same game update inside the randomizer. You can follow the instructions [here](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Randomizing-the-3DS-games#3ds-game-updates) to load it

**Comment by cbrinkman1** [comment]
Oh does that take priority?
Thats probably it, thanks.
