### ISSUE TITLE
[Contribution Idea]

### ISSUE THREAD

**Issue by DinoDazed** [Ajarmar/universal-pokemon-randomizer-zx#444]
**Is your idea a new setting, a change to an existing setting, or something else? Please describe clearly:** 
Adding a config setting to disable the "Randomizer was not started via the launcher" popup. The popup would be enabled by default.

**What problem would your contribution solve? Please describe:** 
This would eliminate the nuisance message when the Randomizer is opened from the JAR file.

**Additional context:**

**Comment by Ajarmar** [comment]
I can understand the popup being a nuisance if you need to start the randomizer without the launcher for some reason, but we have too much trouble already with people not using the launcher (and running into errors) despite how clear we try to make it so we'd really like to avoid any sort of feature that suggests that the user can skip using the launcher. Sorry!
