### ISSUE TITLE
I also just updated it and got a different error code.

### ISSUE THREAD

**Issue by SneakyCreaper** [Ajarmar/universal-pokemon-randomizer-zx#446]
**Describe the bug**
I have launched version 4.4.0 and have tried to randomize pokemon x via citra nightly but when I do it says that the randomizer was not started via the launcher and that I will not be able to load 3ds games into the randomizer. When I try to launch the unrandomized game in citra nightly it works, so I have come to believe that it has something to do with the randomizer. 

**System (please complete the following information):**
 - Operating System: Microsoft windows 10 home
 - Java Version: 64-bit Java for Windows, Version 8 Update 333
 - Randomizer Version: 4.4.0
![image_2022-05-26_115513955](https://user-images.githubusercontent.com/105977703/170464839-ec2e495a-4fa3-45de-a52e-aaa1e7c3982a.png)

**Comment by tom-overton** [comment]
Did you launch the randomizer by double-clicking on launcher_WINDOWS.bat?

**Comment by SneakyCreaper** [comment]
how do I do that?

**Comment by SneakyCreaper** [comment]
I just updated it and got this:
![image_2022-05-27_081852974](https://user-images.githubusercontent.com/105977703/170642145-d641b921-64f4-4b54-a097-0d54df01d745.png)

**Comment by SneakyCreaper** [comment]
But I don't know how to.

**Comment by SneakyCreaper** [comment]
And how do I see what the appropriate launcher for my operating system is?

**Comment by SneakyCreaper** [comment]
When I click on launcher_WINDOWS.bat it says this:
![image_2022-05-27_082623384](https://user-images.githubusercontent.com/105977703/170643176-84a22254-6ea3-403c-8d77-9c33aa32a1a3.png)

**Comment by SneakyCreaper** [comment]
I just came back from my trip and it works now for some reason. Thank you for your help 😄

**Comment by tom-overton** [comment]
Great, glad it's working! If you run into any other launcher issues, be sure to check #221
