### ISSUE TITLE
[Bug] Sprites breaking in Soul Silver

### ISSUE THREAD

**Issue by Mrwolffey** [Ajarmar/universal-pokemon-randomizer-zx#450]
This has happened to me in two different saves in Soul Silver. After a battle, my character and following pokemon sprites are jumbled boxes. I can still move, but after the next battle, the whole top screen goes black, and if I save in this state, it stays this way after a restart. I wasn't able to reproduce it in order to get screenshots/video, but the most reliable way I was able to replicate it is to catch a new pokemon, enter battle with it, switch mid fight, and win with the swapped pokemon.

OS: Windows 10
Java: Version 8 update 333 (build 1.8.0_333-b02
Randomizer version: v4.4.0
Emulator: DeSmuME 0.9.11 x64

**Comment by tom-overton** [comment]
This is a problem with older versions of Desmume, not the randomizer. Grab the latest Desmume here: https://github.com/TASEmulators/desmume/releases/tag/release_0_9_13
