### ISSUE TITLE
[Contribution Idea] Custom Starters, partial random

### ISSUE THREAD

**Issue by Zach-Meadows** [Ajarmar/universal-pokemon-randomizer-zx#453]
**Is your idea a new setting, a change to an existing setting, or something else? Please describe clearly:** 

Change to current setting

The current starter pokemon options for Custom are set for choosing the exact pokemon you want, but there's a good bit of Ironmon streamers that enjoy doing one specific mon and the others random. I'd like to implement the ability to choose "random" in the dropdown for custom.

**What problem would your contribution solve? Please describe:** 

simplifies the process of randomly choosing a rival mon in tutorial battle.

**Additional context:**

My knowledge with the current setup is limited and would love to work with the other programmers on this and other features. If there's a discord or other communication platform for the existing engineers i'd love to be a part of it.

**Comment by Ajarmar** [comment]
Sure, I think this would be a fine addition. I'm not sure of everything that would need to be changed, but you'd definitely need to make some changes around here where the combo boxes are set up: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/blob/master/src/com/dabomstew/pkrandom/newgui/NewRandomizerGUI.java#L3613

And also in the method where the custom starters actually are set in the code: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/blob/master/src/com/dabomstew/pkrandom/romhandlers/AbstractRomHandler.java#L3184

Instructions for building the randomizer can be found here, in case you haven't already set that up: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Building-Universal-Pokemon-Randomizer-ZX

**Comment by Ajarmar** [comment]
Closed by https://github.com/Ajarmar/universal-pokemon-randomizer-zx/pull/455
