### ISSUE TITLE
[Bug] Pokémon World Tournament Error Message

### ISSUE THREAD

**Issue by wwtepicfail** [Ajarmar/universal-pokemon-randomizer-zx#454]
**Describe the bug**
In the Pokémon World Tournament, I experienced an error message before the Colress battle in the Driftveil Cup commences. The Hugh and Cheren battles work fine, but Colress' did not, making it impossible to pass through this section of the game.

**Expected behavior**
The Colress battle should have occurred as normal.

**System (please complete the following information):**
 - Operating System: Windows 10

 - Java Version: Version 8 Update 321 (build 1.8.0_321-b07)
 - Randomizer Version: v4.4.0

**Additional context**
You can easily replicate my problem by generating the same seed using [the log file](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/8866787/aBadIdeaGoneHorriblyWrong.nds.log) and [save file](https://cdn.discordapp.com/attachments/492840729429803023/984309407770898462/aBadIdeaGoneHorriblyWrong.nds.sav).

Speaking of the log file, this is supposed to be Colress' roster:
`#815  - Jolteon@Scope Lens Lv25, Sigilyph@Rawst Berry Lv25, Ekans@Rawst Berry Lv25`

This was done on a _White 2_ ROM.

**Comment by tom-overton** [comment]
Thanks for the report; apparently this happens because two Pokemon that have the same item. This works fine for normal trainers, but causes an error in the PWT. Why? Who knows.
