### ISSUE TITLE
Could not load Rom as it is unsupported[Bug] 

### ISSUE THREAD

**Issue by LumpyLimpyloo** [Ajarmar/universal-pokemon-randomizer-zx#459]
When trying to open a ROM of a pirated ultra sun it says it has an unsupported ROM. it has a .standard.cia ending which could be the problem but i really dont know. I am using windows 10 if that makes a difference.
This is my first time using this programme or even homebrewing a console so i could just be an idiot.

**Comment by Ajarmar** [comment]
If you didn't dump the ROM yourself and the randomizer says it's unsupported then the ROM is probably corrupt in some way. Try using a different ROM.

**Comment by LumpyLimpyloo** [comment]
Thanks, i have found another that seems to have worked.
