### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by vcudi** [Ajarmar/universal-pokemon-randomizer-zx#463]
when i open the mac key it shows that it is invalid and the randomizer wont open
when i download the link and i open it, i have mac so i try to open the mac starter but it shows a bunch of code and states that the key is invalid and the pokerandozx wont open and when i try to open it through just the jar it says that it was not opened by the launcher but the launcher does not work.
**To Reproduce**
1. Go to 'mac.launcher'
2. Click on 'mac.launcher'
code and invalid 

**Expected behavior**
i expected to open it and it would open the pokerandozx but instead it showed a bunch of other things and nothing will open
**Screenshots**

**System (please complete the following information):**
 - Operating System: mac book pro 
 - Java Version: newest version
 - Randomizer Version: newest version

**Additional context**

the only thing that does not work is the mac launcher the randomizer works good but the thing that does not work is the launcher 
<img width="1280" alt="Screen Shot 2022-06-15 at 12 11 15 PM" src="https://user-images.githubusercontent.com/107580822/173906985-3fa21ed3-a606-4d6b-bbbf-e57b053a7f62.png">

**Comment by tom-overton** [comment]
I think that error is indicating that:
- You either don't have Java 8 installed, or
- You *do* have Java 8 installed, but for some reason the Terminal can't find it.

Can you open up your Terminal and type `java -version`, then show what it says?

**Comment by vcudi** [comment]
> I think that error is indicating that:
> 
> * You either don't have Java 8 installed, or
> * You _do_ have Java 8 installed, but for some reason the Terminal can't find it.
> 
> Can you open up your Terminal and type `java -version`, then show what it says?

when i open terminal and type that in it says version 1.6
<img width="1280" alt="Screen Shot 2022-06-15 at 4 05 51 PM" src="https://user-images.githubusercontent.com/107580822/173956700-f94005ad-1f3e-415e-a8c6-9cd05e6d7be8.png">

**Comment by tom-overton** [comment]
Yeah, there's the problem. I'm not 100% sure how to fix this sort of thing, because if you ran the randomizer successfully without using the launcher, then you *do* somehow have Java 8 installed; it's just that for some reason, the `java` command in the terminal can't seem to find it.

Maybe something like this might help? https://apple.stackexchange.com/questions/344677/how-do-i-remove-java-version-1-6-0-65

The point is, to use the launcher, you need to make it so running `java` in the Terminal maps to Java 8, not Java 1.6.

**Comment by vcudi** [comment]
thank you so much for the help i got it fixed

if you wanted to know how to fix it all i did was delete java off my mac and do the same with deleting it off terminal and redownloading it on terminal so that i could finally open the mac launcher and i can now play thank you.

**Comment by tom-overton** [comment]
Great, glad to hear it's fixed! I'll close this issue out. If someone else with a Mac comes to us with this problem, I'll point them to this issue.
