### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Silky422** [Ajarmar/universal-pokemon-randomizer-zx#467]
**Describe the bug**
Testing on gen 4, selecting the randomize each level setting and keeping the rest of the game unrandomized, the pokemon evolves into the same 4 pokemon in a cycle. 

**To Reproduce**
1. Loaded a platinum rom (US 1.1v)
2. Enable Randomize evolution every level setting 
3. Didn't Randomize any other settings 
4. level up pokemon 6-7 times, recycles the same 4 pokemon in a pattern

**Expected behavior**
Randomize pokemon evolution at each level using the entire roster of pokemon.

**System (please complete the following information):**
 - Operating System: Windows 10
 - Java Version: Java version 8 update 281
 - Randomizer Version: V4.4.0

**Comment by tom-overton** [comment]
This is intended behavior; evo every level is not *supposed* to make Pokemon evolve into every single possible Pokemon in the roster. Otherwise, there's not really much of a point in catching other Pokemon.
