### ISSUE TITLE
When I try to open launcher_windows, it crashes and gives me an error screen

### ISSUE THREAD

**Issue by oshafudge** [Ajarmar/universal-pokemon-randomizer-zx#470]
**Describe the bug**
Just downloaded randomizer and when i went to go open from the windows launcher it tells me fatal error press any key to exit.
**To Reproduce**
1. Go to randomizer folder
2. Click on launcher_windows
 See error

**Expected behavior**
should have launched randomizer
**Screenshots**

**System (please complete the following information):**
 - Operating System: windows
 - Java Version: ?
 - Randomizer Version: ?

**Additional context**

**Comment by Pau0910** [comment]
![Captura de pantalla 2022-06-24 034837](https://user-images.githubusercontent.com/108107237/175446067-1313de22-cb60-4197-b961-129973e762a3.jpg)

**Comment by JakobDev** [comment]
Did you have 32bit Java?

**Comment by Pau0910** [comment]
i have Java 64, i dont remember i had Java 32

**Comment by kronmandoom** [comment]
i also am having the same problem

**Comment by oshafudge** [comment]
I was using the wrong version of Java.
Download it from there troubleshooting page they have the correct link. Solved problem for me

**Comment by oshafudge** [comment]
solved
