### ISSUE TITLE
[Bug] Premade Seed does not produce the same randomization as the original

### ISSUE THREAD

**Issue by sornerol** [Ajarmar/universal-pokemon-randomizer-zx#476]
**Describe the bug**
When using the Premade Seed dialog to randomize a ROM, the ROM from the presets has a different randomization than the original ROM.

**To Reproduce**
1. Open a ROM
2. Choose randomization settings or load a settings string
3. Click Randomize
4. When prompted to save a presets file, click Produce File to save it
5. Click Premade Seed
6. Select the presets file you just created
7. Select the required ROM file
8. Click Apply Randomization Settings
9. Compare the checksums of the original randomized ROM and the one generated from the presets file.

**Expected behavior**
The first randomized ROM and the one generated from the presets file have the same checksum.

**Screenshots**
![presets-bug](https://user-images.githubusercontent.com/47842483/176510017-57b1a787-386d-45b5-8caf-a151a5eba199.png)

**System (please complete the following information):**
 - Operating System: Linux Mint 20.3
 - Java Version: 8.332.08.1-amzn
 - Randomizer Version: 4.5.0 (commit 4ea92d8)

**Additional context**
I also tested this by manually copying the values for Config String and Random Seed and got the same results.

**Comment by tom-overton** [comment]
Can you post your seed/string combo that replicates this? I can't seem to get this to happen myself.

**Comment by sornerol** [comment]
Here are some more details about what I'm encountering:
1. I'm testing this with a Pokemon Fire Red v1.1 ROM.
2. I'm using the following settings string: `319WRIEEjIBAAQABwCRAAKeBnsECQEAFAACCQAuEgAAAAAABRi45ATkAYYICTIGBAIyAAUAEEZpcmUgUmVkIChVKSAxLjGwV2lQ48M4ig==`
3. After clicking Randomize (Save), I am presented with the dialog which shows the random seed and config string, and I'm asked if I want to produce a presets file to use for creating the same randomization.
![randomization-complete-dialog](https://user-images.githubusercontent.com/47842483/177018835-9eb79cb4-3a82-4aaa-9226-28be1ae14912.png)
5. Regardless of whether I enter the values from this dialog manually on the Premade Seed dialog, or I choose the presets file, I get a different randomization than the original (as determined by running `md5sum` on both randomized ROMs).

**Comment by tom-overton** [comment]
Thanks for giving me the string; something about trainer randomization does seem a bit broken, so I'll look into it.

**Comment by tom-overton** [comment]
Thanks for filing this; it's been fixed and will work properly in the next release. For now, just now that "Force Fully Evolved" is the culprit; if you want to ensure that premade seeds work properly, that setting needs to be disabled in v4.5.0.
