### ISSUE TITLE
[Bug] Gen 1 Logs Don't Display Special Info and Try to Print SPA/SPD Instead

### ISSUE THREAD

**Issue by NARFNra** [Ajarmar/universal-pokemon-randomizer-zx#486]
**Describe the bug**
If you choose to alter Movesets when randomizing a Generation 1 ROM like Red or Blue, the log file attempts to print out the stats for each Mon over their level-up Movepool, but it tries to write SpA and SpD instead of a Special entry and simply fills them in with 0. No Special stat info slot is provided. The games themselves are randomized perfectly fine with no issues I noticed - only the log file has this error. The Base Stats & Types and Wild Pokemon sections correctly provide a SPEC stat entry with no SPA or SPD listed.

**To Reproduce**
1. Open a Generation 1 ROM (I tested with US Blue and US Red only, with release 4.5.)
2. Choose any combination of settings that will print out the Pokemon Movesets section of the log.
3. Choose to create log when randomizing file and randomize.
4. Check log. 

**Expected behavior**
Like the Base Stats & Types section, instead of an SPA/SPD stat, there should be a single SPEC stat that contains the relevant number.

**Screenshots**
![image](https://user-images.githubusercontent.com/7265358/178087063-52c6387c-9c6a-4274-b289-bccdc0a8e5a0.png)

Example logs:
[testinlogissue.gbc.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/9075668/testinlogissue.gbc.log)
[PokemonRedTotallyNuts-CooltrainerTest.gbc.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/9075674/PokemonRedTotallyNuts-CooltrainerTest.gbc.log)

**System (please complete the following information):**
 - Operating System: Linux, Ubuntu 18.04
 - Java Version: 17.0.3, OpenJDK 64-Bit Server VM
 - Randomizer Version: 4.5.0

**Additional context**
I am aware this is a small issue that is mostly worked around by being irrelevant unless other changes are applied anyway, but I thought I'd mention it all the same. Thank you for your hard efforts.

**Comment by tom-overton** [comment]
Thanks, will be fixed in the next release.
