### ISSUE TITLE
Starters not random

### ISSUE THREAD

**Issue by noclipthunder** [Ajarmar/universal-pokemon-randomizer-zx#50]
Ive been trying for a few weeks on and off to randomize ORAS and now X as well for a friend and myself, but the starters and tms are never random. I know that I selected that option (I even have the randomized settings file saved) and the randomizer seems to be working otherwise (abilities and wild pokemon are random) any ideas what could be happening?

**Comment by tom-overton** [comment]
I'm fairly certain what's happening is that you have a game update installed in Citra or on your 3DS. See if you have something like "Ver 1.5" on the file select screen like this:

![image](https://user-images.githubusercontent.com/12245827/97775269-90f5e380-1b1c-11eb-98de-e482b1db036b.png)

If you have a game update installed in Citra, you have two options:
1. Delete the game update. You can follow the instructions [here](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Randomizing-the-3DS-games#managing-game-updates-in-citra) to delete it
2. Load a CIA of the same game update inside the randomizer. You can follow the instructions [here](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Randomizing-the-3DS-games#3ds-game-updates) to load it

**Comment by noclipthunder** [comment]
I deleted and reloaded the cia into citra with version 1.4 (same thing I had before as well) and the same thing is happening, when I randomize it will produce a cxi file but gives me an error message saying "There was an unhandled exception trying to save your ROM to disk." when I try producing a LayeredFS

Could I be doing something wrong loading the files? I've been using the cia I have loaded into citra to randomize, then I go file> load file> and click the randomized game

**Comment by tom-overton** [comment]
Can you upload the error.txt file that is produced when you get that error? If you do, I can take a look and see if the error is on your side or ours

**Comment by noclipthunder** [comment]
This is what I see from my most recent attempt at randomizing Omega Ruby


Randomizer Version: 4.0.0
Seed: 28023248982772
Settings String: 4.0.0OQgEBkL7AP4AAQEEAAKoJAjELAGZLJk9AQABIAAAAAAAAgAI0IHQwdoICTIHBxJQb2tlbW9uIE9tZWdhIFJ1YnmG+rwP48M4ig==
ROM: Pokemon Omega Ruby
Code: CTR-P-ECRA
Reported Support Level: Complete

com.dabomstew.pkrandom.exceptions.RandomizerIOException: java.io.FileNotFoundException: C:\Users\nocli\OneDrive\Desktop\Soul Link\ORAS\...\000400000011C400\code.bin (The system cannot find the path specified)
	at com.dabomstew.pkrandom.romhandlers.Abstract3DSRomHandler.saveRomDirectory(Abstract3DSRomHandler.java:107)
	at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:611)
	at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$performRandomization$98(NewRandomizerGUI.java:825)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: C:\Users\nocli\OneDrive\Desktop\Soul Link\ORAS\...\000400000011C400\code.bin (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at com.dabomstew.pkrandom.ctr.NCCH.saveAsLayeredFS(NCCH.java:551)
	at com.dabomstew.pkrandom.romhandlers.Abstract3DSRomHandler.saveRomDirectory(Abstract3DSRomHandler.java:105)
	... 3 more

**Comment by noclipthunder** [comment]
[error_2020-10-31-16-58-41.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5470119/error_2020-10-31-16-58-41.txt)
heres the actual file i have as well

**Comment by tom-overton** [comment]
Huh, I thought this might have something to do with OneDrive, but I actually can make a LayeredFS directory in a OneDrive folder just fine. Can you try outputting your layeredFS somewhere other than your OneDrive? The error is simply complaining that it can't find the file path, so maybe trying somewhere else would make it work.

**Comment by noclipthunder** [comment]
The layeredFS is coming through now, just doesnt pop up when i try loading in citra, did i a different step to use the layeredFS?

**Comment by tom-overton** [comment]
Yeah, you need to make sure that you've copy-and-pasted the layeredFS directory into the game's mod directory in Citra. [We have a section on the wiki about this](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Randomizing-the-3DS-games#guide-for-playing-your-randomized-layeredfs-directory-on-the-citra-emulator); hopefully that solves the problem!

**Comment by noclipthunder** [comment]
Yes!!! The starters are random, I'm very thankful for your help and appreciate your time greatly. Have a wonderful night^
