### ISSUE TITLE
Certain ROM incompatibility

### ISSUE THREAD

**Issue by pokemonfan6498** [Ajarmar/universal-pokemon-randomizer-zx#504]
I had found that some roms aren,t compatible:
Pocket Monsters - Aka (Japan) Rev1
Pocket Monsters - Midori (Japan) Rev1
Pocket Monsters - Pikachu (Japan) Rev1/2/3
Pocket Mosnters Eum/Geum (Korea)
Pocket Monsters - Ruby (Japan) Rev1
Pocket Monsters - Sapphire (Japan) Rev1
Pocket Monsters - LeafGreen (Japan) Rev1
Pocket Monsters - Diamond (Japan) Rev5/6
Pocket Monsters - Pearl (Japan) Rev5/6

**Comment by tom-overton** [comment]
Sorry, but we have no interest in adding support for versions that are not currently compatible with the randomizer. Frankly, I'd remove support for a lot of versions if Ajarmar would let me.
