### ISSUE TITLE
[Contribution Idea] Option for Ditto to always have Transform as its only move

### ISSUE THREAD

**Issue by kittenchilly** [Ajarmar/universal-pokemon-randomizer-zx#508]
**Is your idea a new setting, a change to an existing setting, or something else? Please describe clearly:** 
This would be a new setting. It'd work a lot like the Wonder Guard setting that guarantees Shedinja always has that ability, but for Ditto and Transform.

**What problem would your contribution solve? Please describe:** 
Like Shedinja having Wonder Guard, Ditto only learning Transform and it being its only move is something that is unique to it. I think having this option would make randomizer runs more interesting when you have random movesets on and run into it, both for using it and encountering it on a trainer. It'd be an option, of course.

**Additional context:**
I got this idea from Ironmon when I found it weird that Ditto wasn't any special and was even a bad mon since it didn't learn moves by leveling up. With this option it'd be actually fun and interesting to run with.

**I understand that I am expected to implement this change myself in the randomizer's codebase: [X]**

**Comment by Ajarmar** [comment]
Thanks for the submission, but we'll pass on this. Forcing a Pokemon to only have a single move is quite a bit more problematic than forcing a Pokemon to only have a single ability, as it interferes with settings like extra level 1 moves, TM/HM randomization, and "better movesets". Additionally, Shedinja is pretty much the only special case in the whole randomizer, even though you could make the case for several other Pokemon that it's "part of their identity" to have a certain move or ability (Ditto with Transform like you mentioned, but some others that come to mind are Unown with Hidden Power, Castform with Forecast, and Arceus/Silvally with Multitype/RKS System). We'd prefer to not have too many special cases.
