### ISSUE TITLE
[Help] Java IllegalArgumentException on start

### ISSUE THREAD

**Issue by C0ntroller** [Ajarmar/universal-pokemon-randomizer-zx#509]
When starting the launcher script (or the jar directly doesn't matter) I get the following error:

> Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Comparison method violates its general contract!

This happens on both the Oracle JRE version 8 (so "1.8") and the OpenJDK 18. Everything works fine in WSL using the same Java versions. Full traceback can be found here: https://pastebin.com/D8XbiMw9

**System (please fill in the following information):**
 - Operating System: Windows
 - Randomizer Version: 4.5.1

**Comment by tom-overton** [comment]
I'm completely stumped on this one. Did you ever get it working? In the traceback, I don't see *any* randomizer code actually running.

**Comment by C0ntroller** [comment]
No I just launched it in the WSL where this error didn't happen.

So you say, maybe my Java installation could have been faulty?

**Comment by tom-overton** [comment]
Huh, very strange. I took another look, and our code *is* running, but it's not what is causing the crash. This line is the last line of randomizer code that executes before the crash:
```java
private JFileChooser romOpenChooser = new JFileChooser();
```
As you can see, it's a pretty "boring" line of code that doesn't really do anything fancy. The exception being thrown, `Comparison method violates its general contract!`, also doesn't really make much sense here. I can write code that causes this error, but it causes it *consistently*; in other words, it will cause an error on everyone's computer all the time. The fact that no one, to my knowledge, has seen this error before you, and the fact that you even got it working on the same computer using WSL, indicates to me that this is probably some strangeness with Java. I don't know *what* exactly is going wrong or why, but I don't think the randomizer is at fault here.

**Comment by C0ntroller** [comment]
> I don't know _what_ exactly is going wrong or why, but I don't think the randomizer is at fault here.

Well at this point you can close the issue. Seems like my Java installation was/is broken (I currently can't retry). Thank you very much for looking into it!

**Comment by tom-overton** [comment]
Alright, will close this one out then, thanks! I'm sorry you got bitten by one of the strangest issues we've seen yet. Hopefully, you can find a fix for it!
