### ISSUE TITLE
New Randomizer update launcher not working

### ISSUE THREAD

**Issue by RevanXVIV** [Ajarmar/universal-pokemon-randomizer-zx#51]
I just downloaded the new update for the randomizer and when I tried to load the launcher it gave me an error message telling me that my version of Java may not be compatible, I updated my Java but I still get the message. Here's what the launcher log says:

Invalid maximum heap size: -Xmx4096M
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

Any help would be much appreciated.

**Comment by RevanXVIV** [comment]
Edit: Nvm I just had the wrong version of Java it seems to open just fine.

**Comment by tom-overton** [comment]
Well, I'm glad it ended up working!
