### ISSUE TITLE
[Contribution Idea] Porting Pokémon palette randomization from another UPR branch

### ISSUE THREAD

**Issue by voliol** [Ajarmar/universal-pokemon-randomizer-zx#510]
**Is your idea a new setting, a change to an existing setting, or something else? Please describe clearly:** 
It is a port of a feature that comes with multiple settings, as well as a framework for future graphics/palette-related stuff. I'd also like to do some refactoring for the sake of the feature.
The feature is Pokémon palette randomization, which currently resides on this branch of the UPR: https://github.com/voliol/universal-pokemon-randomizer/tree/paltest . Here is a binary/executable release: https://github.com/voliol/universal-pokemon-randomizer/releases/tag/random-palettes-v1.0 . I would like to port it in its entirety to ZX, to continue working on it in a more active environment, and where forms are better figured out. To do so, I would like to refactor the following in ZX, as I did on the branch it is currently on (in case any of this has already been solved in ZX I'll of course use the existing ZX solution):
- Alter/rewrite the methods in GFXfunctions, and getMascotImage().
- Refactor CopyUpEvolutionsHelper so it can be used for palette randomization (seems to have been partially done in ZX?)
- Move some saving functionality to AbstractRomHandler to avoid repeating code 
- Edit the .ini files for Gen 3, since the non-English, non-Japanese versions of Ruby/Sapphire have one of the "pointer blocks" with pointers to e.g. Pokémon names and sprites it makes sense they can use it. Variables like "efrlgPokemonNamesPointer" in Gen3Constants also become misnomers, when they are used for some Ruby/Sapphire games, so they and the RomEntry framework surrounding them would also be altered.

**What problem would your contribution solve? Please describe:** 
It solves the problem of people wanting randomized Pokémon palettes, as found in e.g. Artemis251's Emerald Randomizer, but not being able to combine it with the UPR. It also solves to some degree the problem of not being able to recognize Pokémon types when randomized, as the palettes can be made to follow types, and the difficulty of figuring out evolution chains when randomized, as the palettes can be made to follow evolutions.

**Additional context:**
For information on the palette randomization in the state it is in currently/on the other branch, see this readme: https://github.com/voliol/universal-pokemon-randomizer/blob/paltest/README.md
The palette randomization is set up to use a separate "sub-handler" called the PaletteHandler, to increase cohesion in the central RomHandlers.

**I understand that I am expected to implement this change myself in the randomizer's codebase: [X]**

**Comment by voliol** [comment]
Hello again!

The port to ZX has now been fully done. Though this means fully supporting Gen I-III, and Gen IV and V having a warning label that some Pokémon Palettes will not be randomized (neither will formes). I am unsure how I will proceed; I might take a break from the project after cleaning up some code, leaving Gen IV and V "unfinished".
I also ended up doing heavier refactoring than I had initially anticipated, so I apologize for that, communication-wise. As always with refactoring there is a risk of breaking stuff, so I added JUnit tests to mitigate that.

I would like response so I know what the central ZX people think of this, whether you'll take the branch as is and add its functionality to the next release, or if you want full Gen IV/V support before you consider it complete enough. Or if you don't like it at all. In the latter cases I'd like advise on how to build the binaries, as I would (then) like to to an experimental release on my own for those interested.

**Comment by NathanYumekoe** [comment]
Just here as testimony to this being a feature people would enjoy having! It sounds very cool.

**Comment by Ajarmar** [comment]
Hi, sorry about the late response. I think it's a cool concept, but we're gonna have to decline. To explain a bit:

- The reason why we don't have much in the way of cosmetic randomization is not just because nobody's implemented it yet, but also because it's not really a direction that we want to take the randomizer in. I understand that it's something that some players are interested in, but we prefer to focus on gameplay randomization.
- Extensive refactors are _very_ annoying to merge in, and we're not particularly interested in doing that.

Once again, sorry for responding so late - we've really been slacking on the issue responses these past few months. Regarding your question about how to build the binaries, we have [this page](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Building-Universal-Pokemon-Randomizer-ZX) that may or may not help, but if you have any specific questions I can answer them here.

**Comment by voliol** [comment]
Understood, though I do find this regrettable. The branch has been kept up to date with ZX, so most of the merging in should already have been done. A value of refactoring is also that it should make the code easier for others to work with, not just the refactorer. That being said, I cannot guarantee it is bug-free even with the few test-cases implemented, and I understand you don't want to take on extensive code changes from an unknown second party.  It is what it is. I will continue maintaining a separate branch, for those interested in cosmetic randomization. 

Thank you for giving a response. If/when I do smaller bug-fixes found in ZX in the future (because I hang on /r/pokemonromhacks and users may ask about bugs there), I plan to branch those fixes directly off ZX, and then merge them into my branch. I hope you can use those, that way.
