### ISSUE TITLE
Add dragon scale and up-grade to the bad item list in gen 3 if "Change Impossible Evolutions" is checked

### ISSUE THREAD

**Issue by Kasiyo1** [Ajarmar/universal-pokemon-randomizer-zx#511]
When Change Impossible Evolutions is checked the pokemon that evolve using these items are changed to just level up. These items also have no in battle effect unlike the other evolution items making them useless. I have no idea if people ever trade using the randomizer so I can't say if they should be added to the bad item list in general but when the setting is checked they should be removed from the item pool.

Edit: While I originally only had Dragon scale and up-grade as items to be put on the list. After thinking about it a bit I think deepseascale and deepseatooth should also be added based on the fact that light ball and thick club are on it and those 2 items provide a similar effect to both the deepseascale and tooth.

**Comment by Ajarmar** [comment]
Sorry, but we don't take feature requests. That said, we're planning to take a closer look at how "bad items" are defined in general at some point, and this is the sort of thing we will probably fix when we do that.
