### ISSUE TITLE
[Bug] Trainer randomization fails in the Japanese version of gen3（FRLG）

### ISSUE THREAD

**Issue by enbeeee** [Ajarmar/universal-pokemon-randomizer-zx#512]
**Describe the bug**
Trainer randomization fails in the Japanese version of FRLG
(I am Japanese and I am writing this text using deep translation, sorry if some expressions are difficult to understand, Thank you for all your fun tools.)

Since the error did not occur with the US version of the ROM, it seems to be a problem specific to the Japanese version.

**To Reproduce**
The first item under "Toariner Pokemon," if any of them are checked, the randomization fails.

**Screenshots**
![image](https://user-images.githubusercontent.com/110842680/183463829-eefb53f1-a49b-4134-808c-8b73faf6cfcb.png)
![image](https://user-images.githubusercontent.com/110842680/183466562-e884e39a-5527-43af-9324-fb5ba30fc81b.png)

**System (please complete the following information):**
 - Operating System: windows10
 - Java Version:1.8.0_333-b02
 - Randomizer Version: 4.5.1（This has been occurring since 4.5.0）

**Comment by tom-overton** [comment]
Thank you for the bug report! I fixed the bug, and this will work properly in the next release. This issue happens on all Japanese Gen 3 games (Ruby/Sapphire, FRLG, Emerald) if you have the "Pokemon League Has Unique Pokemon" setting enabled. Until the next release is available, you'll have to disable "Pokemon League Has Unique Pokemon" when using a Japanese version of the games. Sorry for the inconvenience!

**Comment by enbeeee** [comment]
Thank you!
Looking forward to your updates!
