### ISSUE TITLE
Pokémon Omega Ruby and Alpha Sapphire Won't Randomize Starters [Bug] 

### ISSUE THREAD

**Issue by Grip555** [Ajarmar/universal-pokemon-randomizer-zx#513]
I'm running the latest version of the randomizer and I have game version 1.4 on Citra (1778).

I've also noticed it doesn't randomize Trainer names.

Running the Windows 10 Java version.

**Comment by tom-overton** [comment]
Did you load the v1.4 game update in the randomizer? If not, then this is entirely expected; you need to make sure the version in the randomizer and the version that you're playing match.

**Comment by Grip555** [comment]
The issue with patching the game is that I can't get the game to run because all the Randomiser does is extract the ROM without putting it back together. I tried putting it back together myself, but it was corrupted.
