### ISSUE TITLE
[Help] when running the launcher it says could not create the java virtual machine and closes

### ISSUE THREAD

**Issue by bannanabelt** [Ajarmar/universal-pokemon-randomizer-zx#515]
operating system: windows 10 (i have latest version of java)
issue when i open the windows.bat launcher this shows up:

Invalid maximum heap size: -Xmx4608M
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. program will exit.
press any key to exit...

**Comment by ItzFrazele** [comment]
Same Issue here too!

**Comment by DeRiften** [comment]
Same here

**Comment by rbedsole** [comment]
same

**Comment by Ajarmar** [comment]
As @rbedsole mentioned, you need 64-bit Java. read

**Comment by tom-overton** [comment]
Closing as it's just the classic 64-bit Java issue. For more info, see #221
