### ISSUE TITLE
Hi, I'm using a MacBook Pro and when dowloaded the universal randomizer to my desktop and opened the folder, there was only one jar file in it and no launcher.jar file and when I launch the other jar file, it says I cannot randomize my game because I did not use the launcher.

### ISSUE THREAD

**Issue by Bman15mc** [Ajarmar/universal-pokemon-randomizer-zx#517]
**Describe your problem clearly:** 

**System (please fill in the following information):**
 - Operating System: 
 - Randomizer Version: 

**If your problem is that you can't randomize a game:**
If you get a popup saying that there has been an "unhandled exception", please attach the error log as an attached file to this issue.

**Comment by Ajarmar** [comment]
The launcher is not a jar file; if you're on Mac, you should be using the launcher named `launcher_MAC.command`. If you don't see a file like that, make sure you're downloading the correct thing: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases

**Comment by tom-overton** [comment]
Closing this one out, since it's been nearly four months since Ajarmar's reply with no further response.
