### ISSUE TITLE
The launcher does not launch

### ISSUE THREAD

**Issue by faultydevvv** [Ajarmar/universal-pokemon-randomizer-zx#518]
So, what i mean is it basically just, does not launch! i have the correct java version and all, but whenever i double click launcher, it does not launch, the thing that DOES launch is pokerandoZX but it says i cant do anything because it was not opened directly from the launcher 
![image](https://user-images.githubusercontent.com/111494275/185348581-59fed917-d4e7-4438-9f5f-a6ffafbe667f.png)

**Comment by RevanXVIV** [comment]
This message only means you can't randomize 3DS game, anything between gens 1 and 5 should be doable. have you actually tried randomizing a non-gen 6 game?

**Comment by Ajarmar** [comment]
What version of the randomizer are you trying to use?

**Comment by tom-overton** [comment]
Gonna close this one out, since it has been nearly four months since Ajarmar's last reply with no response. OP, please make sure you are using the most recent version (v4.5.1) of the randomizer.
