### ISSUE TITLE
[Bug] Infinite saving issue

### ISSUE THREAD

**Issue by RevanXVIV** [Ajarmar/universal-pokemon-randomizer-zx#519]
**Describe the bug**
Every time I try to save the rom it just saves forever, doesn't matter what rom I seem to use it just saves forever.

**To Reproduce**
Simply tried to make a randomizer out of one of my rom hacks and the file just saved forever, tried it with a clean rom, same result.

**Expected behavior**
I expected the game to save without issue and the randomization to work.

 - Randomizer Version: 
I have tried this on all versions all the way back to like 4.0.1

Nothing seems to fix this, I updated my java, made sure everything was downloaded properly  and I still can't get this tool to work, it's infuriating.

**Comment by RevanXVIV** [comment]
Update: Ok so tried adding random abilities to the mix just out of curiosity and I have zero issues when abilities are randomized.

**Comment by Ajarmar** [comment]
Which game are you trying to randomize when you get this problem, and could you give me a settings file that causes it? You can just upload the file here.

**Comment by MrBreadBread** [comment]
I'm also having a similar issue. Sorry for butting in, but maybe it's got a similar solution for both of us. I'm randomizing Black 2.
Settings file (.rnqs) doesn't seem to be a supported filetype for uploading on Github, so I've just got a google drive link instead.
[https://drive.google.com/file/d/1aEp8V4Le1X9OSRT2BjDAqveQ06kUEiPi/view?usp=sharing](url)
Like OP, I've updated Java and redownloaded everything just to make sure. Thanks in advance.

**Comment by RevanXVIV** [comment]
It turned out to be a bad rom I was using, the issue has since fixed itself.
________________________________

**Comment by MrBreadBread** [comment]
Update on my end: I did some experimenting, saving the rom over and over with/without certain settings. Seems as though the offender was randomizing trainer classes. Even using the basic namelist for trainer classes and having the randomization option checked messed with the program. Everything else worked just fine though.
Upsetting, since I had some funny class names I wanted to use, but that's the way it is.
