### ISSUE TITLE
Wont Randomize at all

### ISSUE THREAD

**Issue by leroy9669** [Ajarmar/universal-pokemon-randomizer-zx#52]
Hi so i've tried to randomize ORAS, USUM and XY and it gets saved as layerdsf for my 3DS but when i get to the starters nothing is randomized. Not even the wild encounters

**Comment by tom-overton** [comment]
Maybe a silly question, but do you have "Enable Game Patching" turned on in Luma like so?

![image](https://user-images.githubusercontent.com/12245827/97969423-e3c9d800-1d74-11eb-92d5-6ca4f341700b.png)

Assuming you do, then maybe you have a version mismatch. On the file select screen, you can see a version info string if your game is updated like so:

![image](https://user-images.githubusercontent.com/12245827/97969526-09ef7800-1d75-11eb-9773-7ec12d6ad899.png)

If you see a game update, you need to make sure that the version of the game in the randomizer matches the version of the game on your 3DS. You have two options:
1. Delete the game update. You can follow the instructions [here](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Randomizing-the-3DS-games#managing-game-updates-on-a-3ds) to delete it
2. Load a CIA of the same game update inside the randomizer. You can follow the instructions [here](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Randomizing-the-3DS-games#3ds-game-updates) to load it

**Comment by tom-overton** [comment]
Closing because I think this is a simple version mismatch and the OP hasn't come back in nearly two weeks
