### ISSUE TITLE
[Help] I keep getting this error " i'ts not a supported rom"

### ISSUE THREAD

**Issue by CatLad4** [Ajarmar/universal-pokemon-randomizer-zx#521]
Every time i try to open a cia file or cxi file from a pokémon game i get this error with the universial pokémon randomizer:
![33B8C9146D874047A672B270D49D7238](https://user-images.githubusercontent.com/83897110/185779101-149a4916-595e-4850-8244-3def70b4e06d.png)

These pokémon games were dumped from Godmode9 on my O3ds. I tried this with a pokémon red cxi and an omega ruby cia. I followed this yt tutorial https://youtu.be/vN7l4gE0qgI and I rewatched it 3 times but for some reason he can edit his game and I can't

 - Operating System: Windows Java 64 latest version
 - Randomizer Version: 4.5.1

**Comment by pokemonfan6498** [comment]
i get same error when tryinbg to use other roms like revision 6 of japanese diamond and pearl

**Comment by Ajarmar** [comment]
Unfortunately it's difficult for us to help with this - if the randomizer says that the ROM is not supported, then there's something wrong with it, but we can't tell what's wrong specifically. I'd suggest maybe checking out a different guide for dumping your games to see if you might have missed something, but we can't help much more than that.

@pokemonfan6498 Rev 6 of Japanese D/P is one of the few official ROMs that we do not support, if you want to play Japanese D/P then I suggest a different revision (or play on English).
