### ISSUE TITLE
[Bug] "Ban Bad items" is not banning mail and berries 

### ISSUE THREAD

**Issue by RobloxxMastr34** [Ajarmar/universal-pokemon-randomizer-zx#522]
I click on ban bad items when they are fully random, and it does not ban the items as they used to.

**System (please complete the following information):**
 - Operating System: Win 10
 - Java Version: 1.8.0_321
 - Randomizer Version: v.4.5.1

**Additional context**
I have only tested this in gens 4 and 5, but none of my newest randomizations are banning the items. i do not use the launcher bat file when randomizing older gens if that changes anything.

**Comment by Ajarmar** [comment]
Could you give me a log file of a randomized game where you've had this happen? You can just upload it here.

**Comment by tom-overton** [comment]
Gonna close this one out due to inactivity. Things like mail and berries are definitely being banned with this setting, at least in my testing.
