### ISSUE TITLE
[Bug] there was an unhandled exception trying to load your ROM. a log file containing some details has been saved to [file]

### ISSUE THREAD

**Issue by cheemmaster** [Ajarmar/universal-pokemon-randomizer-zx#523]
**Describe the bug**
i just dumped a copy of my omega ruby from my 3ds to my laptop and loaded up the launcher for the universal pokemon randomizer. when i tried to open my ROM it said "there was an unhandled exception trying to load your ROM. a log file containing some details has been saved to [file name], i opened the file and it said Randomizer Version: 4.5.1
Java Version: 1.8.0_341, Java HotSpot(TM) 64-Bit Server VM
ROM: Pokemon Omega Ruby
Code: CTR-P-ECRA
Reported Support Level: Complete

com.dabomstew.pkrandom.exceptions.RandomizerIOException: java.io.IOException: Invalid GARC file
	at com.dabomstew.pkrandom.romhandlers.Gen6RomHandler.loadedROM(Gen6RomHandler.java:307)
	at com.dabomstew.pkrandom.romhandlers.Abstract3DSRomHandler.loadRom(Abstract3DSRomHandler.java:69)
	at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$loadROM$106(NewRandomizerGUI.java:775)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Invalid GARC file
	at com.dabomstew.pkrandom.ctr.GARCArchive.<init>(GARCArchive.java:64)
	at com.dabomstew.pkrandom.romhandlers.Abstract3DSRomHandler.readGARC(Abstract3DSRomHandler.java:180)
	at com.dabomstew.pkrandom.romhandlers.Gen6RomHandler.loadedROM(Gen6RomHandler.java:304)
	... 3 more

--ROM Diagnostics--
The ROM you loaded is not a clean, official ROM.
Randomizing ROM hacks or bad ROM dumps is not supported and may cause issues.

File name: 000400000011C400_v02.trim.3ds
.code: 9EDD8BA3
romfs header: D39632B9
a/0/7/3: FC8A

I was using a laptop with windows 10 version 4.5.1 of the universal pokemon randomizer zx. is the problem with the way i dumped omega ruby onto my pc or is it a different problem? please help me out im pretty new to this stuff and im completely lost.

**Comment by Ajarmar** [comment]
Unfortunately it's hard for us to help with this; if the randomizer says that the ROM dump is bad then it typically means it's bad. That said, it seems like the file name of your ROM ends with `v02`. Do you know if you happen to have a patched cartridge?

**Comment by BigBoyFleur** [comment]
Can you randomize ROM hacks at all?

**Comment by tom-overton** [comment]
Gonna close this one out, as Ajarmar asked for a response nearly four months ago and didn't get one. Feel free to reply to this if you come back, OP.

@BigBoyFleur For certain ROM hacks, yes, you can. We do not offer any official support though. This means if you run into issues, you're on your own.
