### ISSUE TITLE
when i  t[Help] 

### ISSUE THREAD

**Issue by dubbiepool** [Ajarmar/universal-pokemon-randomizer-zx#524]
**Describe your problem clearly:** 

**System (please fill in the following information):**
 - Operating System: 
 - Randomizer Version: 

**If your problem is that you can't randomize a game:**
If you get a popup saying that there has been an "unhandled exception", please attach the error log as an attached file to this issue.

**Comment by tom-overton** [comment]
Closing because I think this is literally the same thing as the other one you opened.
