### ISSUE TITLE
i cannot launch the randomizer[Help] 

### ISSUE THREAD

**Issue by dubbiepool** [Ajarmar/universal-pokemon-randomizer-zx#526]
when trying to launch  it has error "Invalid maximum heap size: -Xmx4608M"
**System (please fill in the following information):**
 - Operating System: Windows
 - Randomizer Version: 4.5.1

**If your problem is that you can't randomize a game:**
If you get a popup saying that there has been an "unhandled exception", please attach the error log as an attached file to this issue.

**Comment by tom-overton** [comment]
Closing because I think this is literally the same thing as the other one you opened.
