### ISSUE TITLE
[Help] Setting Random Every Level And Move

### ISSUE THREAD

**Issue by JirayutTon** [Ajarmar/universal-pokemon-randomizer-zx#527]
I'm sorry I'm not good at English

**Comment by Ajarmar** [comment]
Can you explain what it is you need help with?

**Comment by JirayutTon** [comment]
How to randomize every level and move change according to the random ones?

**Comment by Ajarmar** [comment]
If you want randomized evolutions every level, use the "Random every level" setting under "Pokemon Evolutions", and if you want randomized moves, use one of the "Random" settings under "Pokemon Movesets"

**Comment by tom-overton** [comment]
Gonna close this one out due to inactivity, and also because I think Ajarmar did a pretty good job explaining how to make it work.
