### ISSUE TITLE
I have downloaded a ROM, and tried inserting it into the randomizer. The randomizer is telling me to make sure I have permission to open the file, which I do. How do I fix this?[Help] 

### ISSUE THREAD

**Issue by shaunakchaudhuri** [Ajarmar/universal-pokemon-randomizer-zx#528]
**Describe your problem clearly:** 

**System (please fill in the following information):**
 - Operating System: 
 - Randomizer Version: 

**If your problem is that you can't randomize a game:**
If you get a popup saying that there has been an "unhandled exception", please attach the error log as an attached file to this issue.

**Comment by Ajarmar** [comment]
Try moving the ROM file to a different folder and see if that helps.

**Comment by tom-overton** [comment]
Closing this one, as Ajarmar offered a suggestion nearly four months ago. If you do come back, OP, let us know if moving it to a different folder helps.
