### ISSUE TITLE
[Contribution Idea] Option to disable AIs knowing about species' abilities

### ISSUE THREAD

**Issue by endrift** [Ajarmar/universal-pokemon-randomizer-zx#529]
**Is your idea a new setting, a change to an existing setting, or something else? Please describe clearly:** 

Adding an option to disable the AI trainers from having knowledge of 'mon abilities in gens 3+. For example, if your 'mon has only one possible ability per species, and that ability is an absorb ability, the opponent will try to not use that type against you.

**What problem would your contribution solve? Please describe:** 

It's a rando. If you don't know species' abilities, why should they? I've seen streamers (partially jokingly) call this the AI cheating.

**Additional context:**

Since this is not necessarily desirable, it would most likely make sense as an option that's not enabled by default, especially since that would match the existing behavior.

**I understand that I am expected to implement this change myself in the randomizer's codebase: [X]**

I've made one-off ROM hacks of Gen 3 pret reversing before, as well as making binary-only patches; I definitely have enough experience to take care of this on games that have far-enough along decompilations.

**Comment by Ajarmar** [comment]
Thanks, but we'll pass on this idea. The capabilities of the player and the AI are unavoidably different, and changing just one facet of this is too niche of a feature.
