### ISSUE TITLE
I'm trying to open "launcher_WINDOWS.bat" and this error comes up.

### ISSUE THREAD

**Issue by Zinx12** [Ajarmar/universal-pokemon-randomizer-zx#531]
"Invalid maximum heap size: -Xmx4608M
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Press any key to exit..." Any Help?
I already reinstalled Java, And it's up to date.

**Comment by icenemore** [comment]
me too

**Comment by Ajarmar** [comment]
You need 64-bit Java. Read this page: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java
