### ISSUE TITLE
What does bad CRC32 mean?

### ISSUE THREAD

**Issue by mewtwofan** [Ajarmar/universal-pokemon-randomizer-zx#532]
Hi, I just recently dumped my Pokemon Alpha Sapphire so I could randomize it, but when I load the trim.3ds file into the randomizer, I get this at the top. What does this mean? 
![Screenshot 2022-09-06 232111](https://user-images.githubusercontent.com/112999733/188781414-68381a2e-2cc1-4fd0-81fc-bed0c42c6951.png)

**Comment by tom-overton** [comment]
Bad CRC32 means that the randomizer doesn't think that's a clean ROM. However, we have had multiple people report ORAS carts that they have personally dumped which are considered unclean. Can you tell me exactly how you dumped it, and what the name of the resulting dump is?

**Comment by tom-overton** [comment]
Gonna close this one since it's been two months without a response. If you do come back and want to tell me how it was dumped, please let me know though!
