### ISSUE TITLE
Development Plans

### ISSUE THREAD

**Issue by bidoof87** [Ajarmar/universal-pokemon-randomizer-zx#533]
Hello, I've tried searching the issues to see if anything regarding this was mentioned, but I didn't find anything. Are there any plans to add the dark, steel, and fairy typing to Gen I? As well as updated movesets from Gen II and on? I would love to be able to play through Pokemon Red with a Wigglytuff that can learn Play Rough, for example. 

Thank you in advance :)

**Comment by tom-overton** [comment]
We have no plans on adding types or moves to games where they do not currently exist.
