### ISSUE TITLE
Not randomizing[Bug] 

### ISSUE THREAD

**Issue by MLGJu** [Ajarmar/universal-pokemon-randomizer-zx#535]
**After i do my settings, like activating random starters. random trainers, etc. and want to finish it i finally press "randomize save" but after that i always get a pop up, that something didn't work and receive an error document**

**To Reproduce**
1. Go to 'open rom'
2. Click on 'load settings'
3. Press Randomize (Save)

**Expected behavior**
I want the file to insert in a emulator und play the wanted randomizer

**System (please complete the following information):**
 - Operating System: 
 - Java Version:
 - Randomizer Version: 1.7.2

[error_2022-09-10-22-07-08.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/9541365/error_2022-09-10-22-07-08.txt)

**Comment by MLGJu** [comment]
Forgot the Screenshot. Here is the addition 
![Screenshot (110)](https://user-images.githubusercontent.com/113263129/189500717-fb18b1c5-a4c5-46a0-9a5e-a936c04e02c8.png)

**Comment by tom-overton** [comment]
You're using Universal Pokemon Randomizer, which hasn't been updated in over six years. This is the Universal Pokemon Randomizer *ZX* repo, so we can't really help you with issues that occur in a super old build that isn't even ours. Grab the latest release of Universal Pokemon Randomizer ZX [here](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases/tag/v4.5.1) and try that instead.

**Comment by MLGJu** [comment]
> 

Well i didn't knew that, just took the first on google. Thanks for the information and link :)
