### ISSUE TITLE
[Help] Randomized Heartgold not working

### ISSUE THREAD

**Issue by Levisetmores** [Ajarmar/universal-pokemon-randomizer-zx#536]
I was trying to randomize Pokemon HeartGold with an Anti-Piracy fix so that I could run it on Twiilightmenu++ without the popup or issues that come from just a normal randomization. But when I tried it gave me an unhandled exception. I don't know what I can do to fix this.

 - Operating System: Windows 10
 - Randomizer Version: 4.5.1

Randomizer Version: 4.5.1
Seed: 46456823493096
Settings String: 320AQgEAQSYAJsAngAEAAEeRAABFAAAFABABAABAAAAAAAAAASIMgQyAQAICTIGBQAyAAIAFVBva2Vtb24gSGVhcnRHb2xkIChVKbyrpqXjwziK
Java Version: 1.8.0_291, Java HotSpot(TM) 64-Bit Server VM
ROM: Pokemon HeartGold (U)
Code: IPKE
Reported Support Level: Complete

java.lang.IndexOutOfBoundsException
	at java.io.RandomAccessFile.writeBytes(Native Method)
	at java.io.RandomAccessFile.write(Unknown Source)
	at com.dabomstew.pkrandom.newnds.NDSRom.copy(NDSRom.java:443)
	at com.dabomstew.pkrandom.newnds.NDSRom.saveTo(NDSRom.java:367)
	at com.dabomstew.pkrandom.romhandlers.AbstractDSRomHandler.saveRomFile(AbstractDSRomHandler.java:92)
	at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:679)
	at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$performRandomization$111(NewRandomizerGUI.java:1020)
	at java.lang.Thread.run(Unknown Source)

--ROM Diagnostics--
The ROM you loaded is not a clean, official ROM.
Randomizing ROM hacks or bad ROM dumps is not supported and may cause issues.

File name: Pokemon - HeartGold Version (USA)_apfix_trimmed.nds
arm9: 5D39375C
overlay9_12: 048416DE
overlay9_1: 2166BEFE
overlay9_21: A17E976F
overlay9_61: 7C547A77
a/0/0/1: 6644F919
a/0/0/2: DE8C5CAF
a/0/0/4: 373BBE93
a/0/1/1: 284AEE7A
a/0/1/2: A7E3F740
a/0/1/7: 40823EDE
a/0/2/7: 123DEB0B
a/0/3/2: 3AC93851
a/0/3/3: F0F9B169
a/0/3/4: 6711E4B4
a/0/3/7: 9B861BD5
a/0/5/5: 8B9BD9CE
a/0/5/6: E30BC8BE
a/1/1/2: 24561BD6
a/1/3/3: 4B9696A6
a/2/2/9: 67123F30
a/2/5/2: 82A55C45
data/mushi/mushi_encount.bin: 17CA15C5
fielddata/maptable/mapname.bin: 5547F5BE
fielddata/wazaoshie/waza_oshie.bin: 1DFC77A1
poketool/personal/pms.narc: C457991B

**Comment by tom-overton** [comment]
We don't offer support for ROMhacks, including those created by antipiracy patches. Try applying the antipiracy patch to an already randomized ROM.
