### ISSUE TITLE
says Invalid maximum heap size: -Xmx4608M even though I don't have it set to 4608m

### ISSUE THREAD

**Issue by PizzedPantz04** [Ajarmar/universal-pokemon-randomizer-zx#538]
**Describe the bug**

says Invalid maximum heap size: -Xmx4608M even though I don't have it set to 4608m

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - Operating System: 
 - windows
 - 
 - Java Version:
 - 
 - 1.8.0_341
 - 
 - Randomizer Version: 
 - v4.5.1

**Additional context**

**Comment by Ishryn** [comment]
Hello, i had a similar problem to yours, what you have to do is get the java64 version, just grab the java 64 offline version from  here[https://www.java.com/en/download/windows_manual.jsp?host=java.com&locale=en-GB](url)
