### ISSUE TITLE
Can't randomize abilities [help]

### ISSUE THREAD

**Issue by maltheslarsen** [Ajarmar/universal-pokemon-randomizer-zx#540]
So I've tried countless solutions trying to work around it. But every time I create a randomizer for pokemon Y, regardless of if its "pk3ds" or the "universal randomizer x-y version 4.5.1", it never changes the abilities. I've updated the randomizer to the newest version and also Java. Every other thing gets randomized perfectly except the abilities, can anyone help?

I'm using windows 10

**Comment by tom-overton** [comment]
Make sure that the version of the game you load into the randomizer and the version of the game that you are playing on your 3DS/in Citra match. If they do *not* match, this ***will*** cause problems!

**Comment by tom-overton** [comment]
Gonna close this one out, as it has been over three months since my last reply with no further response. OP, please make sure the version of the game that is loaded in the randomizer is the same as the version that you are playing.
