### ISSUE TITLE
Invalid maximum heap size: -Xmx4608M The specified size exceeds the maximum representable size. Error: Could not create the Java Virtual Machine.

### ISSUE THREAD

**Issue by sylkreon** [Ajarmar/universal-pokemon-randomizer-zx#543]
**Describe the bug**
Hi, when I launch the randomizer, a error occurs, I don't really know why. All the information I could provide it's on the images

**To Reproduce**
1. Extract the .zip file
2. Click on launcher_WINDOWS
3. See error

**Expected behavior**
launcher_WINDOWS file should end with a .bat, but it doesn't, and then the error shows up.

**Screenshots**
If applicable, add screenshots to help explain your problem. (They are bellow)

**System (please complete the following information):**
 - Operating System: 
 - Java Version:
 - Randomizer Version: 
 
![imagen](https://user-images.githubusercontent.com/114200962/192033177-1d6170eb-9eae-4228-80f8-fb335894bc3a.png)
![imagen](https://user-images.githubusercontent.com/114200962/192033938-e30e4b2f-55ce-4eaa-8f57-9ee99aa5fc99.png)
![imagen](https://user-images.githubusercontent.com/114200962/192032978-80440ba0-4e5c-4d27-aea4-987a7346edaf.png)
![imagen](https://user-images.githubusercontent.com/114200962/192032876-41565c9e-9a8a-4197-be50-040e4aac83be.png)

**Comment by BJRironside** [comment]
> **Describa el error** Hola, cuando ejecuto el aleatorizador, ocurre un error, realmente no sé por qué. Toda la información que pude proporcionar está en las imágenes.
> 
> **Para reproducir** Pasos para reproducir el comportamiento:
> 
> 1. Extraiga el archivo .zip
> 2. Haga clic en lanzador_WINDOWS
> 3. ver error
> 
> **Comportamiento esperado El** archivo launcher_WINDOWS debería terminar con .bat, pero no es así, y luego aparece el error.
> 
> **Capturas** de pantalla Si corresponde, agregue capturas de pantalla para ayudar a explicar su problema. (Están abajo)
> 
> **Sistema (por favor complete la siguiente información):**
> 
> * Sistema operativo:
> * Versión Java:
> * Versión del aleatorizador:
> 
> ![imagen](https://user-images.githubusercontent.com/114200962/192033177-1d6170eb-9eae-4228-80f8-fb335894bc3a.png) ![imagen](https://user-images.githubusercontent.com/114200962/192033938-e30e4b2f-55ce-4eaa-8f57-9ee99aa5fc99.png) ![imagen](https://user-images.githubusercontent.com/114200962/192032978-80440ba0-4e5c-4d27-aea4-987a7346edaf.png) ![imagen](https://user-images.githubusercontent.com/114200962/192032876-41565c9e-9a8a-4197-be50-040e4aac83be.png)

Hola, yo tuve el mismo error, lo solucione reinstalando Java, puede que tengas instalado Java 32 bits y tu computador sea de 64 bits, busca la version adecuado y se soluciona.
Saludos

**Comment by DemonicDragon7111** [comment]
I am having the same issue please help.

**Comment by tom-overton** [comment]
This is a pretty common problem; it indicates that you have 32-bit Java installed instead of 64-bit Java. You can see our [Java wiki page](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java) for more info. I believe [this link](https://java.com/en/download/) should let you download 64-bit Java for Windows, but if it doesn't explicitly say "64-bit", then take a look at the Java wiki page for links to other versions of Java.
