### ISSUE TITLE
Error: could not open `C:\Program Files\Java\jre1.8.0_271\lib\amd64\jvm.cfg'

### ISSUE THREAD

**Issue by RaffaeleMelluso** [Ajarmar/universal-pokemon-randomizer-zx#547]

**Comment by RaffaeleMelluso** [comment]
This happens when i open launcher_WINDOWS, even with administrator

**Comment by tom-overton** [comment]
This indicates that Java is misconfigured on your system. Try some of the suggestions here: https://stackoverflow.com/questions/6036462/running-java-gives-error-could-not-open-c-program-files-java-jre6-lib-amd64
