### ISSUE TITLE
Unable to access jar file[Help] 

### ISSUE THREAD

**Issue by Kittichii** [Ajarmar/universal-pokemon-randomizer-zx#548]
I have windows and I have java but when I try to launch the windows Launcher I get this message.
I have reinstalled twice.
![Screenshot (2)](https://user-images.githubusercontent.com/114708402/193161505-1e86e0d0-8320-4300-af5b-ee6eac7a07b1.png)

**Comment by tom-overton** [comment]
You need to actually extract the randomizer from the .zip file. You can't just double-click on it while it's compressed.

**Comment by Kittichii** [comment]
I did
