### ISSUE TITLE
generate ".rnqs" file via cli

### ISSUE THREAD

**Issue by mattiaferrari02** [Ajarmar/universal-pokemon-randomizer-zx#551]
Is there a way to create a .rnqs file via cli passing also a setting string? (eg. 320WRIEEjIBAAQABwCRAAKeBnsECQEAFAACCQAuEgAAAAAABRi45ATkAYYICTIGBAIyAAUAEEZpcmUgUmVkIChVKSAxLjGwV2lQ48M4ig==)

**Comment by tom-overton** [comment]
There is no current way of doing this. If this is something you want to try to implement on your own, feel free to open a Contribution Idea.
