### ISSUE TITLE
Java cannot access the tmp folder during 3DS randomization

### ISSUE THREAD

**Issue by tealynx** [Ajarmar/universal-pokemon-randomizer-zx#554]
Hi there. I've been trying to randomize any 3DS game and keep running into the same error. While trying to save the randomized game, it stops after the tmp folder is created. This has happened with Pokemon Y, Alpha Sapphire, Moon and Ultra Sun, regardless of the ROM source and whether it was trimmed after decrypting or not. Attempting to save as CXI or Layered FS does not change the outcome either. All error reports show the same issue: "Caused by: java.io.FileNotFoundException: P:\PokeRoms\PokeRandoZX-v4_5_1\tmp_3DS0510PokemonYUSADecrypted\.code (Access is denied)"

Hopefully there is something that can be done to remedy this. I've attached one of the error reports as well. Many thanks for any insight.

 - Operating System: Windows 10
 - Java Version: 1.8.0_341, Java HotSpot(TM) 64-Bit Server VM
 - Randomizer Version: 4.5.1

[error_2022-10-12-11-59-50.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/9766739/error_2022-10-12-11-59-50.txt)

**Comment by tom-overton** [comment]
Can you try moving the randomizer to a different folder? I think this is a simple permissions issue with the folder that it is currently placed in.

**Comment by tom-overton** [comment]
I'm gonna close this one out since it's been two months without a response. If you do come back, let me know if that works for you.
