### ISSUE TITLE
[Help] versionLabel fires java.lang.NullPointerException

### ISSUE THREAD

**Issue by Ch41r05** [Ajarmar/universal-pokemon-randomizer-zx#560]
**Describe your problem clearly:** 
I'm trying to recompile the jar to try and implement a couple of functions that would be nice to have for me (for example, starters based on bst between 300 and 350, but randomized) but even when git cloning the master branch and exporting the jar, I can't get it to run correctly. I obviously use the run on windows bat to ensure everything is ok.

![image](https://user-images.githubusercontent.com/32594277/198160490-7618ded1-6f51-43fc-af25-d03fdbf50190.png)

The main class I'm using is com.dabomstew.pkrandom.newgui.NewRandomizerGUI which I saw was used in the manifest of the pre-compiled jar that works flawlessly on my machine.

**System (please fill in the following information):**
 - Operating System: Windows 11
 - Randomizer Version: 4.5.1
 - Java SDK: Eclipse Adoptium\jdk-17.0.5.8-hotspot

What I find strange, is that I can't see the component instantiated anywhere, nor do I see a pom.xml or something else that lets me think I'm missing some dependency.

**Comment by Ch41r05** [comment]
I could test on a friend of mine's pc which runs intellij and the jar was correctly produced. I deduce that this behavior is linked to intellij ui designer.

**Comment by Ajarmar** [comment]
Yes, the randomizer requires IntelliJ to build. You can read this for more information: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Building-Universal-Pokemon-Randomizer-ZX
