### ISSUE TITLE
trainer level increases are not 50% but 150% instead[Bug] 

### ISSUE THREAD

**Issue by vitotrue** [Ajarmar/universal-pokemon-randomizer-zx#561]
the randomized levels of the rival are compleatly fucked up, they are supposed to be the 50% higher of my strongest pokemon (my pokemon is lv 5 his whould be lv 8); but somehow whene i start a new run the pokemon level of the rival is de 50% higher than the level of HIS previus starter (my pokemon is lv5 and his would be lv 12 or even higher) i don't know if this is some randomized rule error or a rom error and i don't know how to fix it

this scenary continues to happen every time i randomizea fresh rom of pokemon fire red, i set that the levels of foe's pokemons are 50% higher than mine, but whene i load in the first time the levels are correct (my starter is level 5 and the rival's starter level is 8) but whene i restart the rom (i'm playng randomized nuzlock so i have to restart the game and randomize again the pokemons) the level of the rival's pokemon is 150% higher (my starter level is still 5 but the rival's starter level is 12)

**System (please complete the following information):**
 - Operating System: Windows 11 Pro, Version 21H2
 - Java Version :java version "1.8.0_351"
 - Randomizer Version:  4.5.1

**Comment by Fellshadow** [comment]
this means you're re-randomising the already randomised rom, which is stacking the level boost each time. Initially the rival mon is level 5, +50% -> level 8, if you then load up a rom that has already been randomised it'll see the rival has a level 8 and apply 50% which brings it up to level 12, and so on.

You need to load the original unrandomised rom (where the rival has a level 5 vanilla starter) into the randomiser for each new run you're doing and save the randomised rom as a different rom (don't overwrite the original). When you reset for a new run, load up that original rom again (not the randomised one) to make a new seed.

**Comment by tom-overton** [comment]
Yeah, what @Fellshadow said is correct. You need to load the original unrandomized ROM every time.
