### ISSUE TITLE
Windows launcher not working

### ISSUE THREAD

**Issue by Yerningcross8** [Ajarmar/universal-pokemon-randomizer-zx#563]
Every time I try to open the randomizer via the Windows launcher I get this message and can only close the program, the randomizer works fine through the jar but I do want to randomize 3ds games at some point.

Invalid maximum heap size: -Xmx4608M
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Press any key to exit...

**Comment by rom1x38** [comment]
Hi, I got the same error as you
Try to reinstall java, it worked for me

**Comment by Yerningcross8** [comment]
I just tried that and it still doesn't work for me, what version of Java do you have?

> Hi, I got the same error as you Try to reinstall java, it worked for me

**Comment by Spasminos** [comment]
It's not working for me either. That's really annoying.

**Comment by Spasminos** [comment]
> I just tried that and it still doesn't work for me, what version of Java do you have?
> 
> > Hi, I got the same error as you Try to reinstall java, it worked for me

My man, try using the Java Uninstall tool (https://www.java.com/en/download/uninstalltool.jsp) To clean out any older instances of Java.

**Comment by Yerningcross8** [comment]
> > I just tried that and it still doesn't work for me, what version of Java do you have?
> > > Hi, I got the same error as you Try to reinstall java, it worked for me
> 
> My man, try using the Java Uninstall tool (https://www.java.com/en/download/uninstalltool.jsp) To clean out any older instances of Java.

Thanks that actually worked, appreciate you my man
