### ISSUE TITLE
[Help] 

### ISSUE THREAD

**Issue by willywhisky** [Ajarmar/universal-pokemon-randomizer-zx#564]
**Describe your problem clearly:** 

**System (please fill in the following information):**
 - Operating System: 
 - Randomizer Version: 

**If your problem is that you can't randomize a game:**
If you get a popup saying that there has been an "unhandled exception", please attach the error log as an attached file to this issue.

**Comment by willywhisky** [comment]
Im trying to randomize a Hackrom for a tournament with my friends but the randomizer tell me that the ROM its not supported

**Comment by Linkdash2019** [comment]
did you do cxi or cia? It seems to need cxi

**Comment by tom-overton** [comment]
ROMhacks are not officially supported by the randomizer. That being said, it might be *un*officially supported, and the randomizer is just telling you "hey, this isn't official, just FYI". Either way, there's nothing I can do to help.
