### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Omnipotent-jinx** [Ajarmar/universal-pokemon-randomizer-zx#567]
I just installed the randomizer and when i clicked the launcher (i'm on mac OS) it came up with an error which wasn't on here and just said press enter to exit. Information below

MacOS
Java update 351
![Screen Shot 2022-11-04 at 06 58 04](https://user-images.githubusercontent.com/117681710/200399975-54048a21-5b43-45cb-b7fe-76adb2e90e67.png)

i've tried deleting and re-installing Java and the launcher, no use

**Comment by tom-overton** [comment]
This is caused by you not having Java 8 installed. I think on some older Macs, either Java 1.6 or 1.7 is installed by default. You'll need to install Java 8 or higher to use the randomizer.
