### ISSUE TITLE
[Help]When ever i double click the file this is what it says Invalid maximum heap size: -Xmx4608M The specified size exceeds the maximum representable size. Error: Could not create the Java Virtual Machine. Error: A fatal exception has occurred. Program will exit. Press any key to exit...

### ISSUE THREAD

**Issue by NycOtter** [Ajarmar/universal-pokemon-randomizer-zx#569]
**Describe your problem clearly:** 

**System (please fill in the following information):**
 - Operating System: 
 - Randomizer Version: 

**If your problem is that you can't randomize a game:**
If you get a popup saying that there has been an "unhandled exception", please attach the error log as an attached file to this issue.

**Comment by YourRival8** [comment]
I have the same problem, I have downloaded the newest version of the randomizer and I checked to see if java needed an update, neither fixed it.

**Comment by illonion** [comment]
**System**: Windows 10 (64-bit)
**Randomizer Version:** 4.5.1

Problem: opened launcher_WINDOWS.bat. This error message popped up:
```
Invalid maximum heap size: -Xmx4608M
The specified size exceeds the maximum representable size
Error: Could not create the Java Virtual Machine
Error: A fatal exception has occurred. Program will exit.
Press any key to exit...
```
![Error File](https://user-images.githubusercontent.com/60532041/201671604-3133bc09-7596-4a06-a432-fa5ae7341ce5.PNG)

**Comment by TheTap406** [comment]
same issue

**Comment by illonion** [comment]
Issue fixed! Please refer to https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/221.

**Comment by tom-overton** [comment]
Yeah, everyone involved here needs 64-bit Java. You can see our [Java wiki page](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/582) for more information. As @illonion said, this is all covered by the main launcher issue; thanks for linking it!

**Comment by ricasbp** [comment]
Best Randomizer project :)
