### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by greyfox004** [Ajarmar/universal-pokemon-randomizer-zx#570]
i go to launch the randomizer and in the command prompt i get this text.
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred.

**Comment by illonion** [comment]
Please refer to: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/221

**Comment by tom-overton** [comment]
As @illonion said, this is a common issue people have with the launcher. Please make sure you have a 64-bit version of Java installed.
