### ISSUE TITLE
[Help] [7th Gen] Wild Pokemon Database

### ISSUE THREAD

**Issue by LMHTPucho** [Ajarmar/universal-pokemon-randomizer-zx#572]
Hello!
I'm working into an app to show all the information wrote in the file.log created after randomize a 7th gen game. I'm trying to understand the wild pokemon sets / tables but it isn't clearly specified. If you or anyone have an idea to identifies the grass related to each table in log i'll be happy to hear it.

 - Operating System: Windows 10
 - Randomizer Version: 4.5.1
 - ROM: Pokemon Ultra Sun

**Comment by SpazzOutt** [comment]
Hey, I'm super sorry that I'm not giving you an answer to your questions but I see that you were able to get the gen 7 games to work. Was it the first games or the Ultra ones? I tried playing USUM but when I open the rom in the randomizer it always just says out of memory even though every other 3ds pokemon game works flawlessly.

**Comment by LMHTPucho** [comment]
> Hey, I'm super sorry that I'm not giving you an answer to your questions but I see that you were able to get the gen 7 games to work. Was it the first games or the Ultra ones? I tried playing USUM but when I open the rom in the randomizer it always just says out of memory even though every other 3ds pokemon game works flawlessly.

It was Ultra Sun and had no errors!

**Comment by tom-overton** [comment]
@LMHTPucho Unfortunately, Gen 7 encounter tables are extremely complicated, and we leave them as pretty generic "Table #X" in the logs for a reason; there's no real rhyme or reason behind how they're ordered internally. Things like surfing/berry trees/etc are *usually* in "later" tables for a given area, but it's not consistent, and as an example, the Wimpod encounter is in Table 1 on Route 8.

I can't really give you an answer for this, but you may be able to find some answers yourself by using [pk3DS](https://github.com/kwsch/pk3DS) and scrolling through the encounter tables in the wild encounter editor. They correspond very closely with what the output of our log files are.
