### ISSUE TITLE
I tried randomizing pokemon Ultra Moon but got this message: "There was an unhandled exception trying to load your rom".

### ISSUE THREAD

**Issue by PatoGanso420** [Ajarmar/universal-pokemon-randomizer-zx#575]
Every time i try to randomize my Ultra Moon copy i get this message, in the error file there´s really nothing i can do to identify the problem, any help will be aprecciated. Here´s the file:

[error_2022-11-19-02-38-54.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/10045884/error_2022-11-19-02-38-54.txt)

**Comment by tom-overton** [comment]
This is on a quite old version of the randomizer. I suspect the problem is something we actually fixed a long time ago. Grab the latest release [here](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases/tag/v4.5.1) and it should work. If it doesn't, just reopen this issue.
