### ISSUE TITLE
I tried to randomize pokemon Emerald but got this message: "There was an unhandled exception trying to save your rom into your disk"

### ISSUE THREAD

**Issue by PatoGanso420** [Ajarmar/universal-pokemon-randomizer-zx#576]
Every time i try to save my pokemon Emerald rom into my disc a get this message, my device is a windows64bits and i have the randomizer version 4.0.0, there also the bug report if that could help.
[error_2022-11-19-02-52-40.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/10045913/error_2022-11-19-02-52-40.txt)

**Comment by gr3ger** [comment]
I'd try the latest build. You're using a 2 year old version.

**Comment by tom-overton** [comment]
Yeah, I'm going to close this one out, since it's running an ancient build of the randomizer. Please try it on the latest version (v4.5.1).
