### ISSUE TITLE
Pokemon XY randomizing on macOS hangs on black screen after the Nintendo 3DS logo

### ISSUE THREAD

**Issue by techmuse8** [Ajarmar/universal-pokemon-randomizer-zx#58]
I randomized Pokemon Y (0004000E00055E00) on macOS 10.16 with update 1.5 and after randomizing and loading the game with Luma3DS 10.2 it hangs on a black screen after the Nintendo 3DS logo, tested this on Windows 10 with the same files and I don't get the same issue. I'll attempt this on 10.15 and see what happens there.

**Comment by tom-overton** [comment]
I don't think the OS the randomizer is running on has anything to do with the crash. Can you try the following?
1. First, just make sure that version 1.5 is installed on your 3DS. Try deleting the layeredFS and booting it normally; you should see the string "Ver. 1.5" on the file select screen. I just want to be sure that the version on the 3DS matches the version you're using in the randomizer.
2. Assuming that, yes, you have version 1.5 installed on your 3DS, make a new version 1.5 seed and make sure to save a log. If that still hangs on a black screen, send me the log file and I'll see if I can recreate it.
3. Assuming that you still hang on a black screen in step 2, try deleting the update from your 3DS and making a version 1.0 seed. [We have a section on the wiki about how to delete updates on a 3DS](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Randomizing-the-3DS-games#managing-game-updates-on-a-3ds). If *that* hangs on a black screen, then it's not related to game updates at all.

**Comment by techmuse8** [comment]
Couldn't reproduce, got it working.
