### ISSUE TITLE
[Bug] B2W2 Pokedex Habitat Mode still shows vanilla locations of pokemon

### ISSUE THREAD

**Issue by f-raZ0R** [Ajarmar/universal-pokemon-randomizer-zx#580]
**Describe the bug**
With wild pokemon randomized, looking at the habitat mode of the pokedex will, instead of showing the actual locations of pokemon, will show the **vanilla** locations of them.

**To Reproduce**
1. Open the Pokedex
2. Change the mode to "Habitat"
3. View the Wild Pokemon of any area.
4. See inaccurate pokemon data.

**Expected behavior**
The habitat mode of the pokedex would be factored into the randomization of pokemon, instead of it just showing the vanilla values.

**Screenshots**
![Screenshot (1121)](https://user-images.githubusercontent.com/30442287/205519411-06c9e2b2-0c55-4628-849b-f111d9602995.png)

(route 19 in this seed has hoppip and shroomish as grass wilds, both of which are seen, and yet neither are showing up.)

**System (please complete the following information):**
 - Operating System: Win10
 - Java Version: 17 I think? There's some nonsense I've done with old minecraft versions where I have multiple different versions of java installed. 17 is one of them and is probably the one loaded so I'm going to go with 17.
 - Randomizer Version: 4.5.1

**Additional context**
The pokemon themselves are still randomized. The area tab functions just fine, and shows a pokemon's new habitat. It is specifically, the Habitat mode, that is incorrectly displaying vanilla info when it shouldn't.

Issue was encountered in melonDS, will attempt to replicate on actual hardware shortly.
log file for seed:
[eta.nds.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/10149635/eta.nds.log)
This might be specifically because of the 1:1 global setting? Unsure, might do some more testing to narrow down whether or not it always happens, later.

**Comment by f-raZ0R** [comment]
If more details are needed please let me know, and I will happily provide them.

**Comment by f-raZ0R** [comment]
![image](https://user-images.githubusercontent.com/30442287/205666369-41a4d7b5-5d60-498b-a722-a72f090c4bee.png)
Can replicate issue on real hardware. 
(Don't ask me about bypassing AP that took me like 8 hours to do because the twilightmenu ap patch seems to not work with my dump of the game and instead white screens. I even tried just putting an actual W2 cart into slot 1, as the AP is triggered by a lack of an IR sensor, but nope, that still triggered it for some reason.)

**Comment by tom-overton** [comment]
Thanks for the report. It turns out that we actually tried this in the past, and it causes game crashes: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/blob/master/src/com/dabomstew/pkrandom/romhandlers/Gen5RomHandler.java#L1117-L1118

For now, I've put this on the [Known Issues](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Known-Issues#black-2white-2) list, since it's not something we're likely to get to. Perhaps some day I'll investigate how to prevent the crash, but this is a pretty niche feature.
