### ISSUE TITLE
Add support for SpeedChoice ROM Hacks

### ISSUE THREAD

**Issue by entropiccode** [Ajarmar/universal-pokemon-randomizer-zx#583]
Not a bug and not really a contribution request, I'm merely curious to know if there are plans to add support for the SpeedChoice ROM hacks in the future, SpeedChoice Red and SpeedChoice Crystal in particular.

There is a fork of the original UPR that supports SpeedChoice, however it offers the same limited randomization options as the original UPR and has not been updated in 2 years.  SpeedChoice Emerald and Emerald EX also offer compiled versions of this fork with their releases.  The randomizer available with SpeedChoice Emerald is version SPDC-20210315 and also supports Red and Crystal (personally tested) and likely also Ruby and FireRed, whereas the Emerald EX randomizer is version v2.0.0-alpha and only supports Emerald EX.

Links for reference:
SpeedChoice fork of UPR: https://github.com/Dabomstew/UPR-Speedchoice
SpeedChoice Red: https://github.com/Dabomstew/pokered-speedchoice
SpeedChoice Crystal: https://github.com/Dabomstew/pokecrystal-speedchoice
SpeedChoice Ruby: https://github.com/ProjectRevoTPP/pokeruby-speedchoice
SpeedChoice Emerald: https://github.com/ProjectRevoTPP/pokeemerald-speedchoice
SpeedChoice Emerald EX: https://github.com/ProjectRevoTPP/pokeemerald-ex-speedchoice
SpeedChoice FireRed: https://github.com/PikalaxALT/firered-speedchoice

**Comment by tom-overton** [comment]
Sorry, but we have no plans for adding SpeedChoice support to the randomizer, for two main reasons:
1. We have our hands full with the official games already
2. SpeedChoice ROMs are liable to change at any moment, which might require updates to the randomizer to function. And given our glacial pace of releasing updates, this is probably not a good thing.
