### ISSUE TITLE
[Bug] HeartGold Double Battle Mode

### ISSUE THREAD

**Issue by Ikkisoad** [Ajarmar/universal-pokemon-randomizer-zx#584]
When entering a double battle with all pokemons fainted but one, you are pretty much soflocked as shown on this video:
https://youtu.be/-sKPc4uo0aw?list=PL_xoVgMmtPRRZez_9hU75ND30TJLnc2ih&t=3982

If you attack the game crashes, that ROM was made using version 4.2.

Today I tested the same thing with a ROM randomized with the latest randomizer version, and the game crashes just as the fight is starting: https://youtu.be/VQqe0n_OBGI

This really is avoidable but this mode is really fun and I hope there is a fix for this.

**Comment by tom-overton** [comment]
We warn about this directly in the tooltip:
![image](https://user-images.githubusercontent.com/12245827/209290635-cfba6142-cdf4-49f5-94c6-00202e2b540c.png)

As of now, the fix is to make sure you have two Pokemon when you enter a trainer battle.
