### ISSUE TITLE
No idea why this wont work

### ISSUE THREAD

**Issue by NickE3472** [Ajarmar/universal-pokemon-randomizer-zx#589]
Every time I try to open the application I get an error message that says "Unable to install Java There are errors in the following switches: "C:Users/eefst/Desktop/Jav/launcher.jar" Check that the commands are valid and try again" no idea why or how to fix it

**Comment by tom-overton** [comment]
A quick google search brought this up: https://www.repairwin.com/fix-java-installation-not-completed-unable-to-open-java-jar-files/

Also, are you using the latest version of the randomizer? We haven't had something called `launcher.jar` for quite some time.
