### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SeifoMowafi05** [Ajarmar/universal-pokemon-randomizer-zx#59]
I'm trying to randomize this rom but i get this error:

 Randomizer Version: 4.0.1
Seed: 211925686322881
Settings String: 4.0.1IQgEAUJEAQoAvwIEAAKtJAjCKQAAKQAVAQABMgAAAAAAAgAIvNG8wVoJCTIHBxZQb2tlbW9uIEFscGhhIFNhcHBoaXJl2V3XsuPDOIo=
ROM: Pokemon Alpha Sapphire
Code: CTR-P-ECLA
Reported Support Level: Complete

java.lang.NullPointerException
	at com.dabomstew.pkrandom.romhandlers.Gen6RomHandler.getStaticPokemon(Gen6RomHandler.java:1774)
	at com.dabomstew.pkrandom.Randomizer.maybeChangeAndLogStaticPokemon(Randomizer.java:897)
	at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:395)
	at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$performRandomization$99(NewRandomizerGUI.java:830)
	at java.lang.Thread.run(Unknown Source)

**Comment by tom-overton** [comment]
I cannot reproduce this with my copy of Alpha Sapphire. Here is a log demonstrating that with the same version, seed, and settings, I can randomize the game successfully:
[test.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5538869/test.log)

Can you try the following?
1. Update the randomizer to version 4.0.2. I actually doubt think this will help, but it makes debugging a little easier when you're on the latest version
2. Can you try a different Alpha Sapphire ROM? The only difference between you and me is our ROM, so my suspicion is that your ROM is incorrect in some way.

**Comment by SeifoMowafi05** [comment]
> I cannot reproduce this with my copy of Alpha Sapphire. Here is a log demonstrating that with the same version, seed, and settings, I can randomize the game successfully:
> [test.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5538869/test.log)
> 
> Can you try the following?
> 
> 1. Update the randomizer to version 4.0.2. I actually doubt think this will help, but it makes debugging a little easier when you're on the latest version
> 2. Can you try a different Alpha Sapphire ROM? The only difference between you and me is our ROM, so my suspicion is that your ROM is incorrect in some way.

Well I have a Pokémon Alpha sapphire but it’s working I have some files that turn it into a rom hack. When I put those files it works but when I try to randomize the whole rom in the end it gives me the error

**Comment by tom-overton** [comment]
We don't support any ROM hacks - it's simply too much work to add support for new games and there are too many ROM hacks out there. Furthermore, ROM hacks may have issues that don't occur in the regular games, which require even more work. If the original version of Pokemon Alpha Sapphire is functioning correctly for you, then there is no issue here.
