### ISSUE TITLE
[Bug] Error when exporting

### ISSUE THREAD

**Issue by pikscast** [Ajarmar/universal-pokemon-randomizer-zx#590]
I get an error when I try to export randomized Alpha Sapphire. I am using a 3ds file dumped from my own cartridge, and an update dumped from my 3ds.
[error_2023-01-01-16-47-56.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/10329516/error_2023-01-01-16-47-56.txt)

**Comment by tom-overton** [comment]
Thanks for the report! Fixed the issue and it will be in the next release. For now, you can avoid this crash by either (a) disabling Limit Pokemon, *or* (b) disabling Swap Mega Evolvables.
