### ISSUE TITLE
BAT file wont launch the randomizer

### ISSUE THREAD

**Issue by Mantra1776** [Ajarmar/universal-pokemon-randomizer-zx#592]
When i launch using the windows cmd it just says

Invalid maximum heap size: -Xmx4608M
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Press any key to exit...

any clue how to fix this?? Never had this issue before.

**Comment by Fellshadow** [comment]
you have 32-bit java installed, you need 64-bit for the randomiser. For more info there's a [java section](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java) on the wiki pages

**Comment by tom-overton** [comment]
Yep, that's correct. Thanks @Fellshadow for responding to this!
