### ISSUE TITLE
[Bug] 100% Catch rate in Pokémon X & Y

### ISSUE THREAD

**Issue by Quagsiree** [Ajarmar/universal-pokemon-randomizer-zx#594]
**Describe the bug**
All randomized X & Y roms i make, the catch rate is set to 255 (always catches) and yeah, i don't even change the minimal Catch Rate.

**To Reproduce**
1. I Randomize a X or Y rom.
2. I Get the CXI or RomFs file.
3. Start the game and pass through until receive Pokéballs
4. Catch all the Pokémon that i throw a pokeball at.

**Screenshots**
On the screenshots i am with a lv 6 Salamence (which don't make any difference) i caught 5 Tyrogues with Full HP and 1 Pichu also with Full hp, (the others pokémon that is in the final screenshot are from route 2 that pokémon can't broke the pokéball.) 
 
**System (please complete the following information):**
 - Operating System: Processor Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz  1.99 GHz 
 - RAM 4,00 GB 
 - System 64 bits
 - Java Version: Java 8 Version 333
 - Randomizer Version: v4.5.1

**Additional context**
![Bug Report](https://user-images.githubusercontent.com/110263070/211627841-86d49ef2-333f-4067-bdbf-57eeb01cdc67.png)
![Bug Report2](https://user-images.githubusercontent.com/110263070/211627865-f07c6b05-afbd-42b5-80e7-34d21082d46d.png)
![Bug Report3](https://user-images.githubusercontent.com/110263070/211627873-8b38e1ac-59cc-4e52-9484-88a3a9aa43c2.png)
![Bug Report4](https://user-images.githubusercontent.com/110263070/211627876-bb63c607-db51-424c-bd17-0868fd7b3181.png)
![Bug Report5](https://user-images.githubusercontent.com/110263070/211627877-a90e252b-e2b4-429b-830e-121ddf43fe1b.png)
![Bug Report7](https://user-images.githubusercontent.com/110263070/211627885-56ff2af0-47e4-4c44-944e-ca3d9d1ee51b.png)
![Bug Report8](https://user-images.githubusercontent.com/110263070/211627890-947cddd2-638a-4d8b-af20-dd1dba891729.png)
![Bug Report9](https://user-images.githubusercontent.com/110263070/211627894-8a4a1b27-71de-4a57-87a8-acc688945157.png)
![Bug Report10](https://user-images.githubusercontent.com/110263070/211627897-50be3a5f-66bc-47d5-910e-3e286a2b0b20.png)
![Bug Report11](https://user-images.githubusercontent.com/110263070/211627899-2f425c50-8798-4635-ade3-d46a5cbe1109.png)
![Bug Report12](https://user-images.githubusercontent.com/110263070/211627904-12c55fdd-0b42-4af2-99e9-201193c81889.png)
![Captura de tela 2023-01-10 144818](https://user-images.githubusercontent.com/110263070/211627933-f1df19b0-43fe-4dde-b9e0-251b37e2e391.png)

And This is the Rom i been using to Randomize my games.
https://drive.google.com/file/d/1skQ04_OzOwnOIGYkM0iSQSl1NbZIcdlz/view?usp=sharing

Is there something wrong?

**Comment by tom-overton** [comment]
Can you provide a log file for one of the randomizations you created? I want to see if I can replicate the issue.

**Comment by KyleTheMan4444** [comment]
Pokemon in Santalune Forest are a guaranteed catch even in the base game. Maybe try catching Pokemon in other locations and see if they break out.

**Comment by Quagsiree** [comment]
> Pokemon in Santalune Forest are a guaranteed catch even in the base game. Maybe try catching Pokemon in other locations and see if they break out.

i discovered that tonight, i hate my life i am a dumbass (it's a joke by the way, except the dumbass one)
thank you guys!
