### ISSUE TITLE
[Help] java error when launching (windows) randomizer "Comparison method violates its general contract!"

### ISSUE THREAD

**Issue by adamajh92** [Ajarmar/universal-pokemon-randomizer-zx#597]
**Describe your problem clearly:** 
When launching the windows launcher, i keep getting the error "Comparison method violates its general contract!" with a wall of text (sc below)
**System (please fill in the following information):**
 - Operating System: win 11
 - Randomizer Version: 4.5.1

**If your problem is that you can't randomize a game:**
If you get a popup saying that there has been an "unhandled exception", please attach the error log as an attached file to this issue.
![error](https://user-images.githubusercontent.com/122816306/212729882-36845f30-15c8-4d28-b731-9fa0bbd87724.png)

**Comment by adamajh92** [comment]
*have uninstalled and reinstalled java 64 bit and restarted my system

**Comment by tom-overton** [comment]
We have seen this before, but without a very clear solution: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/509

Can you open the command prompt and run `java -version` for me? I don't really know how to fix this issue, but this would be a decent place to start.

**Comment by adamajh92** [comment]
> 

I would, but I already did a fresh start on my PC several hours ago. It is working now.

**Comment by tom-overton** [comment]
Well, I'm glad it's working! I wish we could actually diagnose this problem in greater detail, but oh well. All's well that ends well.
