### ISSUE TITLE
[Bug] Randomize Starter Held Items setting fails to save/load from an RNQS file

### ISSUE THREAD

**Issue by UTDZac** [Ajarmar/universal-pokemon-randomizer-zx#601]
**Describe the bug**
Enabling the new 4.6.0 setting for "Randomize Starter Held Items" does not persist in an RNQS settings save file.

**To Reproduce**
1. Load a Pokémon Platinum game ROM into the Randomizer
2. Manually enable the "Randomize Starter Held Items" setting found under the "Starters, ..." tab
3. Click "Save Settings" and create an RNQS settings save file
4. Close & re-open the Randomizer Program
5. Repeat step 1
6. Click "Load Settings" and load the file created in step 3

**Expected behavior**
The "Randomize Starter Held Items" setting adjusted in step 2 should be still be enabled after loading that settings file. The setting should be reflected in the RNQS save file that is created.

Note: This appears to work fine if you use a Settings String instead, however that is undesirable when using external programs that rely on an RQNS settings file.

**Screenshots**
![image](https://user-images.githubusercontent.com/4258818/218280645-547da155-5258-41d2-8d3b-83880e8b3ab0.png)

**System (please complete the following information):**
 - Operating System: Windows 10
 - Java Version: 1.8.0_351
 - Randomizer Version: 4.6.0

**Comment by Ajarmar** [comment]
Thanks, will be fixed in the next release
