### ISSUE TITLE
[Help] 

### ISSUE THREAD

**Issue by AgileLion1** [Ajarmar/universal-pokemon-randomizer-zx#604]
Hello everytime I go to launch using the windows launcher (I am on windows 11) I get this error 

Invalid maximum heap size: -Xmx4608M
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Press any key to exit...

**Comment by UTDZac** [comment]
This means that you need to install 64-bit Java Offline. Make sure you get the offline version. You can get it from the official java site: [https://www.java.com/en/download/manual.jsp](https://www.java.com/en/download/manual.jsp)
