### ISSUE TITLE
Could not create the Java Virtual Machine. [Bug] 

### ISSUE THREAD

**Issue by zkozzy** [Ajarmar/universal-pokemon-randomizer-zx#608]
Whenever I try to run the randomizer through the .bat file I get this screen: 

**To Reproduce**
1. Unzip the .zip-file
2. Run launcher_WINDOWS.bat
3. cmd-screen pops up saying:
> Invalid maximum heap size: -Xmx4608M
> The specified size exceeds the maximum representable size.
> Error: Could not create the Java Virtual Machine.
> Error: A fatal exception has occurred. Program will exit.
> Press any key to exit...
![image](https://user-images.githubusercontent.com/118555083/225322041-485254a4-199e-4392-a4e8-333b49a12718.png)

**System (please complete the following information):**
 - Operating System: Windows 10
 - Java Version: 8 Update 361
 - Randomizer Version: 4.6.0

All the files from the .zip remain in the same folder.

**Comment by Fellshadow** [comment]
you have 32-bit java installed, you need 64-bit offline java. For more info there's a [java section](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java) on the wiki pages
