### ISSUE TITLE
Certain Aspects of OR/AS not randomizing properly

### ISSUE THREAD

**Issue by AurangeJuice** [Ajarmar/universal-pokemon-randomizer-zx#61]
Hi, I recently tried this randomizer out on Alpha Sapphire with settings to randomize the starters, wild encounters, trainer pokemon and trainer names, pokemon typings and abilities, movesets, items and TMs, and shop items. However, some of these settings did not function properly. For one, the starters did not randomize. Their typings and abilities did, but I still got Treeko, Torchic, and Mudkip no matter how many times I re-randomized. TMs also did not change, though items did. Shop items did also not randomize correctly. I did check my randomization log to make sure these settings were on, and according to the log they were supposed to have been changed, but I am not seeing those changes within my game.

[Alpha Sapphire randoo.cxi.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5541791/Alpha.Sapphire.randoo.cxi.log)

**Comment by tom-overton** [comment]
I'm fairly certain what's happening is that you have a game update installed in Citra or on your 3DS. See if you have something like "Ver 1.5" on the file select screen like this:

![image](https://user-images.githubusercontent.com/12245827/97775269-90f5e380-1b1c-11eb-98de-e482b1db036b.png)

If you have a game update installed in Citra or on your 3DS, you have two options:
1. Delete the game update. You can follow the instructions [here](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Randomizing-the-3DS-games#managing-game-updates-in-citra) to delete it
2. Load a CIA of the same game update inside the randomizer. You can follow the instructions [here](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Randomizing-the-3DS-games#3ds-game-updates) to load it

**Comment by AurangeJuice** [comment]
I do have a 1.4 version here:

![image](https://user-images.githubusercontent.com/73694325/99181774-57b19c00-26f6-11eb-979a-4c4d713d8d7d.png)

Thank you, I'll try that!

**Comment by tom-overton** [comment]
@AurangeJuice Did it end up working? If so, I'll close this issue

**Comment by AurangeJuice** [comment]
My bad, forgot to reply! Yes, it did work. Thanks for the help!
