### ISSUE TITLE
[Help] windows .bat won't lauch the randomizer

### ISSUE THREAD

**Issue by jonnitor06** [Ajarmar/universal-pokemon-randomizer-zx#613]
I downloaded the zip and extracted it and tried to lauch it using the .bat file since I am on windows, but all I get when I try to launch is this: 
![Screenshot 2023-04-06 170823](https://user-images.githubusercontent.com/130104270/230494404-adafa009-5e05-413f-99c2-e55380d7681f.png)

I tried bypassing by lauching the .jar instead, but then it won't load the rom. I have uninstalled and reinstalled java but that hasn't worked either. I have another randomizer that I use that is just a .exe but it doesn't work with .3ds files. I don't know much about coding but why not use an exe? This is just confusing to me.

**Comment by TheRobLP** [comment]
Hey there. I just happened to stumble upon this. It may be that you are using a 32 Bit version of Java. This version can't use more then 4 Gigabyte of RAM. Either download and install the 64-Bit version of Java (Requires Windows 7 or higher) or lower the -Xmx value in the .bat file to 4096 (To avoid issues I woulsd suggest using 4000 instead). You can check if you have 32-Bit or 64Bit by pressing Windows + R and typing cmd into the dialogue box. Then in the black window type in `java --version` it will either say 32-Bit or 64-Bit
