### ISSUE TITLE
[Help] windows launcher not working

### ISSUE THREAD

**Issue by CutePandaZ** [Ajarmar/universal-pokemon-randomizer-zx#615]
i use windows
the latest version of the randomizer 

im trying to randomize 3ds games 
and the launcher is not working its giving me this error: 
![image](https://user-images.githubusercontent.com/130249159/230739708-d14be8ff-8072-4c23-986d-d32e8ce72b34.png)

**Comment by jonnitor06** [comment]
Having the same issue

**Comment by tychii93** [comment]
That's because you're using the 32bit version of the Java runtime.  I had this too so I installed the 64bit version and it worked after that.  Choose Windows Offline 64-bit from here.
https://www.java.com/en/download/manual.jsp

**Comment by DRogueRonin** [comment]
The wiki has a `About Java` section here: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java
