### ISSUE TITLE
Is the universal randomizer able to be run on official hardware without citra or any other emulator?

### ISSUE THREAD

**Issue by sauceerr** [Ajarmar/universal-pokemon-randomizer-zx#617]
seems like a stupid question but i am new to this and am very curious.

**Comment by DRogueRonin** [comment]
Depends on what you mean by "official hardware". I installed a custom firmware on my 3DS like this: https://3ds.hacks.guide/

And then I moved a decrypted and randomized ROM to my SD Card, put the SD Card in my 3DS and could play the randomized game just fine.

**Comment by tom-overton** [comment]
Yes, as stated, check the wiki.
