### ISSUE TITLE
Issue with File Extraxtion

### ISSUE THREAD

**Issue by Galloran-Thirio** [Ajarmar/universal-pokemon-randomizer-zx#62]
My problem right now is when I extract the downloaded zip file, instead if it extracting the launcher.jar, readme, and pokerandozx. I instead get another set of zip files titled launcher and pokerandozx, which again are both zip files instead of an executable file. After this happens I try to extract the two new zip files and I still cannot use the launcher.

**Comment by Ajarmar** [comment]
This can happen if you have a program other than Java assigned as the "default program" for JAR files. If you right click on a JAR file, click "Open with" and choose to open it with Java, you should be able to run the program. (You should also be able to set Java as the default program.)

If you don't have Java installed, read this page for more info: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java

**Comment by Galloran-Thirio** [comment]
Thanks for the answer! It also helped me realize that the reason it was opening the way it was, was because I was using WinRAR as well. As soon as I uninstalled WinRAR the program worked!

**Comment by Ajarmar** [comment]
Great! Closing this issue.
