### ISSUE TITLE
[Bug] ""Java" is not recognized as an internal or external command"

### ISSUE THREAD

**Issue by ReallyNotBob** [Ajarmar/universal-pokemon-randomizer-zx#622]
I am trying to install v4_6 of the randomizer on windows, and when I open the .bat file, I get the the message: 'java' is not recognized as an internal or external command,
operable program or batch file.

![image](https://user-images.githubusercontent.com/97850209/235265011-f38eaed2-5962-4d15-ab0c-f192554eca7c.png)

 - Operating System: Windows 10
 - Java Version: 1.8.0_371
 - Randomizer Version: 4.6

**Comment by BadThehalfbreed** [comment]
You don't have java installed, download it and it will fix your problem

**Comment by Onre64** [comment]
i have the same problem
But Java is installed by me i can open the .jar and randomize nds and lower fine but if a try run the .bat file it says Java is not a command
