### ISSUE TITLE
3ds problem

### ISSUE THREAD

**Issue by schyx08** [Ajarmar/universal-pokemon-randomizer-zx#630]
when i put my 3ds Saphire ROM the randomizer seys: '' The randomizer was not started via the launcher. You will not be able to load 3ds games into the randomizer''. what did i should do? (sorry for the bad inglish im italian)

**Comment by DRogueRonin** [comment]
You have to use the appropriate launcher to start the program, don't use the `.jar` file directly.

Instead run `launcher_MAC.command` if you are on macOS, `launcher_UNIX.sh` when on Linux or the `launcher_WINDOWS.bat` when using Windows.
