### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by xSnags** [Ajarmar/universal-pokemon-randomizer-zx#632]
![Screenshot 2023-06-04 215210](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/assets/43101819/31c45158-56eb-4d30-aab9-a84b46bbdec4)

**Comment by DRogueRonin** [comment]
Maybe you have this https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/615#issuecomment-1505525901 problem.
