### ISSUE TITLE
[Bug] When i start my launcher with the rom I want to use it is just saying" Press any key to exit" and doesent start anithing

### ISSUE THREAD

**Issue by Kevvtm** [Ajarmar/universal-pokemon-randomizer-zx#636]
**Describe the bug**
When I start my launcher with the rom I want to use it is just saying" Press any key to exit" and doesent start anithing.

**Expected behavior**
should launch the rom

**Screenshots**
![Java](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/assets/136357038/58560881-49a1-486d-b6da-74136b30a20e)

**System (please complete the following information):**
 - Operating System: windows 10
 - Java Version:  1.8.0_371-b11
 - Randomizer Version: 4.6.0

**Comment by DRogueRonin** [comment]
Here https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/606 someone got it working with the same error message. Their error apparently was that they didn't install java correctly. Maybe try reinstalling java.

Also the wiki has an [About Java](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java) section. Maybe you can find more info there.

**Comment by Kevvtm** [comment]
ok thanks its working now
