### ISSUE TITLE
[Help] 

### ISSUE THREAD

**Issue by Irrazional** [Ajarmar/universal-pokemon-randomizer-zx#637]
**Describe your problem clearly:** Is the shiny rate boosted like the original when I SOS chain in USUM when it's randomized?

**System (please fill in the following information):**
 - Operating System: Windows
 - Randomizer Version: 4.6.0

**If your problem is that you can't randomize a game:**
If you get a popup saying that there has been an "unhandled exception", please attach the error log as an attached file to this issue.

**Comment by tom-overton** [comment]
Shiny odds are completely unchanged, which means yes, the SoS chain gives boosted shinies
