### ISSUE TITLE
[Help] question about txt file

### ISSUE THREAD

**Issue by Drenatheon** [Ajarmar/universal-pokemon-randomizer-zx#638]
i got a question about the txt file if i randomize a game.
after i randomized the starters it says in the file "set starter 1/2/3 to "..." ", which are the starters in the game but in the file are 12 starters and i wanted to know what the other ones mean because i can't get them as starters.
here is the example of my txt file :

--Random Starters--
Set starter 1 to Natu
Set starter 2 to Regice
Set starter 3 to Archeops
Set starter 4 to Cubchoo
Set starter 5 to Giratina
Set starter 6 to Meditite
Set starter 7 to Manaphy
Set starter 8 to Snover
Set starter 9 to Kabuto
Set starter 10 to Pancham
Set starter 11 to Mareep
Set starter 12 to Meloetta

**Comment by tom-overton** [comment]
I'm assuming this is ORAS, and that's just because that game has a bunch of starters. The values are:
1. Treecko
2. Torchic
3. Mudkip
4. Chikorita
5. Cyndaquil
6. Totodile
7. Turtwig
8. Chimchar
9. Piplup
10. Snivy
11. Tepig
12. Oshawott
