### ISSUE TITLE
[Help] Problem with launcher_WINDOWS.bat

### ISSUE THREAD

**Issue by MysticTalion** [Ajarmar/universal-pokemon-randomizer-zx#642]
Hi, I tried to use the randomizer by launching the **launcher_WINDOWS.bat** file, but I always got the same error...
Is there a solution to this problem ?

 Windows 11
 - Randomizer Version: [v4.6.0](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/tree/v4.6.0)

![image](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/assets/35067767/78755029-1696-4ddf-a75c-6cc0cd43fbbf)

**Comment by ClintB1990** [comment]
I am having the exact same issue

**Comment by tom-overton** [comment]
This means that you need to install 64-bit Java Offline. Make sure you get the offline version. You can get it from the official java site: [https://www.java.com/en/download/manual.jsp](https://www.java.com/en/download/manual.jsp)

You can read more about the Randomizer program's requirements here: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java#java-requirements
