### ISSUE TITLE
Problem with launcher

### ISSUE THREAD

**Issue by DinoPersn** [Ajarmar/universal-pokemon-randomizer-zx#643]
Invalid maximum heap size: -Xmx4608M
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Press any key to exit...

**System (please complete the following information):**
 - Operating System: WinX64
 - Java Version:8
 - Randomizer Version: 4.6.0

**Additional context**

**Comment by tom-overton** [comment]
This means that you need to install 64-bit Java Offline. Make sure you get the offline version. You can get it from the official java site: [https://www.java.com/en/download/manual.jsp](https://www.java.com/en/download/manual.jsp)

You can read more about the Randomizer program's requirements here: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java#java-requirements
