### ISSUE TITLE
[Bug] Game crashes when catching tutorial tries to start

### ISSUE THREAD

**Issue by Spas120** [Ajarmar/universal-pokemon-randomizer-zx#654]
I'm using the latest version if the randomizer and I'm using pokemon black2/white2 and when ever i get to the catching tutorial it crashes and idk what the problem is since i been using this randomizer for a long time now

**Comment by wwtepicfail** [comment]
It is caused by the "Fix Music" option (#603). For now, just disable it.

**Comment by Spas120** [comment]
> It is caused by the "Fix Music" option (#603). For now, just disable it.

Oh alright, Thanks

**Comment by tom-overton** [comment]
Sorry for the huge delay! This is fixed now and will be in the next release
