### ISSUE TITLE
Pure Power and Huge Power aren't combined. [Bug] 

### ISSUE THREAD

**Issue by Gobl943** [Ajarmar/universal-pokemon-randomizer-zx#670]
I'll keep this one simple. The "Combine Duplicate Abilities" option doesn't combine Huge Power/Pure Power despite them being the same ability. How to recreate? Easy. Just randomize the game and look at the log file. Small quirk, but kinda funny.

**Comment by tom-overton** [comment]
Do you mean that Huge Power and Pure Power appear on the same Pokemon? Or that Huge Power and Pure Power appear within the same seed? Because the latter is entirely expected.

**Comment by tom-overton** [comment]
Actually, the former is expected too. There's a separate bug where, rarely, it could pick Huge Power on the same Pokemon twice, which I fixed. But yeah, a Pokemon having both Huge and Pure Power is expected.

**Comment by Gobl943** [comment]
> Do you mean that Huge Power and Pure Power appear on the same Pokemon? Or that Huge Power and Pure Power appear within the same seed? Because the latter is entirely expected.

Same seed despite the "Combine Duplicate Abilities" option being selected. The same thing happens with Wimp Out and Emergency Exit when randomizing the Gen 7 games with both abilities appearing on the same seed. All others are combined.

**Comment by tom-overton** [comment]
Yeah, that is entirely expected. Imagine a game with only three abilities: Drought, Huge Power, and Pure Power. If we just pick abilities randomly, you have:
- 1/3 chance of getting Drought
- 1/3 chance of getting Pure Power
- 1/3 chance of getting Huge Power

However, that means that you have a 2/3rds chance of getting an "attack doubling" ability. So what the "Combine Duplicate Abilities" setting does is fix that; it treats them as one ability when selecting between all other abilities. So you would instead get:
- 1/2 chance of getting Drought
- 1/2 chance of getting an "attacking doubling" ability.

However, once we've picked an "attack doubling" ability, we then randomly pick *which* attack doubling ability to use randomly. So it is entirely expected to see both Huge and Pure Power in the same seed; this is 100% expected and won't change. What "Combine Duplicate Abilities" does is adjust *how often* Huge Power and Pure Power appear by adjusting the probability of their appearances.

**Comment by Gobl943** [comment]
> Yeah, that is entirely expected. Imagine a game with only three abilities: Drought, Huge Power, and Pure Power. If we just pick abilities randomly, you have:
> 
> * 1/3 chance of getting Drought
> * 1/3 chance of getting Pure Power
> * 1/3 chance of getting Huge Power
> 
> However, that means that you have a 2/3rds chance of getting an "attack doubling" ability. So what the "Combine Duplicate Abilities" setting does is fix that; it treats them as one ability when selecting between all other abilities. So you would instead get:
> 
> * 1/2 chance of getting Drought
> * 1/2 chance of getting an "attacking doubling" ability.
> 
> However, once we've picked an "attack doubling" ability, we then randomly pick _which_ attack doubling ability to use randomly. So it is entirely expected to see both Huge and Pure Power in the same seed; this is 100% expected and won't change. What "Combine Duplicate Abilities" does is adjust _how often_ Huge Power and Pure Power appear by adjusting the probability of their appearances.

Okay, thanks for clearing that up!
