### ISSUE TITLE
Pokemon ultra moon call rate

### ISSUE THREAD

**Issue by allert12** [Ajarmar/universal-pokemon-randomizer-zx#68]
Hey! i love that you made the universal randomizer for 3ds games, i already randomized pokemon ultra moon. I checked the box which turns on that every pokemon can call for allies, but it seems that the call rates are really low? I would really like to know how these call rates have been set for pokemon that couldnt call for help before. Maybe there is a setting to set a minimum call rate for pokemon? I hope my question is not too dumb lol.

**Comment by tom-overton** [comment]
The "All Wild Pokemon Can Call Allies" misc. tweak will give every Pokemon *at least* a call rate of 3. If the Pokemon already had a call rate higher than 3, the setting won't change it. For reference, 3 is the smallest non-zero call rate that GameFreak used in the original game; you can see a list of all call rates in the original game here: https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_call_rate

As for your other question, there is currently no setting to set a minimum call rate. Is there a particular reason why you want the call rate raised?

**Comment by allert12** [comment]
Hello! Thanks for the answer, the particular reason i want the call rate to be higher is because i want to shiny hunt and get pokemon with good IV's. Of course setting a mininum call rate too high would be a bit cheaty, so that's not what i really want. But about the tweak, you say it will give a pokemon of at least 3, so is this also randomly generated for each randomized pokemon? Or is this already been decided by the maker what pokemon get what call rate?

**Comment by tom-overton** [comment]
After talking with Ajarmar about it and calculating the odds of a Pokemon calling an ally and the odds of the call being successfully answered, we decided to bump the call rate of Pokemon affected by this setting from 3 to 5. With a call rate of 5, a wild Pokemon with 20% or less of their max HP will have a 50% chance to call for help each turn assuming that an Adrenaline Orb has been used in that battle; the odds of the call being answered successfully ranges between 20% all the way to 100% depending on various conditions.

Note that Pokemon that already have a non-zero call rate are *not* affected by this. As an example, Gyarados has a call rate of 3 in the original Gen 7 games, and it will *still* have a call rate of 3 when using the "All Wild Pokemon Can Call Allies" setting. This *only* affects Pokemon that either (a) had a call rate of 0 before, or (b) didn't have a call rate at all. As for your other question, this call rate tweak is not random. Every Pokemon will have the same call rate for every single randomized seed that you make.

This is as high as we felt comfortable increasing the call rate; we wanted to make it a little easier to engage with the SOS battle mechanics if you want while avoiding being incredibly annoying to users who would rather ignore it.
