### ISSUE TITLE
refuses to reset in citra

### ISSUE THREAD

**Issue by periwinklerene** [Ajarmar/universal-pokemon-randomizer-zx#69]
trying to reset after a failed nuzlocke, and nothing is working. Pressing all the right buttons, every other input works, but not a reset.

**Comment by tom-overton** [comment]
I have no issues resetting a randomized CXI. I sincerely doubt this has anything to do with the randomizer; can you try resetting an original, unrandomized version of the game?

**Comment by tom-overton** [comment]
@periwinklerene Did you ever get this working?

**Comment by periwinklerene** [comment]
I didn't actually. I just manually removed the save every time. No idea what the issue was.
________________________________

**Comment by tom-overton** [comment]
Huh, odd. Did you try using an original, unrandomized version? If you did, did soft reset work?

**Comment by periwinklerene** [comment]
No, I didn’t, but my friend using the same version of citra and randomizer could do it just fine

Thank you for your time!
Julia Thomas
________________________________
