### ISSUE TITLE
Additional Pokemon For... not working on 3rd gen?

### ISSUE THREAD

**Issue by Boso101** [Ajarmar/universal-pokemon-randomizer-zx#70]
Not sure if it just hasn't been implemented for Gen 3, but none of the additional party Pokémon options are active for gen 3

**Comment by tom-overton** [comment]
That's correct, the option is for Gens 4 and up, so it shouldn't show up for anything earlier than that. It is difficult to implement in Gens 1-3.

**Comment by Boso101** [comment]
Ah thats okay. I'm guessing its a challenge due to how the overall codebase was structured from the beginning. I have however implemented something like that in my own fork of "Hopeless Trainer Editor" which is written in C#. But it's basic and simply makes every trainer have 6 mons. Wondering if anything can be scavenged from it

**Comment by tom-overton** [comment]
Huh, interesting! Thanks for bringing this to my attention! You're right about why it's a challenge; we simply didn't want to mess with it given that we weren't sure where we would store the data for the new Pokemon. Gens 4-7 make it easy by defining trainer data as a bunch of files that can be easily expanded at will, so we just limited it to that to keep it easy for ourselves. I have no promises that it will actually result in anything, but I'll definitely take a look at Hopeless Trainer Editor and see what I can gleam from it.

**Comment by tom-overton** [comment]
Hey responding to this insanely late, but I got it working in b3099e0ba99eda72218bc3453c3a5761c526b2d5. Turns out support for repointing trainer data was *already implemented* so it was extraordinarily easy to get this working.
