### ISSUE TITLE
[Help] Setting up the dev environment

### ISSUE THREAD

**Issue by IronhideIvan** [Ajarmar/universal-pokemon-randomizer-zx#717]
Hello! There are some small tweaks I would like to make in order to fit some specific randomization criteria I'd like to see in my personal copy of HGSS, which unfortunately aren't covered by the out-of-the-box randomizer. 

I'm trying to build and run the code on my local machine and would like some help getting things set up, if possible. Is there any documentation on setting up and running the developer environment for this code base? I tried running the project through Eclipse and I'm having some trouble. I'm not sure what extensions or additional tools are necessary.

Thanks very much.

**System (please fill in the following information):**
 - Operating System: mac Sonoma 14
 - Randomizer Version: master

**Comment by Qvdpost** [comment]
The WIki linked in the Readme specifies the use of Intellij Idea and is what worked really well for me so far. Check it out over at [the Wiki Page](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Building-Universal-Pokemon-Randomizer-ZX)

**Comment by IronhideIvan** [comment]
Thanks @Qvdpost! I was able to get up and running with Intellij. I appreciate the info.
