### ISSUE TITLE
game crash when I open the shop pokemon black

### ISSUE THREAD

**Issue by Baat01** [Ajarmar/universal-pokemon-randomizer-zx#72]
I've randomize the special shop in pokemon black , but when I open the shop menu in the pokemon center (buy menu) the game crash
I've tried randomize my game using both the non launcher and launcher app (using the same seed and string)
I'm playing on a french rom of pokemon black
Randomizer Version: 4.0.2
Random Seed: 167441274844727
Settings String: 313AygEbgjuAfEB9AEEABClAxkyKgGyFAAFGAABEwAAAAAAAAAAxpnG0doJCTIICBFQb2tlbW9uIEJsYWNrIChGKXg975TjwziK
 
I think the option I put are :
Special shop : random
ban bad items
ban regular items
guarantee evolution items

I didn't see anywhere that bug so  i post here but I may have miss it

anyway I LOVE that randomizer, and i wasn't aware until today that it had an update (i was using an old version of that randomizer since 2017) and I'm so excited to try the new feature like shop randomizer that looks amazing

**Comment by Baat01** [comment]
i don't know by what it was caused but, after randomizing another rom, this time putting ban op items and balance item price it work normally

**Comment by Baat01** [comment]
however ther is another issue with the shop : 1: i can still see the old items :
![image](https://user-images.githubusercontent.com/75745165/101793453-1dc19300-3b06-11eb-84f9-ea251e321bbf.png)
![image](https://user-images.githubusercontent.com/75745165/101793541-3467ea00-3b06-11eb-9b33-ebe1ce195017.png)
2: in the regular shop, there is a lot of additionnal items, including bugged items
![image](https://user-images.githubusercontent.com/75745165/101793689-5c574d80-3b06-11eb-99da-d20856cfb238.png)
![image](https://user-images.githubusercontent.com/75745165/101793720-64af8880-3b06-11eb-9073-d4238f56604b.png)
![image](https://user-images.githubusercontent.com/75745165/101793764-709b4a80-3b06-11eb-811b-b2a63250453d.png)
i can't figure out in the log file frome where there are
i'm still using pokemon black french version, however this time my settings are :
Random Seed: 146059386642678
Settings String: 313ASgEfgjuAfEB9AEEABCoAxkyKgGyFAABGAABGwAAAAAAAAAAxvnG0doICTIIBhFQb2tlbW9uIEJsYWNrIChGKdSgNHbjwziK

**Comment by Baat01** [comment]
also striaton city only have heal ball
![image](https://user-images.githubusercontent.com/75745165/101801053-43529a80-3b0e-11eb-9359-7345247e0c1a.png)
![image](https://user-images.githubusercontent.com/75745165/101801073-48174e80-3b0e-11eb-8783-d33c8cc1eb98.png)

**Comment by tom-overton** [comment]
I took a look and I understand the problem. What's happening here is that we based our offsets for where the shop data is located in the ROM on the US version, and it is located in a different place in the French version. I'll fix this for the next release, but until then, you'll need to use the US version if you want shop randomization to work. And in general, we tend to use the US versions of every game for testing, so we can't strictly guarantee that everything will work in other versions. We appreciate the bug reports for non-US versions (if you see anything else that doesn't work, please let us know!), but at the same time, we recommend using the US version if you run into issues.

**Comment by Baat01** [comment]
okay thank you, i was also a bit thinking of a problem like this, but i don't know anything about rom data
I'm gonna test a rom of hearthgold and soulsilver with a friend,that time in US, if there is anything else that bug, I will report it too
expect to see me a lot, I love pokemon and especially randomizing pokemon XD
