### ISSUE TITLE
Launcher is going to cmd reading "'java' is not recognized as an internal or external command, operable program or batch file." [Bug] 

### ISSUE THREAD

**Issue by Vohkee** [Ajarmar/universal-pokemon-randomizer-zx#726]
**Describe the bug**
Just downloaded. When I run the Windows launcher, it says 'java' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Vohkee** [comment]
I'm an idiot. Fixed it.

**Comment by LoganTheWisest** [comment]
how did you fix it?

**Comment by IceburgLettuce17** [comment]
@LoganTheWisest installing jav duh. also sorry for the necro

**Comment by IceburgLettuce17** [comment]
mb i meant java*
