### ISSUE TITLE
Error message when attempting to "Randomize (Save)" my Pokemon Moon Rom

### ISSUE THREAD

**Issue by viggoj10** [Ajarmar/universal-pokemon-randomizer-zx#74]
![image](https://user-images.githubusercontent.com/70344736/101998653-fdbadc80-3c89-11eb-8fc8-a059a48ec525.png)

This error message pops up when I attempt to make a randomized file of Pokemon Moon as a CIX or FSLayered file.

The log file reads as follows:

![image](https://user-images.githubusercontent.com/70344736/101998672-31960200-3c8a-11eb-83aa-7a5996a72256.png)

Is the problem something with my version of Java specifically, my Pokemon Moon .3DS Rom, Some specific setting in the Randomizer, or something else I am not aware of? I do have the latest version (4.0.2) downloaded, as well as both Offline and Online x64 Java versions.

**Comment by tom-overton** [comment]
Can you post the error log in text form? I tried manually entering the seed and settings string by hand from your screenshot and it randomized successfully for me. However, I could've made a mistake in typing the seed or settings.

[test.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5684341/test.log)

**Comment by viggoj10** [comment]
Randomizer Version: 4.0.2
Seed: 53746773970927
Settings String: 313OQgE+kLRAtQC1wIEAAKoJBhESgAAFAAVCQABcgAAAAAAAoAItsm0wSQhojIICAxQb2tlbW9uIE1vb247PwIY48M4ig==
Java Version: 1.8.0_271, Java HotSpot(TM) 64-Bit Server VM
ROM: Pokemon Moon
Code: CTR-P-BNEA
Reported Support Level: Complete

java.lang.ArrayIndexOutOfBoundsException: 72
	at com.dabomstew.pkrandom.romhandlers.Abstract3DSRomHandler.readWord(Abstract3DSRomHandler.java:208)
	at com.dabomstew.pkrandom.romhandlers.Gen7RomHandler.getMovesLearnt(Gen7RomHandler.java:1623)
	at com.dabomstew.pkrandom.romhandlers.Gen7RomHandler.removeImpossibleEvolutions(Gen7RomHandler.java:2221)
	at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:236)
	at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$performRandomization$99(NewRandomizerGUI.java:847)
	at java.lang.Thread.run(Unknown Source)

**Comment by viggoj10** [comment]
Side note: I have tested a few different options and it seems that specific Randomizations such as "Fix Impossible Evos" and randomizing Foe Pokemon are the cause of the problem. If I randomize without those options it works correctly, but ofc I would like to be able to have access to as many options as possible.

**Comment by tom-overton** [comment]
Hmm, using that same seed and settings string randomizes fine for me:
[test.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5691000/test.log)

Just to double check, this isn't a ROMhack or anything like that, right? The error basically indicates that a Pokemon's moveset doesn't end with the expected terminator, That's usually an indication of either a ROMhack or a bad ROM.

**Comment by tom-overton** [comment]
Closing as it's been a month without a response
