### ISSUE TITLE
Can't open via the launcher

### ISSUE THREAD

**Issue by BobberDuck** [Ajarmar/universal-pokemon-randomizer-zx#75]
So I just downloaded the zip file but my computer won't open the launcher file, however, it will open the PokeRandoZX.jar file. There is no error message that comes up just when I click open nothing happens. I looked at the task manager and it didn't show anything running after clicking to open. I've also tried deleting and reinstalling the randomizer and moving it out of the downloads folder. BTW I'm on Windows 10 if that helps.

**Comment by viggoj10** [comment]
You are going to need to download the latest version of Java for your specific computer whether that be 64-bit or 32-bit you must find out in the settings (here are some instructions: https://windowsloop.com/find-if-pc-is-32-bit-or-64-bit/#:~:text=How%20to%20Check%20If%20Your%20Computer%20Is%2032,64-bit.%205%205.%20Use%20a%20Third-party%20Tool.%20)

**Comment by tom-overton** [comment]
You'll need to have a 64-bit version of Java installed to use the launcher. We have a wiki page about Java requirements here: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java

When you start the launcher, it should make a file called `launcher-log.txt` in the same directory. What does that say for you?

**Comment by BobberDuck** [comment]
I used the links and confirmed that I am using the right version of Java and have a 64-bit computer. I also can't find a file called launcher-log.txt. Should I try uninstalling and redownloading Java?

**Comment by Ajarmar** [comment]
Can you try running the launcher from the command prompt and see if that gives you an error message? Open a command prompt window in the folder where you have the launcher and type `java -jar launcher.jar`

**Comment by BobberDuck** [comment]
I tried it, it says "Unable to access jarfile launcher.jar"
