### ISSUE TITLE
the launcher wont run

### ISSUE THREAD

**Issue by confusedbloke** [Ajarmar/universal-pokemon-randomizer-zx#76]
i have installed the latest version of java and am running on a 64 bit computer. both the launcher and the PokeRandoZX files are 
folders for me when i extract them. i rename them to .jar files and they still dont work. i went into the launcher folder and found a launcher.class file which i renamed to launcher.java. this turned it into a java file but every time i open it pops a black screen for a second and then disappears. if you could maybe tell me what im doing wrong i would be very aprreciative.

**Comment by zincarla** [comment]
Sounds like you downloaded the source code. You need the compiled jar files. These can be downloaded in the releases section. Latest one is [here](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases/download/v4.0.2/PokeRandoZX-v4_0_2.zip)

**Comment by tom-overton** [comment]
This can happen if you have a program other than Java assigned as the "default program" for JAR files. If you right click on a JAR file, click "Open with" and choose to open it with Java, you should be able to run the program. (You should also be able to set Java as the default program.)

If you don't have Java installed, read this page for more info: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java

**Comment by tom-overton** [comment]
Closing all issues related to the launcher not working because #93 is the home for that sort of thing now. @confusedbloke go there and try the workarounds listed.
