### ISSUE TITLE
Pokemon Y playing as normal and not randomized?

### ISSUE THREAD

**Issue by grayknight224** [Ajarmar/universal-pokemon-randomizer-zx#77]
Im using citra canary. I used the randomizer and even got a log showing all the changes it was supposed to make. I made sure I launched the correct file and everything however when i play my game nothing in it is randomized at all. Is anyone else running into the same issue or is there a way to solve this?

**Comment by zincarla** [comment]
I ran into something similar. Are you using a patched version of the rom? For me, it was due to me using the randomizer on a non-patched version of the rom, then patching the randomized rom in citra. The fix was to load the patch into the randomizer and re-randomize the rom. Worked perfectly.

**Comment by tom-overton** [comment]
@grayknight224 Zincarla is exactly right. If the version in the randomizer does *not* match the version in your emulator or on your 3DS, then we can't guarantee that the randomization works correctly. There's a [little more detail on the wiki](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Randomizing-the-3DS-games#3ds-game-updates) if you want more info.

You can see what version you're running in Citra by checking the bottom-right corner of the title screen, as seen in this image: 
![image](https://user-images.githubusercontent.com/12245827/102726917-2caeff00-42d7-11eb-9215-d1425399823a.png)

You'll need to make sure that you either:
a. Load the same update in the randomizer, or
b. Delete the game update from Citra

**Comment by tom-overton** [comment]
@grayknight224 Did you ever get this working? This looks like a standard version mismatch issue so I'm thinking of closing it

**Comment by tom-overton** [comment]
Closing as OP is MIA. Feel free to reopen it if you want.
