### ISSUE TITLE
Sketch Only Mode

### ISSUE THREAD

**Issue by Luigimeansme** [Ajarmar/universal-pokemon-randomizer-zx#81]
I don't know if this has been suggested before or even if it can be implemented, but I think a really good idea for the randomzier could be so when you catch a Pokemon it replaces all it's moves with Sketch so you have to fight other Pokemon to get a moveset. Uncaught Wild Pokemon and Trainers would still have randomized moves but as soon as one joins your team, it immediately changes to only learn Sketch.

**Comment by tom-overton** [comment]
Sorry, but we don't take feature requests.
