### ISSUE TITLE
Gen 6 (XY) - Oversight causing infinite Korrina battle softlock

### ISSUE THREAD

**Issue by idontwantanaccount69** [Ajarmar/universal-pokemon-randomizer-zx#85]
The battle with Korrina (the two lucario) when randomized, causes an infinite loop because Korrina forces you to battle her over and over again until you mega evolve your pokemon, which is impossible if the randomizer gives the player a non-mega evolvable pokemon and no mega stone for it. This leaves XY unbeatable after being randomized since this battle is mandatory.

**Comment by tom-overton** [comment]
Can you provide a log file? We believe we fixed this with commit 906b131031453634d70138a77ad4deae3599ef52, which ended up being released in 4.0.1. So if your seed was generated with 4.0.0, then yeah, this is an already-fixed issue. If your seed was generated with 4.0.1 or 4.0.2, though, then we'll need to investigate.

**Comment by idontwantanaccount69** [comment]
Ah, i believe we did use 4.0.0. Apologies for wasting your time, I must have missed it in the update notes.
