### ISSUE TITLE
I was going through the randomised game pretty smoothly then I came across a totem pokemon in the first totem trial and once the battle animation started it froze and gave me an error. Is there any information on how to fix this problem?

### ISSUE THREAD

**Issue by Karurosu007** [Ajarmar/universal-pokemon-randomizer-zx#88]
![20201229_032205](https://user-images.githubusercontent.com/76731037/103277499-61315380-4986-11eb-8300-7345d37ff88c.jpg)

![1609239321446680271071491233802](https://user-images.githubusercontent.com/76731037/103278861-b884f300-4989-11eb-9517-c9ec2cd1dee5.jpg)

**Comment by tom-overton** [comment]
If there *is* information on how to fix the problem, it's contained within the log file. Did you make a log for this seed? If so, can you upload it?

**Comment by Karurosu007** [comment]
Alright I'll find the log then post it and it'll take some time but I'll respond with something.

**Comment by Karurosu007** [comment]
> If there _is_ information on how to fix the problem, it's contained within the log file. Did you make a log for this seed? If so, can you upload it?
I can't find the log for the seed but is it possible to create a new log or not? If that is not possible have there been cases where a game errors due to fighting pokemon or trainers?

**Comment by tom-overton** [comment]
Without a log, I can't diagnose *why* the crash is occurring. And if you make a new seed, it won't be the same as this particular seed, meaning it probably won't crash. What's probably happening is that your game attempted to spawn an invalid Pokemon here but without the log, I have no clue as to what that may be. If you outputted as layeredFS, you might be able to upload the a/1/5/9 file, since that is where the totem Pokemon are defined.

**Comment by Karurosu007** [comment]
Ok I made it into a layeredFS now I need to figure out how to find the a/1/5/9 file

**Comment by Karurosu007** [comment]
![1609265948427990423139219728437](https://user-images.githubusercontent.com/76731037/103305198-be99c480-49c7-11eb-96d9-85a83d2114b4.jpg)

**Comment by tom-overton** [comment]
Can you send me "9 file.txt" without converting it to a text file first? That's the correct file, but the process of converting it to a text file corrupted it and rendered it unusable. I just need that file to diagnose what's going on.

**Comment by Karurosu007** [comment]
[9.file.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5753784/9.file.txt)

**Comment by tom-overton** [comment]
@Karurosu007 Any update on this? I'm still looking for the file not converted to a text file.

**Comment by tom-overton** [comment]
I'm almost *certain* I fixed this with d8a728eec06ec45c41807c316c33f3476af6dd31. When 4.1.0 comes out (hopefully soon!), give it a try and see if that resolves the issue.
