### ISSUE TITLE
Feature Request: Option to have move learnset follow evolution

### ISSUE THREAD

**Issue by Wyatts** [Ajarmar/universal-pokemon-randomizer-zx#89]
Playing BW recently, something I've encountered semi-frequently is I'll drop a move for one reason or another but want it back after evolution.  Unfortunately, the move rememberer can't help me there because the learnset (and, I think, TM compat too?) has completely changed.  There's definitely fun to be had with this situation, but I'd like to have a toggle for a more traditional experience.

**Comment by tom-overton** [comment]
Sorry, but we don't take feature requests.
