### ISSUE TITLE
Feature Request: Update area in pokedex

### ISSUE THREAD

**Issue by Wyatts** [Ajarmar/universal-pokemon-randomizer-zx#90]
This is kind of a long shot because I suspect it'd be a lot of work, but it'd be awesome if I could look at the AREA tab of the pokedex and see where I can find something I've seen before.

(Playing BW right now, if it's relevant; not sure if this is already in place for other games in the series.)

**Comment by tom-overton** [comment]
Sorry, but we don't take feature requests. However, this particular request was actually already done in commit baac8b826acb53a16d85ee2af09d401c5d2567a9 and will be included in the 4.1.0 release, so you're in luck.
