### ISSUE TITLE
Names don't randomize in non-english OR/AS

### ISSUE THREAD

**Issue by FaeyUmbrea** [Ajarmar/universal-pokemon-randomizer-zx#92]
I randomized my ORAS and started in german, since it's my mothertongue.
The translated trainer names appear to be hardcoded and dont randomize if you dont select english.

I assume this will entail decoding and randomizing the classes on all translation files, but it would be nice to see.

**Comment by tom-overton** [comment]
Our policy is that English is the only language that all features in the randomizer *officially* support. However, this was easy enough that I just knocked it out pretty quick. It will be in the next release of the randomizer.
