### ISSUE TITLE
Custom Trainer Names and Classes in Gen. 7

### ISSUE THREAD

**Issue by SylphOswell** [Ajarmar/universal-pokemon-randomizer-zx#95]
Hello,

I tried to randomnize a Ultra Sun and Moon rom, but in the process, the randomnizer doesnt seem to randomnize custom trainer classes and names. I also turned "Randomnize Trainer Names" and "Randomnize Trainer Class Names" in the Foe Section on but with no success. Is it any way to fix this or isnt it supported for this game or in the first place?

**Comment by tom-overton** [comment]
Can you be a bit more specific? This functionality should work fine when playing in English. If you're *not* playing in English, then it will not work until the next release of the randomizer, as per issue #92

**Comment by SylphOswell** [comment]
This solves the question. Didint saw this on the page. Thx
