### ISSUE TITLE
How do I open this?

### ISSUE THREAD

**Issue by revoltinsurgence** [Ajarmar/universal-pokemon-randomizer-zx#97]
This is dumb, I know - but there's no .exe in the zip file downloaded, what do I have to do to run it?

**Comment by tom-overton** [comment]
The first two lines of README.txt explain it pretty well:
```
1. HOW TO USE

Just double click launcher.jar and it will start the randomizer program.
```

You need Java to launch .jar files. For more information, see our [page about Java requirements](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java)

**Comment by revoltinsurgence** [comment]
> The first two lines of README.txt explain it pretty well:
> 
> ```
> 1. HOW TO USE
> 
> Just double click launcher.jar and it will start the randomizer program.
> ```
> 
> You need Java to launch .jar files. For more information, see our [page about Java requirements](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java)

I... think I have the wrong zip then. Is it not the dropdown of the Code button, or something else?

**Comment by tom-overton** [comment]
No, that dropdown gives you the source code. If you want releases that will run on your computer, head over to our releases page: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases
